MODON MRE BPDEV/force-app/main/default/objects/Unit__c/Unit__c.object-meta.xml
<CustomObject>
    <description>This object is part of inventory management to store the unit details</description>
    <label>Unit</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Units</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

MODON MRE BPDEV/force-app/main/default/objects/Unit__c/fields/ApprovalStatus__c.field-meta.xml
<CustomField>
    <fullName>ApprovalStatus__c</fullName>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Released</fullName>
            </value>
            <value>
                <fullName>UnReleased</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
                <isActive>false</isActive>
                <label>Approved</label>
            </value>
            <value>
                <fullName>Awaiting Approval</fullName>
                <isActive>false</isActive>
                <label>Awaiting Approval</label>
            </value>
            <value>
                <fullName>Blocked</fullName>
                <isActive>false</isActive>
                <label>Blocked</label>
            </value>
            <value>
                <fullName>Rejected</fullName>
                <isActive>false</isActive>
                <label>Rejected</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

MODON MRE BPDEV/force-app/main/default/objects/Unit__c/fields/BlockedFor__c.field-meta.xml
<CustomField>
    <fullName>BlockedFor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Blocked For</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Units1</relationshipName>
    <type>Lookup</type>
</CustomField>

MODON MRE BPDEV/force-app/main/default/objects/Unit__c/fields/Payment_Hold_By__c.field-meta.xml
<CustomField>
    <fullName>Payment_Hold_By__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment Hold By</label>
    <referenceTo>User</referenceTo>
    <relationshipLabel>Payment Hold Units</relationshipLabel>
    <relationshipName>Payment_Hold_Units</relationshipName>
    <type>Lookup</type>
</CustomField>

MODON MRE BPDEV/force-app/main/default/objects/Unit__c/fields/Payment_Hold_Expiry__c.field-meta.xml
<CustomField>
    <fullName>Payment_Hold_Expiry__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Payment Hold Expiry</label>
    <type>DateTime</type>
</CustomField>

MODON MRE BPDEV/force-app/main/default/objects/Unit__c/fields/Payment_In_Progress__c.field-meta.xml
<CustomField>
    <fullName>Payment_In_Progress__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Payment In Progress</label>
    <type>Checkbox</type>
</CustomField>

MODON MRE BPDEV/force-app/main/default/objects/Unit__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Unit Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Available</fullName>
            </value>
            <value>
                <fullName>Sold</fullName>
            </value>
            <value>
                <fullName>CCMD</fullName>
            </value>
            <value>
                <fullName>Reserved</fullName>
            </value>
            <value>
                <fullName>UnReleased</fullName>
            </value>
            <value>
                <fullName>Blocked</fullName>
                <isActive>false</isActive>
                <label>Blocked</label>
            </value>
            <value>
                <fullName>Booked</fullName>
                <isActive>false</isActive>
                <label>Booked</label>
            </value>
            <value>
                <fullName>Booking cancelled</fullName>
                <isActive>false</isActive>
                <label>Booking cancelled</label>
            </value>
            <value>
                <fullName>Booking confirmed</fullName>
                <isActive>false</isActive>
                <label>Booking confirmed</label>
            </value>
            <value>
                <fullName>Booking in progress</fullName>
                <isActive>false</isActive>
                <label>Booking in progress</label>
            </value>
            <value>
                <fullName>Draft</fullName>
                <isActive>false</isActive>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Leased</fullName>
                <isActive>false</isActive>
                <label>Leased</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

MODON MRE BPDEV/force-app/main/default/objects/Unit__c/fields/Sub_Status__c.field-meta.xml
<CustomField>
    <fullName>Sub_Status__c</fullName>
    <label>Sub Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Assigned</fullName>
            </value>
            <value>
                <fullName>Un-Assigned</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

MODON MRE BPDEV/force-app/main/default/classes/SalesOperationUnitSearch.cls
/**
 * ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
 * Class Name      : SalesOperationUnitSearch
 * Author          : Kumaravel Mathivanan
 * Created Date    : Apr 1, 2026
 * Last Modified By: Kumaravel Mathivanan
 * Last Modified On: Apr 1, 2026
 * Description     : This class implements for sales operation unit search
 *  
 * Change History  :
 *  Date          │   Author     │   Change
 * ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
 *  Apr 1, 2026  │ Kumaravel Mathivanan   │ Initial version
 * ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
 */

public with sharing class SalesOperationUnitSearch {
    @AuraEnabled(cacheable=false)
    public static List<Unit__c> searchUnits(String searchKey) {
        Id loggedInUserId = UserInfo.getUserId();
        
        return [
            SELECT Id, Name, Source_Entity__c, ApprovalStatus__c, 
                   Sub_Status__c, Status__c, BlockedFor__c
            FROM Unit__c
            WHERE Name LIKE :('%' + searchKey + '%')
            AND Source_Entity__c != 'Modon - Egypt'
            AND ApprovalStatus__c = 'Released'
            AND Status__c = 'Available'
            AND (
                 ((Sub_Status__c = 'Un-Assigned' AND BlockedFor__c = null )  or (Sub_Status__c = 'Assigned' AND BlockedFor__c = :loggedInUserId) )
            )
            AND (Payment_In_Progress__c = false OR Payment_Hold_Expiry__c < :System.now() OR Payment_Hold_By__c = :loggedInUserId)
            LIMIT 50
        ];
    }
}