MODON MRE BPDEV/force-app/main/default/objects/Receipt__c/Receipt__c.object-meta.xml
<CustomObject>
    <label>Payment</label>
    <nameField>
        <displayFormat>R-{00000}</displayFormat>
        <label>Receipt No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

MODON MRE BPDEV/force-app/main/default/objects/Receipt__c/fields/IPGTransactionId__c.field-meta.xml
<CustomField>
    <fullName>IPGTransactionId__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>IPGTransactionId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

MODON MRE BPDEV/force-app/main/default/objects/Receipt__c/fields/PaymentGatewayRawResponse__c.field-meta.xml
<CustomField>
    <fullName>PaymentGatewayRawResponse__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Payment Gateway Raw Response</label>
    <length>50000</length>
    <type>LongTextArea</type>
</CustomField>

MODON MRE BPDEV/force-app/main/default/objects/Receipt__c/fields/PaymentStatus__c.field-meta.xml
<CustomField>
    <fullName>PaymentStatus__c</fullName>
    <description>This is for Payment Gateway</description>
    <inlineHelpText>This is for Payment Gateway</inlineHelpText>
    <label>Payment Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>APPROVED</fullName>
            </value>
            <value>
                <fullName>REJECTED</fullName>
            </value>
            <value>
                <fullName>FAILED</fullName>
            </value>
            <value>
                <fullName>WAITING</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

MODON MRE BPDEV/force-app/main/default/objects/Receipt__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In Progress</fullName>
                <default>true</default>
                <label>In Progress</label>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Reversed</fullName>
            </value>
            <value>
                <fullName>Cleared</fullName>
            </value>
            <value>
                <fullName>Bounced</fullName>
            </value>
            <value>
                <fullName>Received</fullName>
            </value>
            <value>
                <fullName>Remitted</fullName>
            </value>
            <value>
                <fullName>Returned</fullName>
            </value>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>Returned to customer</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
                <isActive>false</isActive>
                <label>Draft</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

MODON MRE BPDEV/force-app/main/default/objects/Receipt__c/fields/TransactionDateTimePGWinText__c.field-meta.xml
<CustomField>
    <fullName>TransactionDateTimePGWinText__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>TransactionDateTime PGW in Text</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

MODON MRE BPDEV/force-app/main/default/classes/PaymentGWController.cls
/**********************************************************************************************************************
* Name               : PaymentGWController                                                       
* Description        : This is a class to read the output of payment gateway URL params.
* Usage              : 
* Created By         : PwC Digital Middle East                                                     
* --------------------------------------------------------------------------------------------------------------------
* Version       Author                      Date            Comment                                                                       
* 1.0           Anil Valluri                18 Jan 2024     Initial Draft   
******************************************************************************************************************/    

public without sharing class PaymentGWController {
    
    public string resp {get; set;}
    public string paymentStatus {get; set;}

    public void paymentGWURLResponseCtrl() {

        try{
            resp = JSON.Serialize(ApexPages.currentPage().getParameters());
            system.debug('Payment gateway URL params::::: ' + resp);

            // check response and process..
            string recId = ApexPages.currentPage().getParameters().get('oid');
            paymentStatus = ApexPages.currentPage().getParameters().get('status');
            string IPGTransactionID = ApexPages.currentPage().getParameters().get('ipgTransactionId');
            string transactionDateTimePW = ApexPages.currentPage().getParameters().get('txndatetime');

            if(recId <> null && recId <> ''){
                Receipt__c receiptToUpdate = new Receipt__c();

                if(recId.contains('_'))
                receiptToUpdate.Id = recId.substringBefore('_');
                else 
                receiptToUpdate.Id = recId;
            
                receiptToUpdate.PaymentStatus__c = paymentStatus;

                if(paymentStatus == 'APPROVED' || paymentStatus == 'SUCCESS') 
                receiptToUpdate.Status__c = 'Approved';
                else //if(paymentStatus == 'FAILED' || paymentStatus == 'REJECTED')
                receiptToUpdate.Status__c = 'Rejected';

                receiptToUpdate.PaymentGatewayRawResponse__c = resp;
                receiptToUpdate.IPGTransactionId__c = IPGTransactionID;
                receiptToUpdate.TransactionDateTimePGWinText__c = transactionDateTimePW;

                update receiptToUpdate;
            }
        }
        catch(Exception e) {        
            LoggerService.save(LoggerService.createApexLog(e,'PaymentGWController','PaymentGWController.paymentGWURLResponseCtrl',''));
            system.debug('Error:::: ' + e.getMessage() + ' Trace::: ' + e.getStackTraceString());
        }   
    } 
}