MODON MRE BPDEV/force-app/main/default/objects/Receipt__c/Receipt__c.object-meta.xml
<CustomObject>
    <label>Payment</label>
    <nameField>
        <displayFormat>R-{00000}</displayFormat>
        <label>Receipt No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

MODON MRE BPDEV/force-app/main/default/objects/Receipt__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Payments</relationshipLabel>
    <relationshipName>Receipts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

MODON MRE BPDEV/force-app/main/default/classes/PaymentGWControllerTest.cls
@isTest
public class PaymentGWControllerTest {
 
    @isTest
    static void myTestMethod(){
        PaymentGWController myClsObj = new PaymentGWController();
        
        Account acc = new Account();
        acc.name = 'Test Account';
        insert acc;
        
        Receipt__c recObj = new Receipt__c();
        recObj.Account__c = acc.Id;
        insert recObj;
        
        Test.setCurrentPageReference(new PageReference('/apex/Receipt__c?oid=' + recObj.Id));
        test.StartTest();
            myClsObj.paymentGWURLResponseCtrl();
        test.stoptest();
    }
}