MODON MRE BPDEV/force-app/main/default/objects/Receipt__c/Receipt__c.object-meta.xml
<CustomObject>
    <label>Payment</label>
    <nameField>
        <displayFormat>R-{00000}</displayFormat>
        <label>Receipt No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

MODON MRE BPDEV/force-app/main/default/objects/Receipt__c/fields/AppliedAmount__c.field-meta.xml
<CustomField>
    <fullName>AppliedAmount__c</fullName>
    <label>Applied Amount</label>
    <summarizedField>Allocation__c.AllocationAmount__c</summarizedField>
    <summaryFilterItems>
        <field>Allocation__c.Status__c</field>
        <operation>equals</operation>
        <value>Applied</value>
    </summaryFilterItems>
    <summaryForeignKey>Allocation__c.Receipt__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

MODON MRE BPDEV/force-app/main/default/objects/Receipt__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In Progress</fullName>
                <default>true</default>
                <label>In Progress</label>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Reversed</fullName>
            </value>
            <value>
                <fullName>Cleared</fullName>
            </value>
            <value>
                <fullName>Bounced</fullName>
            </value>
            <value>
                <fullName>Received</fullName>
            </value>
            <value>
                <fullName>Remitted</fullName>
            </value>
            <value>
                <fullName>Returned</fullName>
            </value>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>Returned to customer</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
                <isActive>false</isActive>
                <label>Draft</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

MODON MRE BPDEV/force-app/main/default/objects/Receipt__c/fields/TotalAmount__c.field-meta.xml
<CustomField>
    <fullName>TotalAmount__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Total Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

MODON MRE BPDEV/force-app/main/default/objects/Receipt__c/recordTypes/Receipt.recordType-meta.xml
<RecordType>
    <fullName>Receipt</fullName>
    <active>true</active>
    <label>Receipt</label>
</RecordType>

MODON MRE BPDEV/force-app/main/default/classes/ReceiptPdfController.cls
/**-------------------------------------------------------------------
 * Description : Controller for Receipt PDF Vf page
 * -------------------------------------------------------------------
 * Version      Author           Date               Comment
 * -------------------------------------------------------------------
 * v1.0         Abdallah Hdaib   15-02-2024         Code Creation
 * -------------------------------------------------------------------
 * Notes: NaN
*/
public with sharing class ReceiptPdfController {

    public Receipt__c receipt {get;set;}

    public ReceiptPdfController() {
        String receiptId = ApexPages.currentPage().getParameters().get('receiptId');
        receipt = [SELECT Id, Name, Status__c, AppliedAmount__c, TotalAmount__c FROM Receipt__c WHERE Id = :receiptId];Apexpages.currentPage().getHeaders().put('content-disposition', 'inline; filename=test');
    }
}