MODON MRE BPDEV/force-app/main/default/objects/Contact/fields/EIDNumber__c.field-meta.xml
<CustomField>
    <fullName>EIDNumber__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Emirates ID Number</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

MODON MRE BPDEV/force-app/main/default/objects/Contact/fields/EmiratesIDExpiryDate__c.field-meta.xml
<CustomField>
    <fullName>EmiratesIDExpiryDate__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Emirates ID Expiry Date</label>
    <type>Date</type>
</CustomField>

MODON MRE BPDEV/force-app/main/default/objects/EscrowAccount__c/EscrowAccount__c.object-meta.xml
<CustomObject>
    <label>Escrow Account</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Escrow Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Escrow Accounts</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

MODON MRE BPDEV/force-app/main/default/objects/Milestone__c/Milestone__c.object-meta.xml
<CustomObject>
    <label>Milestone</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Milestone Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Milestone</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

MODON MRE BPDEV/force-app/main/default/objects/Milestone__c/fields/Phase__c.field-meta.xml
<CustomField>
    <fullName>Phase__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Phase</label>
    <referenceTo>Phase__c</referenceTo>
    <relationshipLabel>Milestone</relationshipLabel>
    <relationshipName>Milestone</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

MODON MRE BPDEV/force-app/main/default/objects/Opportunity/fields/EIDNumber__c.field-meta.xml
<CustomField>
    <fullName>EIDNumber__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Please enter the value in the format of 784-xxxx-xxxxxxx-x</inlineHelpText>
    <label>Emirates ID Number</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

MODON MRE BPDEV/force-app/main/default/objects/Opportunity/fields/PrimaryContact__c.field-meta.xml
<CustomField>
    <fullName>PrimaryContact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities (Primary Contact)</relationshipLabel>
    <relationshipName>Opportunities1</relationshipName>
    <type>Lookup</type>
</CustomField>

MODON MRE BPDEV/force-app/main/default/objects/Opportunity/fields/UAE_Resident_Status__c.field-meta.xml
<CustomField>
    <fullName>UAE_Resident_Status__c</fullName>
    <label>UAE Resident Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Resident</fullName>
            </value>
            <value>
                <fullName>Non-Resident</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

MODON MRE BPDEV/force-app/main/default/objects/PersonAccount/recordTypes/PersonAccount.recordType-meta.xml
<RecordType>
    <fullName>PersonAccount</fullName>
    <active>true</active>
    <description>To capture Individual customer details.</description>
    <label>Person Account</label>
</RecordType>

MODON MRE BPDEV/force-app/main/default/objects/Phase__c/Phase__c.object-meta.xml
<CustomObject>
    <label>Phase</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Building/Section Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Phases</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

MODON MRE BPDEV/force-app/main/default/objects/Phase__c/fields/EscrowAccount__c.field-meta.xml
<CustomField>
    <fullName>EscrowAccount__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Escrow Account</label>
    <referenceTo>EscrowAccount__c</referenceTo>
    <relationshipLabel>Phases</relationshipLabel>
    <relationshipName>Phases</relationshipName>
    <type>Lookup</type>
</CustomField>

MODON MRE BPDEV/force-app/main/default/objects/SalesOrder__c/SalesOrder__c.object-meta.xml
<CustomObject>
    <label>Sales Order</label>
    <nameField>
        <displayFormat>SO-{00000}</displayFormat>
        <label>Sales Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

MODON MRE BPDEV/force-app/main/default/objects/SalesOrder__c/fields/CustomerAccount__c.field-meta.xml
<CustomField>
    <fullName>CustomerAccount__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Sales Orders</relationshipLabel>
    <relationshipName>Sales_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

MODON MRE BPDEV/force-app/main/default/objects/SalesOrder__c/fields/Nationality__c.field-meta.xml
<CustomField>
    <fullName>Nationality__c</fullName>
    <formula>TEXT(Opportunity__r.Nationality__c)</formula>
    <label>Nationality</label>
    <type>Text</type>
</CustomField>

MODON MRE BPDEV/force-app/main/default/objects/SalesOrder__c/fields/PrimaryContact__c.field-meta.xml
<CustomField>
    <fullName>PrimaryContact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Sales Orders</relationshipLabel>
    <relationshipName>Sales_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

MODON MRE BPDEV/force-app/main/default/objects/SalesOrder__c/fields/UAE_Resident_Status__c.field-meta.xml
<CustomField>
    <fullName>UAE_Resident_Status__c</fullName>
    <label>UAE Resident Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Resident</fullName>
            </value>
            <value>
                <fullName>Non-Resident</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

MODON MRE BPDEV/force-app/main/default/objects/SalesOrderInstallments__c/SalesOrderInstallments__c.object-meta.xml
<CustomObject>
    <label>Sales Order Installment</label>
    <nameField>
        <displayFormat>SOI-{00000}</displayFormat>
        <label>Sales Order Installment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SalesOrderInstallments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

MODON MRE BPDEV/force-app/main/default/objects/SalesOrderInstallments__c/fields/InstallmentAmount__c.field-meta.xml
<CustomField>
    <fullName>InstallmentAmount__c</fullName>
    <label>Installment Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

MODON MRE BPDEV/force-app/main/default/objects/SalesOrderInstallments__c/fields/Milestone__c.field-meta.xml
<CustomField>
    <fullName>Milestone__c</fullName>
    <label>Milestone %</label>
    <precision>4</precision>
    <scale>1</scale>
    <type>Percent</type>
</CustomField>

MODON MRE BPDEV/force-app/main/default/objects/SalesOrderInstallments__c/fields/MilestoneNumber__c.field-meta.xml
<CustomField>
    <fullName>MilestoneNumber__c</fullName>
    <label>Milestone Number</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

MODON MRE BPDEV/force-app/main/default/objects/SalesOrderInstallments__c/fields/SalesOrder__c.field-meta.xml
<CustomField>
    <fullName>SalesOrder__c</fullName>
    <label>Sales Order</label>
    <referenceTo>SalesOrder__c</referenceTo>
    <relationshipLabel>Sales Order Installments</relationshipLabel>
    <relationshipName>Sales_Order_Installments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

MODON MRE BPDEV/force-app/main/default/classes/PrintChequeControllerTest.cls
@isTest
private class PrintChequeControllerTest {
    // Mock class to simulate HTTP response
    private class MockHttpResponseGenerator implements HttpCalloutMock {
        public HTTPResponse respond(HTTPRequest req) {
            System.assertEquals('POST', req.getMethod(), 'The request should be POST');
            System.assertNotEquals(null, req.getBody(), 'Body should not be null');
            
            HttpResponse res = new HttpResponse();
            res.setStatusCode(200);
            res.setBody('{"status":"ok"}');
            return res;
        }
    }
    
    @isTest
    static void testPrintChequeStatus_Success() {
        // Create related records (EscrowAccount → Phase → ExpressionOfInterest → Receipt)
        Id personAccountRTID = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('PersonAccount').getRecordTypeId();

        Account testAccount = new Account();
        testAccount.FirstName = 'Test2123';
        testAccount.LastName = 'Account12312';
        testAccount.RecordTypeId = personAccountRTID;
        testAccount.PersonEmail = 'test@test221232.com';
        insert testAccount;

        Contact conObj = new Contact();
        conObj.LastName = 'Test contact12323';
        conObj.Email = 'test12321@test.com';
        conObj.Nationality__c = 'United Arab Emirates';
        conObj.UAE_Resident_Status__c = 'Resident';
        //conObj.AccountId = testAccount.Id;
        INSERT conObj;
        
        Opportunity oppObj = new Opportunity();
        oppObj.Name = 'Test opportunity12312';
        oppObj.StageName = 'Discussion In Progress';
        oppObj.CloseDate = System.Today();
        oppObj.PrimaryContact__c = conObj.Id;
        oppObj.Nationality__c = 'United Arab Emirates';
        oppObj.UAE_Resident_Status__c = 'Resident';
        oppObj.EmiratesIDExpiryDate__c = Date.valueOf('2030-02-02');
        oppObj.EIDNumber__c = '784-1985-0320123-0';
        insert oppObj;
        
        EscrowAccount__c escAccount = new EscrowAccount__c(name='Phase 1 Escrow Account');
        insert escAccount;
        phase__c phase = new phase__c(name='Test Phase',EscrowAccount__c =escAccount.id );
        insert phase;
        
		SalesOrder__c so = new SalesOrder__c();
        so.CustomerAccount__c = testAccount.Id;
        insert so;
        
        SalesOrderInstallments__c soi = new SalesOrderInstallments__c();
        soi.SalesOrder__c = so.Id;
        soi.Milestone__c = 1;
        soi.InstallmentAmount__c = 100;
        insert soi;
        SalesOrderInstallments__c soi1 = new SalesOrderInstallments__c(
            SalesOrder__c = so.id,
            MilestoneNumber__c = 2,
            InstallmentAmount__c = 5000
        );
        insert soi1;
        
        // Set mock for the callout
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());
        
        Test.startTest();
        String result = PrintChequeController.printChequeStatus(so.Id);
        Test.stopTest();
        
    }
    
    @isTest
    static void testPrintChequeStatus_Exception() {
        // Simulate invalid Id to trigger exception
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());
        
        Test.startTest();
        String result = PrintChequeController.printChequeStatus('InvalidId');
        Test.stopTest();       
       
    }
}