MODON MRE BPDEV/force-app/main/default/objects/OIC_Query_Parameters__mdt/OIC_Query_Parameters__mdt.object-meta.xml
<CustomObject>
    <label>OIC Query Parameters</label>
    <pluralLabel>OIC Query Parameters</pluralLabel>
</CustomObject>

MODON MRE BPDEV/force-app/main/default/objects/OIC_Query_Parameters__mdt/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <label>Value</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

MODON MRE BPDEV/force-app/main/default/classes/OIC_ManageSalesforceInvoiceDataSCH.cls
global class OIC_ManageSalesforceInvoiceDataSCH implements Schedulable{
    
    global void execute(SchedulableContext sc) 
    {        
        OIC_Query_Parameters__mdt oicParams = OIC_Query_Parameters__mdt.getInstance('BatchScope_SendInvoiceToOracle');
        String scopeStr = oicParams.Value__c;
        Database.executeBatch(new OIC_ManageSalesforceInvoiceDataBatch(), Integer.valueOf(scopeStr));
    }    
}