MODON MRE BPDEV/force-app/main/default/objects/Broker_Registration__c/Broker_Registration__c.object-meta.xml
<CustomObject>
    <label>Broker Registration</label>
    <nameField>
        <displayFormat>BR-{000000}</displayFormat>
        <label>Broker Registration Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Broker Registrations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

MODON MRE BPDEV/force-app/main/default/objects/Broker_Registration__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Email</label>
    <required>true</required>
    <type>Email</type>
</CustomField>

MODON MRE BPDEV/force-app/main/default/objects/Broker_Registration__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>First Name</label>
    <length>200</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

MODON MRE BPDEV/force-app/main/default/objects/Broker_Registration__c/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Last Name</label>
    <length>250</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

MODON MRE BPDEV/force-app/main/default/objects/Broker_Registration__c/fields/Mailing_Address_Line__c.field-meta.xml
<CustomField>
    <fullName>Mailing_Address_Line__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Mailing Address Line</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

MODON MRE BPDEV/force-app/main/default/objects/Broker_Registration__c/fields/Mailing_City__c.field-meta.xml
<CustomField>
    <fullName>Mailing_City__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Mailing City</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

MODON MRE BPDEV/force-app/main/default/objects/Broker_Registration__c/fields/Mailing_Country__c.field-meta.xml
<CustomField>
    <fullName>Mailing_Country__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Mailing Country</label>
    <length>15</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

MODON MRE BPDEV/force-app/main/default/objects/Broker_Registration__c/fields/Mailing_Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>Mailing_Postal_Code__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Mailing Postal Code</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

MODON MRE BPDEV/force-app/main/default/objects/Broker_Registration__c/fields/Mailing_State__c.field-meta.xml
<CustomField>
    <fullName>Mailing_State__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Mailing State</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

MODON MRE BPDEV/force-app/main/default/objects/Broker_Registration__c/fields/Middle_Name__c.field-meta.xml
<CustomField>
    <fullName>Middle_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Middle Name</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

MODON MRE BPDEV/force-app/main/default/objects/Broker_Registration__c/fields/Mobile__c.field-meta.xml
<CustomField>
    <fullName>Mobile__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Mobile</label>
    <required>true</required>
    <type>Phone</type>
</CustomField>

MODON MRE BPDEV/force-app/main/default/objects/Broker_Registration__c/fields/Supplier_Name__c.field-meta.xml
<CustomField>
    <fullName>Supplier_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Supplier Name</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

MODON MRE BPDEV/force-app/main/default/objects/Broker_Registration__c/fields/Supplier_Number__c.field-meta.xml
<CustomField>
    <fullName>Supplier_Number__c</fullName>
    <label>Supplier Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

MODON MRE BPDEV/force-app/main/default/objects/Broker_Registration__c/fields/Unified_Number__c.field-meta.xml
<CustomField>
    <fullName>Unified_Number__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Unified Number</label>
    <length>200</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

MODON MRE BPDEV/force-app/main/default/classes/BrokerRegistrationTriggerHelperTest.cls
@isTest
private class BrokerRegistrationTriggerHelperTest {

    @isTest
    static void testBrokerRegistrationFromSamaaro() {
        Broker_Registration__c broker = new Broker_Registration__c(
            Supplier_Name__c = 'Test Supplier23',
            Email__c = 'test2323broker@example.com',
            First_Name__c = 'John122',
            Last_Name__c = 'Doe12',
            Middle_Name__c = 'M',
            Unified_Number__c = '12123456789',
            Supplier_Number__c = 1231,
            Mailing_Address_Line__c = '123 Main St',
            Mailing_City__c = 'Dubai',
            Mailing_State__c = 'Dubai',
            Mailing_Postal_Code__c = '00000',
            Mailing_Country__c = 'UAE',
            Mobile__c = '05012234567'
        );
        insert broker;

        Test.startTest();
        BrokerRegistrationTriggerHelper.brokerRegistrationFromSamaaro(new List<sObject>{ broker });
        BrokerRegistrationTriggerHelper.incrementDifferenceExample();
        Test.stopTest();
    }
}