MODON MRE BPDEV/force-app/main/default/objects/Phase__c/Phase__c.object-meta.xml
<CustomObject>
    <label>Phase</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Building/Section Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Phases</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

MODON MRE BPDEV/force-app/main/default/objects/Phase__c/fields/EntityName__c.field-meta.xml
<CustomField>
    <fullName>EntityName__c</fullName>
    <label>EntityName</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Hudayriyat Development - L.L.C- O.P.C</fullName>
            </value>
            <value>
                <fullName>Reem Developers -Sole Proprietorship L.L.C</fullName>
            </value>
            <value>
                <fullName>AL TAMOUH INVESTMENTS COMPANY L.L.C.</fullName>
            </value>
            <value>
                <fullName>Modon Properties PJSC</fullName>
            </value>
            <value>
                <fullName>Modon Real Estate Development Limited</fullName>
            </value>
            <value>
                <fullName>REEM HILLS - SOLE PROPRIETORSHIP L.L.C</fullName>
            </value>
            <value>
                <fullName>AL TAMOUH INVESTMENTS COMPANY L.L.C</fullName>
                <isActive>false</isActive>
                <label>AL TAMOUH INVESTMENTS COMPANY L.L.C</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

MODON MRE BPDEV/force-app/main/default/objects/Phase__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipName>BuildingsSections</relationshipName>
    <type>Lookup</type>
</CustomField>

MODON MRE BPDEV/force-app/main/default/objects/Phase__c/fields/Source_Entity__c.field-meta.xml
<CustomField>
    <fullName>Source_Entity__c</fullName>
    <formula>TEXT( Project__r.Source_Entity__c )</formula>
    <label>Source Entity</label>
    <type>Text</type>
</CustomField>

MODON MRE BPDEV/force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <description>This custom object is part of inventory management to store the project details</description>
    <label>Project</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

MODON MRE BPDEV/force-app/main/default/objects/Project__c/fields/Source_Entity__c.field-meta.xml
<CustomField>
    <fullName>Source_Entity__c</fullName>
    <label>Source Entity</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Source_Entity</valueSetName>
    </valueSet>
</CustomField>

MODON MRE BPDEV/force-app/main/default/globalValueSets/Source_Entity.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Modon - Egypt</fullName>
    </customValue>
    <customValue>
        <fullName>Modon - UAE</fullName>
    </customValue>
    <masterLabel>Source Entity</masterLabel>
</GlobalValueSet>

MODON MRE BPDEV/force-app/main/default/classes/ProjectPhasePicklistController.cls
/**********************************************************************************************************************
 * Name               : ProjectPhasePicklistController
 * Description        : This class is Receipt flow selection in project and phase  
 * Usage              : Called from ProjectPhasePicklistController
 * Created By         : Active minds
 * --------------------------------------------------------------------------------------------------------------------
 * Version       Author                              Date            Comment
 * 1.0           kumaravel.mathivanan         		21 Dec 2025     Initial Draft 
 * 2.0           Manoj                              27 Jan 2026     Add the logic for the projects filter and paramater 
 ******************************************************************************************************************/
public class ProjectPhasePicklistController {

    @AuraEnabled(cacheable=true)
    public static List<Project__c> getProjects(string EntityName) { // 2.0 
        Map<id,Project__c> projectMap = new Map<id,Project__c>();
        //2.0 Started 
        list<Phase__c> phaseProjectlist = [select id,Name,EntityName__c, Project__c, Project__r.name from Phase__c where EntityName__c =: EntityName and Project__r.name not IN ('Ras El Hekma','Ras El Hekma, Egypt','Ras El Hekma, Egypt(Egypt Only)','Thahr El Bateen','') and Source_Entity__c != 'Modon - Egypt' ORDER BY Name];
        for(Phase__c ph : phaseProjectlist){
                if(!projectMap.containsKey(ph.Project__c)){
                    Project__c pr = new Project__c();
                    pr.name = ph.Project__r.name;
                    pr.id = ph.Project__c;
                    projectMap.put(ph.Project__c,pr); 
                    system.debug('projectMap22---'+projectMap);   
                }else {

                    projectMap.get(ph.Project__c).name = ph.Project__r.name;
                    projectMap.get(ph.Project__c).id = ph.Project__c;
                    system.debug('projectMap27---'+projectMap);
                }
        }
        return projectMap.values(); // End
    }

    @AuraEnabled(cacheable=true)
    public static List<Phase__c> getPhases(Id projectId) {
        return [
            SELECT Id, Name
            FROM Phase__c
            WHERE Project__c = :projectId
            ORDER BY Name
        ];
    }
}