MODON MRE BPDEV/force-app/main/default/objects/Business_Process__c/Business_Process__c.object-meta.xml
<CustomObject>
    <label>Business Process</label>
    <nameField>
        <displayFormat>BP-{0000000}</displayFormat>
        <label>Business Process Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Business Processes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

MODON MRE BPDEV/force-app/main/default/objects/Business_Process__c/fields/Process_Flow__c.field-meta.xml
<CustomField>
    <fullName>Process_Flow__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Process Flow</label>
    <referenceTo>Process_Flow__c</referenceTo>
    <relationshipLabel>Business Processes</relationshipLabel>
    <relationshipName>Business_Processes</relationshipName>
    <type>Lookup</type>
</CustomField>

MODON MRE BPDEV/force-app/main/default/objects/Business_Process__c/fields/Sales_Order__c.field-meta.xml
<CustomField>
    <fullName>Sales_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Order</label>
    <referenceTo>SalesOrder__c</referenceTo>
    <relationshipLabel>Business Processes</relationshipLabel>
    <relationshipName>Business_Processes</relationshipName>
    <type>Lookup</type>
</CustomField>

MODON MRE BPDEV/force-app/main/default/objects/Business_Process__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

MODON MRE BPDEV/force-app/main/default/objects/Business_Process__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Type</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

MODON MRE BPDEV/force-app/main/default/objects/Process_Flow__c/Process_Flow__c.object-meta.xml
<CustomObject>
    <label>Process Flow</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Process Flow Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Process Flow</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

MODON MRE BPDEV/force-app/main/default/objects/Process_Flow__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cost Approval</fullName>
            </value>
            <value>
                <fullName>Office Branding</fullName>
            </value>
            <value>
                <fullName>Mall Stand</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

MODON MRE BPDEV/force-app/main/default/objects/SalesOrder__c/SalesOrder__c.object-meta.xml
<CustomObject>
    <label>Sales Order</label>
    <nameField>
        <displayFormat>SO-{00000}</displayFormat>
        <label>Sales Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

MODON MRE BPDEV/force-app/main/default/objects/SalesOrder__c/fields/CustomerAccount__c.field-meta.xml
<CustomField>
    <fullName>CustomerAccount__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Sales Orders</relationshipLabel>
    <relationshipName>Sales_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

MODON MRE BPDEV/force-app/main/default/objects/SalesOrder__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Reservation form generated</fullName>
            </value>
            <value>
                <fullName>Down payment collected</fullName>
            </value>
            <value>
                <fullName>Reservation form signed</fullName>
            </value>
            <value>
                <fullName>Installment Payment Collected</fullName>
            </value>
            <value>
                <fullName>DP Payment Confirmed</fullName>
            </value>
            <value>
                <fullName>SPA Generated</fullName>
            </value>
            <value>
                <fullName>SPA Signed (Customer)</fullName>
            </value>
            <value>
                <fullName>SPA Signed (Modon)</fullName>
            </value>
            <value>
                <fullName>SPA Delivered</fullName>
            </value>
            <value>
                <fullName>Sold</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>System cancelled</fullName>
            </value>
            <value>
                <fullName>KYC - In progress</fullName>
            </value>
            <value>
                <fullName>KYC - Completed / KYC Rejected</fullName>
            </value>
            <value>
                <fullName>Payments Collected</fullName>
            </value>
            <value>
                <fullName>Downpayment Payments Cleared</fullName>
            </value>
            <value>
                <fullName>SPA Sent to customer</fullName>
            </value>
            <value>
                <fullName>SPA Validated</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Cancelled SR</fullName>
            </value>
            <value>
                <fullName>Voided</fullName>
            </value>
            <value>
                <fullName>Pending Blocking Fees</fullName>
            </value>
            <value>
                <fullName>Blocking Fees Collected</fullName>
            </value>
            <value>
                <fullName>Property Transfer Cancelled - SR</fullName>
            </value>
            <value>
                <fullName>Unit Swap Cancelled - SR</fullName>
            </value>
            <value>
                <fullName>Unit Upgrade Cancelled - SR</fullName>
            </value>
            <value>
                <fullName>Unit Cancellation Cancelled - SR</fullName>
            </value>
            <value>
                <fullName>Unit Consolidation Cancelled - SR</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

MODON MRE BPDEV/force-app/main/default/classes/EmployeePaymentPlanChangeController.cls
public without sharing class EmployeePaymentPlanChangeController {
    
	@AuraEnabled
public static Boolean checkEmployeePaymentPlanProcess(
    Id salesOrderId
) {

    if (salesOrderId == null) {
        throw new AuraHandledException(
            'Sales Order Id is required.'
        );
    }

    List<Business_Process__c> processes = [
        SELECT Id
        FROM Business_Process__c
        WHERE Sales_Order__c = :salesOrderId
        AND Type__c = 'Employee Payment Plan'
        AND Status__c != 'Cancelled'
        LIMIT 1
    ];

	List<SalesOrder__c> salesOrder=[Select Id,CustomerAccount__r.Is_Employee_Payment_Plan_Applied__c from SalesOrder__c where Id=:salesOrderId];

    return !processes.isEmpty() || salesOrder[0].CustomerAccount__r.Is_Employee_Payment_Plan_Applied__c ;
}


@AuraEnabled
public static Id createEmployeePaymentPlanProcess(
    Id salesOrderId
) {

    if (salesOrderId == null) {
        throw new AuraHandledException(
            'Sales Order Id is required.'
        );
    }

    List<Business_Process__c> existingProcesses = [
        SELECT Id
        FROM Business_Process__c
        WHERE Sales_Order__c = :salesOrderId
        AND Type__c = 'Employee Payment Plan'
        AND Status__c = 'In Progress'
        LIMIT 1
    ];

    if (!existingProcesses.isEmpty()) {

        throw new AuraHandledException(
            'An Employee Payment Plan Change is already in progress for this Sales Order.'
        );
    }

    Process_Flow__c processFlow = [
        SELECT Id
        FROM Process_Flow__c
        WHERE Name = 'Employee Payment Plan'
        LIMIT 1
    ];

    Id businessProcessId =
        CreateBusinessProcess.createPreRegistration(
            salesOrderId,
            processFlow.Id
        );

    return businessProcessId;
}

}