MODON MRE BPDEV/force-app/main/default/objects/Business_Process__c/Business_Process__c.object-meta.xml
<CustomObject>
    <label>Business Process</label>
    <nameField>
        <displayFormat>BP-{0000000}</displayFormat>
        <label>Business Process Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Business Processes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

MODON MRE BPDEV/force-app/main/default/objects/Business_Process__c/fields/Process_Flow__c.field-meta.xml
<CustomField>
    <fullName>Process_Flow__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Process Flow</label>
    <referenceTo>Process_Flow__c</referenceTo>
    <relationshipLabel>Business Processes</relationshipLabel>
    <relationshipName>Business_Processes</relationshipName>
    <type>Lookup</type>
</CustomField>

MODON MRE BPDEV/force-app/main/default/objects/Business_Process__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

MODON MRE BPDEV/force-app/main/default/objects/Business_Process__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Type</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

MODON MRE BPDEV/force-app/main/default/objects/Business_Process_Documents__c/Business_Process_Documents__c.object-meta.xml
<CustomObject>
    <label>Business Process Documents</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Business Process Documents Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Process Documents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

MODON MRE BPDEV/force-app/main/default/objects/Business_Process_Documents__c/fields/Business_Process__c.field-meta.xml
<CustomField>
    <fullName>Business_Process__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Business Process</label>
    <referenceTo>Business_Process__c</referenceTo>
    <relationshipLabel>Business Process Documents</relationshipLabel>
    <relationshipName>Business_Process_Documents</relationshipName>
    <type>Lookup</type>
</CustomField>

MODON MRE BPDEV/force-app/main/default/objects/Business_Process_Documents__c/fields/Business_Process_Step__c.field-meta.xml
<CustomField>
    <fullName>Business_Process_Step__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Business Process Step</label>
    <referenceTo>Business_Process_Step__c</referenceTo>
    <relationshipLabel>Business Process Documents</relationshipLabel>
    <relationshipName>Business_Process_Documents</relationshipName>
    <type>Lookup</type>
</CustomField>

MODON MRE BPDEV/force-app/main/default/objects/Business_Process_Documents__c/fields/Process_Flow_Document__c.field-meta.xml
<CustomField>
    <fullName>Process_Flow_Document__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Process Flow Document</label>
    <referenceTo>Process_Flow_Document__c</referenceTo>
    <relationshipLabel>Business Process Documents</relationshipLabel>
    <relationshipName>Business_Process_Documents</relationshipName>
    <type>Lookup</type>
</CustomField>

MODON MRE BPDEV/force-app/main/default/objects/Business_Process_Step__c/Business_Process_Step__c.object-meta.xml
<CustomObject>
    <label>Business Process Step</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Business Process Steps Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Process Steps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

MODON MRE BPDEV/force-app/main/default/objects/Business_Process_Step__c/fields/Business_Process__c.field-meta.xml
<CustomField>
    <fullName>Business_Process__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Business Process</label>
    <referenceTo>Business_Process__c</referenceTo>
    <relationshipLabel>Business Process Steps</relationshipLabel>
    <relationshipName>Business_Process_Steps</relationshipName>
    <type>Lookup</type>
</CustomField>

MODON MRE BPDEV/force-app/main/default/objects/Business_Process_Step__c/fields/Business_Process_Steps_Name_Custom__c.field-meta.xml
<CustomField>
    <fullName>Business_Process_Steps_Name_Custom__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Business Process Step Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

MODON MRE BPDEV/force-app/main/default/objects/Business_Process_Step__c/fields/Process_Flow_Step__c.field-meta.xml
<CustomField>
    <fullName>Process_Flow_Step__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Process Flow Step</label>
    <referenceTo>Process_Flow_Step__c</referenceTo>
    <relationshipLabel>Business Process Steps</relationshipLabel>
    <relationshipName>Business_Process_Steps</relationshipName>
    <type>Lookup</type>
</CustomField>

MODON MRE BPDEV/force-app/main/default/objects/Business_Process_Step__c/fields/Section_Number__c.field-meta.xml
<CustomField>
    <fullName>Section_Number__c</fullName>
    <label>Section Number</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

MODON MRE BPDEV/force-app/main/default/objects/Business_Process_Step__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Not Actioned</fullName>
                <default>true</default>
                <label>Not Actioned</label>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Required Info</fullName>
            </value>
            <value>
                <fullName>Provided Info</fullName>
            </value>
            <value>
                <fullName>Re Open</fullName>
            </value>
            <value>
                <fullName>Skipped</fullName>
            </value>
            <value>
                <fullName>Submitted to Audit</fullName>
            </value>
            <value>
                <fullName>Submit to Next Department</fullName>
            </value>
            <value>
                <fullName>Assigned</fullName>
            </value>
            <value>
                <fullName>Re Assigned</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

MODON MRE BPDEV/force-app/main/default/objects/Mandatory_Document__c/Mandatory_Document__c.object-meta.xml
<CustomObject>
    <label>Mandatory Document</label>
    <nameField>
        <displayFormat>MD-{0000}</displayFormat>
        <label>Mandatory Document Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Mandatory Documents</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

MODON MRE BPDEV/force-app/main/default/objects/Mandatory_Document__c/fields/Process_Flow_Document__c.field-meta.xml
<CustomField>
    <fullName>Process_Flow_Document__c</fullName>
    <label>Process Flow Document</label>
    <referenceTo>Process_Flow_Document__c</referenceTo>
    <relationshipLabel>Mandatory Documents</relationshipLabel>
    <relationshipName>Mandatory_Documents</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

MODON MRE BPDEV/force-app/main/default/objects/Mandatory_Document__c/fields/Process_Flow_Step__c.field-meta.xml
<CustomField>
    <fullName>Process_Flow_Step__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Process Flow Step</label>
    <referenceTo>Process_Flow_Step__c</referenceTo>
    <relationshipLabel>Mandatory Documents</relationshipLabel>
    <relationshipName>Mandatory_Documents</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

MODON MRE BPDEV/force-app/main/default/objects/Mandatory_Document__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

MODON MRE BPDEV/force-app/main/default/objects/Process_Flow__c/Process_Flow__c.object-meta.xml
<CustomObject>
    <label>Process Flow</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Process Flow Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Process Flow</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

MODON MRE BPDEV/force-app/main/default/objects/Process_Flow__c/fields/Process_Flow_Unique_Name__c.field-meta.xml
<CustomField>
    <fullName>Process_Flow_Unique_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Process Flow Unique Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

MODON MRE BPDEV/force-app/main/default/objects/Process_Flow__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cost Approval</fullName>
            </value>
            <value>
                <fullName>Office Branding</fullName>
            </value>
            <value>
                <fullName>Mall Stand</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

MODON MRE BPDEV/force-app/main/default/objects/Process_Flow_Document__c/Process_Flow_Document__c.object-meta.xml
<CustomObject>
    <label>Process Flow Document</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Process Flow Document Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ProcessFlowDocuments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

MODON MRE BPDEV/force-app/main/default/objects/Process_Flow_Document__c/fields/Document_Description__c.field-meta.xml
<CustomField>
    <fullName>Document_Description__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Document Description</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

MODON MRE BPDEV/force-app/main/default/objects/Process_Flow_Document__c/fields/isAutoGen__c.field-meta.xml
<CustomField>
    <fullName>isAutoGen__c</fullName>
    <defaultValue>false</defaultValue>
    <label>isAutoGen</label>
    <type>Checkbox</type>
</CustomField>

MODON MRE BPDEV/force-app/main/default/objects/Process_Flow_Document__c/fields/Process_Flow__c.field-meta.xml
<CustomField>
    <fullName>Process_Flow__c</fullName>
    <label>Process Flow</label>
    <referenceTo>Process_Flow__c</referenceTo>
    <relationshipLabel>ProcessFlowDocuments</relationshipLabel>
    <relationshipName>ProcessFlowDocuments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

MODON MRE BPDEV/force-app/main/default/objects/Process_Flow_Document__c/fields/Process_Flow_Step__c.field-meta.xml
<CustomField>
    <fullName>Process_Flow_Step__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Process Flow Step</label>
    <referenceTo>Process_Flow_Step__c</referenceTo>
    <relationshipLabel>ProcessFlowDocuments</relationshipLabel>
    <relationshipName>ProcessFlowDocuments</relationshipName>
    <type>Lookup</type>
</CustomField>

MODON MRE BPDEV/force-app/main/default/objects/Process_Flow_Step__c/Process_Flow_Step__c.object-meta.xml
<CustomObject>
    <label>Process Flow Step</label>
    <nameField>
        <displayFormat>PFS-{0000}</displayFormat>
        <label>Process Flow Step Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Process Flow Steps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

MODON MRE BPDEV/force-app/main/default/objects/Process_Flow_Step__c/fields/Process_Flow__c.field-meta.xml
<CustomField>
    <fullName>Process_Flow__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Process Flow</label>
    <referenceTo>Process_Flow__c</referenceTo>
    <relationshipLabel>Process Flow Steps</relationshipLabel>
    <relationshipName>Process_Flow_Steps</relationshipName>
    <type>Lookup</type>
</CustomField>

MODON MRE BPDEV/force-app/main/default/objects/Process_Flow_Step__c/fields/section_Name__c.field-meta.xml
<CustomField>
    <fullName>section_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>section Name</label>
    <length>250</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

MODON MRE BPDEV/force-app/main/default/classes/fileUploadCompControllerTest.cls
@isTest
public class fileUploadCompControllerTest {

    @testSetup
    static void setupData() {
        
         Profile p = [SELECT Id FROM Profile WHERE Name = 'Standard User' LIMIT 1];
        User u = new User(
            Alias = 'testusr',
            Email = 'testuser@test.com',
            EmailEncodingKey = 'UTF-8',
            LastName = 'User',
            LanguageLocaleKey = 'en_US',
            LocaleSidKey = 'en_US',
            ProfileId = p.Id,
            TimeZoneSidKey = 'Asia/Kolkata',
            UserName = 'testuser' + System.currentTimeMillis() + '@test.com'
        );
        insert u;

        Process_Flow__c testProcessFlow = new Process_Flow__c(
            Name = 'BR Amendment',
            Active__c = true,
            Process_Flow_Unique_Name__c = 'test',
            Type__c='Cost Approval'
        );
        insert testProcessFlow;

        Process_Flow_Step__c pfs1 = new Process_Flow_Step__c(
            Section_Number__c=1,
            section_Name__c='TES1',
            Process_Flow__c = testProcessFlow.Id
        );
        insert pfs1;

        Process_Flow_Step__c pfs2 = new Process_Flow_Step__c(
            Section_Number__c=2,
            section_Name__c='TES2',
            Process_Flow__c = testProcessFlow.Id
        );
        insert pfs2;

        Business_Process__c bp = new Business_Process__c(
            Process_Flow__c =testProcessFlow.Id
        );
        insert bp;

        List<Business_Process_Step__c> steps = new List<Business_Process_Step__c>();

        steps.add(new Business_Process_Step__c(
            Name = 'Step 1',
            Business_Process__c = bp.Id,
            Process_Flow_Step__c = pfs1.Id, 
            Sequence__c = 1,
            Status__c = 'Not Actioned',
            OwnerId = u.Id,
            Business_Process_Steps_Name_Custom__c='test1',
            Section_Number__c=1,
            section_Name__c='test1'
        ));

        steps.add(new Business_Process_Step__c(
            Name = 'Step 2',
            Business_Process__c = bp.Id,
            Process_Flow_Step__c = pfs2.Id, 
            Sequence__c = 2,
            Status__c = 'Not Actioned',
            OwnerId = u.Id,
            Business_Process_Steps_Name_Custom__c='test2',
            Section_Number__c=2,
            section_Name__c='test2'
        ));
        insert steps;

        // Process Flow Document
        Process_Flow_Document__c doc = new Process_Flow_Document__c(
            Name = 'Doc A',
            sequence__c = 1,
            Document_Description__c = 'Test Description',
            isAutoGen__c = false,
            Process_Flow__c=testProcessFlow.Id
        );
        insert doc;

        // Business Process Document
        Business_Process_Documents__c bpd = new Business_Process_Documents__c(
            Name = 'BP Doc',
            Business_Process__c = bp.Id,
            Business_Process_Step__c = steps[0].Id,
            Process_Flow_Document__c = doc.Id
        );
        insert bpd;

        // Mandatory Document (makes it required)
        Mandatory_Document__c md = new Mandatory_Document__c(
            Process_Flow_Step__c = pfs1.Id,
            Process_Flow_Document__c = doc.Id
        );
        insert md;

        // Create a File (ContentVersion)
        ContentVersion cv = new ContentVersion(
            Title = 'Test File',
            PathOnClient = 'TestFile.pdf',
            VersionData = Blob.valueOf('Test Content')
        );
        insert cv;

        // Query ContentDocumentId
        cv = [
            SELECT ContentDocumentId
            FROM ContentVersion
            WHERE Id = :cv.Id
        ];

        // Link file to Business Process Document
        ContentDocumentLink cdl = new ContentDocumentLink(
            ContentDocumentId = cv.ContentDocumentId,
            LinkedEntityId = bpd.Id,
            ShareType = 'V'
        );
        insert cdl;
    }

    @isTest
    static void testGetDocumentsWithFiles() {

        Business_Process__c bp = [SELECT Id FROM Business_Process__c LIMIT 1];

        Test.startTest();
        List<fileUploadCompController.DocumentWrapper> result =
            fileUploadCompController.getDocumentsWithFiles(bp.Id);
        Test.stopTest();

    }

    @isTest
    static void testNoDocuments() {

        Test.startTest();
        List<fileUploadCompController.DocumentWrapper> result =
            fileUploadCompController.getDocumentsWithFiles(null);
        Test.stopTest();

        System.assertEquals(0, result.size());
    }
}