MODON MRE BPDEV/force-app/main/default/objects/Lead/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <formula>LEFT(Email, 2) &amp;&quot;*********&quot; &amp; RIGHT(Email, 3)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Email</label>
    <type>Text</type>
</CustomField>

MODON MRE BPDEV/force-app/main/default/objects/Lead/fields/Lead_Event__c.field-meta.xml
<CustomField>
    <fullName>Lead_Event__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead Event</label>
    <referenceTo>Lead_Event__c</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

MODON MRE BPDEV/force-app/main/default/objects/Lead/fields/TradeName__c.field-meta.xml
<CustomField>
    <fullName>TradeName__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Trade Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

MODON MRE BPDEV/force-app/main/default/objects/Lead_Event__c/Lead_Event__c.object-meta.xml
<CustomObject>
    <label>Lead Event</label>
    <nameField>
        <displayFormat>LE-{0000}</displayFormat>
        <label>Lead Event Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lead Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

MODON MRE BPDEV/force-app/main/default/objects/Lead_Event__c/fields/ADDED_BY__c.field-meta.xml
<CustomField>
    <fullName>ADDED_BY__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>ADDED_BY</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

MODON MRE BPDEV/force-app/main/default/objects/Lead_Event__c/fields/Broker_Email__c.field-meta.xml
<CustomField>
    <fullName>Broker_Email__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Broker Email</label>
    <type>Email</type>
</CustomField>

MODON MRE BPDEV/force-app/main/default/objects/Lead_Event__c/fields/Broker_Name__c.field-meta.xml
<CustomField>
    <fullName>Broker_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Broker Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

MODON MRE BPDEV/force-app/main/default/objects/Lead_Event__c/fields/Broker_Phone__c.field-meta.xml
<CustomField>
    <fullName>Broker_Phone__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Broker Phone</label>
    <type>Phone</type>
</CustomField>

MODON MRE BPDEV/force-app/main/default/objects/Lead_Event__c/fields/Broker_UnifiedNumber__c.field-meta.xml
<CustomField>
    <fullName>Broker_UnifiedNumber__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Broker UnifiedNumber</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

MODON MRE BPDEV/force-app/main/default/objects/Lead_Event__c/fields/CampaignId__c.field-meta.xml
<CustomField>
    <fullName>CampaignId__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>CampaignId</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

MODON MRE BPDEV/force-app/main/default/objects/Lead_Event__c/fields/Checkin_Status__c.field-meta.xml
<CustomField>
    <fullName>Checkin_Status__c</fullName>
    <label>Checkin Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>YES</fullName>
            </value>
            <value>
                <fullName>NO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

MODON MRE BPDEV/force-app/main/default/objects/Lead_Event__c/fields/Checkin_Time__c.field-meta.xml
<CustomField>
    <fullName>Checkin_Time__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Checkin Time</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

MODON MRE BPDEV/force-app/main/default/objects/Lead_Event__c/fields/EventID__c.field-meta.xml
<CustomField>
    <fullName>EventID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>EventID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

MODON MRE BPDEV/force-app/main/default/objects/Lead_Event__c/fields/EventName__c.field-meta.xml
<CustomField>
    <fullName>EventName__c</fullName>
    <defaultValue>&quot;Wadeem Sales Launch&quot;</defaultValue>
    <encryptionScheme>None</encryptionScheme>
    <label>EventName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

MODON MRE BPDEV/force-app/main/default/objects/Lead_Event__c/fields/FirstName__c.field-meta.xml
<CustomField>
    <fullName>FirstName__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>First Name</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

MODON MRE BPDEV/force-app/main/default/objects/Lead_Event__c/fields/LastName__c.field-meta.xml
<CustomField>
    <fullName>LastName__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Last Name</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

MODON MRE BPDEV/force-app/main/default/objects/Lead_Event__c/fields/Lead_Source__c.field-meta.xml
<CustomField>
    <fullName>Lead_Source__c</fullName>
    <defaultValue>&quot;VIP Event_Emirates Palace&quot;</defaultValue>
    <encryptionScheme>None</encryptionScheme>
    <label>Lead Source</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

MODON MRE BPDEV/force-app/main/default/objects/Lead_Event__c/fields/LeadID__c.field-meta.xml
<CustomField>
    <fullName>LeadID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>LeadID</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Lead Events</relationshipLabel>
    <relationshipName>Lead_Events</relationshipName>
    <type>Lookup</type>
</CustomField>

MODON MRE BPDEV/force-app/main/default/objects/Lead_Event__c/fields/SalesAgentName__c.field-meta.xml
<CustomField>
    <fullName>SalesAgentName__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>SalesAgentName</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

MODON MRE BPDEV/force-app/main/default/classes/LeadEventTriggerHandlerTest.cls
@isTest
public class LeadEventTriggerHandlerTest {
    
    @isTest
    static void testAfterInsert() {
        Lead obj_Lead = new Lead(FirstName = 'John', LastName = 'Doe', Company = 'ABC Inc.',TradeName__c ='Test', UnifiedNumber__c='Test');
        Id profId = [SELECT Id FROM PRofile WHERE Name = 'Sales Management' LIMIT 1].Id;
        
        User user = new User();
        user.Username = 'abdallahtest_test@test.com';
        user.LastName = 'Test';
        user.FirstName = 'Sales';
        user.Email = 'test@test.com';
        user.Alias = 'test';
        user.TimeZoneSidKey = 'Pacific/Apia';
        user.LocaleSidKey = 'af_ZA';
        user.EmailEncodingKey = 'x-SJIS_0213';
        user.ProfileId = profId;
        user.LanguageLocaleKey = 'en_US';
        user.IsActive = true;
        
        Test.startTest(); 
        insert obj_Lead;
        insert user;
        List<Lead_Event__c> leadevents = new List<Lead_Event__c>{
            new Lead_Event__c(ADDED_BY__c = 'Test', Broker_Email__c = 'Test@admin.com', 
                              Broker_Name__c = 'Test',Broker_Phone__c ='+97156602342', Broker_UnifiedNumber__c='CN-5026332', 
                              CampaignId__c='Test', Checkin_Status__c = 'NO', Checkin_Time__c = '2025-02-22T10:09:58Z', 
                              Email__c='test@admin.com', EventID__c='67b6c6ab3153a5a856f3b417', 
                              EventName__c='Final Demo Event', FirstName__c='Test', LastName__c='Test2', LeadID__c=obj_Lead.Id, 
                              Lead_Source__c='Walk-In', SalesAgentName__c = 'Sales Test')
            // Add more test lead records as needed
        };
       insert leadevents;    
       Test.stopTest();     
    }

    @isTest
    static void testAfterUpdate() {
        Lead obj_Lead = new Lead(FirstName = 'John', LastName = 'Doe', Company = 'ABC Inc.',TradeName__c ='Test', UnifiedNumber__c='Test');
        Id profId = [SELECT Id FROM PRofile WHERE Name = 'Sales Management' LIMIT 1].Id;
        
        User user = new User();
        user.Username = 'abdallahtest_test@test.com';
        user.LastName = 'Test';
        user.FirstName = 'Sales';
        user.Email = 'test@test.com';
        user.Alias = 'test';
        user.TimeZoneSidKey = 'Pacific/Apia';
        user.LocaleSidKey = 'af_ZA';
        user.EmailEncodingKey = 'x-SJIS_0213';
        user.ProfileId = profId;
        user.LanguageLocaleKey = 'en_US';
        user.IsActive = true;
        
        User user2 = new User();
        user2.Username = 'abdallahtest_test22@test.com';
        user2.LastName = 'Test22';
        user2.FirstName = 'Sales';
        user2.Email = 'test@test.com';
        user2.Alias = 'test';
        user2.TimeZoneSidKey = 'Pacific/Apia';
        user2.LocaleSidKey = 'af_ZA';
        user2.EmailEncodingKey = 'x-SJIS_0213';
        user2.ProfileId = profId;
        user2.LanguageLocaleKey = 'en_US';
        user2.IsActive = true;
        
        Test.startTest(); 
        insert obj_Lead;
        insert user;
        insert user2;
        
        Lead_Event__c obj_LeadEvent = new Lead_Event__c(ADDED_BY__c = 'Test', Broker_Email__c = 'Test@admin.com', 
                              							Broker_Name__c = 'Test',Broker_Phone__c ='+97156602342', Broker_UnifiedNumber__c='CN-5026332', 
                              							CampaignId__c='Test', Checkin_Status__c = 'NO', Checkin_Time__c = '2025-02-22T10:09:58Z', 
                              							Email__c='test@admin.com', EventID__c='67b6c6ab3153a5a856f3b417', 
                              							EventName__c='Final Demo Event', FirstName__c='Test', LastName__c='Test2', LeadID__c=obj_Lead.Id, 
                              							Lead_Source__c='BrokerPortal', SalesAgentName__c = 'Sales Test');
         
       insert obj_LeadEvent; 
       //obj_LeadEvent.SalesAgentName__c = 'Sales Test22'; 
       //update obj_LeadEvent; 
       Test.stopTest();
    }    

}