MODON MRE BPDEV/force-app/main/default/objects/OffersPromotions__c/OffersPromotions__c.object-meta.xml
<CustomObject>
    <description>Object to manage all the Offers &amp; Promotions associated with a Project and/or that can be used for a booking.</description>
    <label>Offer &amp; Promotion</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Offer Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Offers &amp; Promotions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

MODON MRE BPDEV/force-app/main/default/objects/OffersPromotions__c/fields/Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Approval_Status__c</fullName>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Submitted</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
                <default>true</default>
                <label>Approved</label>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

MODON MRE BPDEV/force-app/main/default/objects/OffersPromotions__c/fields/EndDate__c.field-meta.xml
<CustomField>
    <fullName>EndDate__c</fullName>
    <description>Duration till when the offer has to be active.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Duration till when the offer has to be active.</inlineHelpText>
    <label>End Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

MODON MRE BPDEV/force-app/main/default/objects/OffersPromotions__c/fields/OfferName__c.field-meta.xml
<CustomField>
    <fullName>OfferName__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Offer Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

MODON MRE BPDEV/force-app/main/default/objects/OffersPromotions__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Project for which the promotion is applied. All the offers have to be associated with a project.</description>
    <inlineHelpText>Project for which the promotion is applied. All the offers have to be associated with a project.</inlineHelpText>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Offers &amp; Promotions</relationshipLabel>
    <relationshipName>OffersPromotionsProject</relationshipName>
    <type>Lookup</type>
</CustomField>

MODON MRE BPDEV/force-app/main/default/objects/OffersPromotions__c/fields/SalesEventCampaignName__c.field-meta.xml
<CustomField>
    <fullName>SalesEventCampaignName__c</fullName>
    <description>Sales Event/Campaign Name used in Marketing communication.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Sales Event/Campaign Name used in Marketing communication.</inlineHelpText>
    <label>Sales Event/Campaign Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

MODON MRE BPDEV/force-app/main/default/objects/OffersPromotions__c/fields/StartDate__c.field-meta.xml
<CustomField>
    <fullName>StartDate__c</fullName>
    <description>Duration from when the offer has to be active.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Duration from when the offer has to be active.</inlineHelpText>
    <label>Start Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

MODON MRE BPDEV/force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <description>This custom object is part of inventory management to store the project details</description>
    <label>Project</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

MODON MRE BPDEV/force-app/main/default/classes/OffersPromotionTriggerHelperTest.cls
@isTest
public class OffersPromotionTriggerHelperTest {
    @TestSetup static void setupdData(){
        Test.startTest();
        Project__c projectRecord = new Project__c();
        projectRecord.Name = 'Test Project';
        insert projectRecord;
        
        OffersPromotions__c offerPromotion = new OffersPromotions__c();
        offerPromotion.Project__c = projectRecord.Id;
        offerPromotion.Name = 'Test1';
        offerPromotion.OfferName__c = 'Test1';
        offerPromotion.StartDate__c = System.today()+1;
        offerPromotion.EndDate__c = System.today()+30;
        offerPromotion.Approval_Status__c = 'Approved';
        offerPromotion.SalesEventCampaignName__c = 'Test1';
        insert offerPromotion;
        
        OffersPromotions__c offerPromotion1 = new OffersPromotions__c();
        offerPromotion1.Id = offerPromotion.Id;
        update offerPromotion1;
        
        Test.stopTest();
    }
    @isTest static void projectOfferDupeCheck(){
        Test.startTest();
        OffersPromotions__c offerPromotion = new OffersPromotions__c();
        offerPromotion.Project__c = [SELECT Id FROM Project__c LIMIT 1].Id;
        offerPromotion.Name = 'Test1';
        offerPromotion.OfferName__c = 'Test1';
        offerPromotion.StartDate__c = System.today()+2;
        offerPromotion.EndDate__c = System.today()+30;
        offerPromotion.Approval_Status__c = 'Approved';
        offerPromotion.SalesEventCampaignName__c = 'Test1';
        
        try{
            insert offerPromotion;
        }catch(Exception ex){
            
        }
        Test.stopTest();
    }
}