MODON MRE BPDEV/force-app/main/default/objects/Case/fields/CaseCategory__c.field-meta.xml
<CustomField>
    <fullName>CaseCategory__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Sub_Vertical__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Addition/Deletion of Joint Owner</fullName>
            </value>
            <value>
                <fullName>ADM/ADGM Registration</fullName>
            </value>
            <value>
                <fullName>ADM Fee Refund</fullName>
            </value>
            <value>
                <fullName>Advertisements/Events/Digital/PR</fullName>
            </value>
            <value>
                <fullName>Bank Details</fullName>
            </value>
            <value>
                <fullName>Bounced Cheque</fullName>
            </value>
            <value>
                <fullName>Broker Commission Enquiries</fullName>
            </value>
            <value>
                <fullName>Broker Enquiry</fullName>
            </value>
            <value>
                <fullName>Building Guideline Request</fullName>
            </value>
            <value>
                <fullName>Cancel &amp; Refund</fullName>
            </value>
            <value>
                <fullName>Cheque Replacement</fullName>
            </value>
            <value>
                <fullName>Claim</fullName>
            </value>
            <value>
                <fullName>Complaint</fullName>
            </value>
            <value>
                <fullName>Consolidation</fullName>
            </value>
            <value>
                <fullName>Construction Update</fullName>
            </value>
            <value>
                <fullName>Contact Details Update</fullName>
            </value>
            <value>
                <fullName>Court Order</fullName>
            </value>
            <value>
                <fullName>Customer Care</fullName>
            </value>
            <value>
                <fullName>Customer Data Privacy</fullName>
            </value>
            <value>
                <fullName>Default Notice</fullName>
            </value>
            <value>
                <fullName>Delay Handover</fullName>
            </value>
            <value>
                <fullName>Discount</fullName>
            </value>
            <value>
                <fullName>Duplicate Case</fullName>
            </value>
            <value>
                <fullName>Equity Transfer</fullName>
            </value>
            <value>
                <fullName>Expired Cheque Collection</fullName>
            </value>
            <value>
                <fullName>Fee Waiver</fullName>
            </value>
            <value>
                <fullName>Financial Services</fullName>
            </value>
            <value>
                <fullName>General Enquiry</fullName>
            </value>
            <value>
                <fullName>Golden visa</fullName>
            </value>
            <value>
                <fullName>Handover Date</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

MODON MRE BPDEV/force-app/main/default/objects/Case/fields/CaseSubCategory__c.field-meta.xml
<CustomField>
    <fullName>CaseSubCategory__c</fullName>
    <label>Sub Category</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>CaseCategory__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Addition/Deletion of Joint Owner</fullName>
            </value>
            <value>
                <fullName>ADM/ADGM Registration</fullName>
            </value>
            <value>
                <fullName>ADM Fee Refund</fullName>
            </value>
            <value>
                <fullName>ADM Fees</fullName>
            </value>
            <value>
                <fullName>ADM Fee Waiver</fullName>
            </value>
            <value>
                <fullName>ADM Waiver</fullName>
            </value>
            <value>
                <fullName>Appointment Request</fullName>
            </value>
            <value>
                <fullName>Bank Details</fullName>
            </value>
            <value>
                <fullName>Bounced Cheque</fullName>
            </value>
            <value>
                <fullName>Broker Inquiries</fullName>
            </value>
            <value>
                <fullName>Broker Portal</fullName>
            </value>
            <value>
                <fullName>Broker Registration</fullName>
            </value>
            <value>
                <fullName>Cancel &amp; Refund</fullName>
            </value>
            <value>
                <fullName>Cancellation with Refund</fullName>
            </value>
            <value>
                <fullName>Cheque Replacement</fullName>
            </value>
            <value>
                <fullName>Client Approvals</fullName>
            </value>
            <value>
                <fullName>Commission Enquiries</fullName>
            </value>
            <value>
                <fullName>Consolidation</fullName>
            </value>
            <value>
                <fullName>Construction Update</fullName>
            </value>
            <value>
                <fullName>Contact Details Update</fullName>
            </value>
            <value>
                <fullName>Customer Care</fullName>
            </value>
            <value>
                <fullName>Customer Data Privacy</fullName>
            </value>
            <value>
                <fullName>Default Notice And Termination</fullName>
            </value>
            <value>
                <fullName>Discount</fullName>
            </value>
            <value>
                <fullName>Docusign Follow Up</fullName>
            </value>
            <value>
                <fullName>Equity Transfer</fullName>
            </value>
            <value>
                <fullName>Expired Cheque Collection</fullName>
            </value>
            <value>
                <fullName>Financial Service</fullName>
            </value>
            <value>
                <fullName>Financial Services</fullName>
            </value>
            <value>
                <fullName>General Enquiry</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

MODON MRE BPDEV/force-app/main/default/objects/Case/fields/Customer_Email__c.field-meta.xml
<CustomField>
    <fullName>Customer_Email__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Customer Email</label>
    <type>Email</type>
</CustomField>

MODON MRE BPDEV/force-app/main/default/objects/Case/fields/New_Owner__c.field-meta.xml
<CustomField>
    <fullName>New_Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case Owner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>NewOwner</relationshipName>
    <type>Lookup</type>
</CustomField>

MODON MRE BPDEV/force-app/main/default/objects/Case/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unit</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>$Source.AccountId</field>
            <operation>equals</operation>
            <valueField>Unit__c.Opportunity__r.AccountId</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Unit__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

MODON MRE BPDEV/force-app/main/default/objects/Portal_Notification__c/Portal_Notification__c.object-meta.xml
<CustomObject>
    <label>Portal Notification</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Portal Notification Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Portal Notifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

MODON MRE BPDEV/force-app/main/default/objects/Portal_Notification__c/fields/Event_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Event_Date_Time__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Event Date &amp; Time</label>
    <type>DateTime</type>
</CustomField>

MODON MRE BPDEV/force-app/main/default/objects/Portal_Notification__c/fields/Event_Description__c.field-meta.xml
<CustomField>
    <fullName>Event_Description__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Event Description</label>
    <type>TextArea</type>
</CustomField>

MODON MRE BPDEV/force-app/main/default/objects/SalesOrder__c/SalesOrder__c.object-meta.xml
<CustomObject>
    <label>Sales Order</label>
    <nameField>
        <displayFormat>SO-{00000}</displayFormat>
        <label>Sales Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

MODON MRE BPDEV/force-app/main/default/objects/SalesOrder__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Reservation form generated</fullName>
            </value>
            <value>
                <fullName>Down payment collected</fullName>
            </value>
            <value>
                <fullName>Reservation form signed</fullName>
            </value>
            <value>
                <fullName>Installment Payment Collected</fullName>
            </value>
            <value>
                <fullName>DP Payment Confirmed</fullName>
            </value>
            <value>
                <fullName>SPA Generated</fullName>
            </value>
            <value>
                <fullName>SPA Signed (Customer)</fullName>
            </value>
            <value>
                <fullName>SPA Signed (Modon)</fullName>
            </value>
            <value>
                <fullName>SPA Delivered</fullName>
            </value>
            <value>
                <fullName>Sold</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>System cancelled</fullName>
            </value>
            <value>
                <fullName>KYC - In progress</fullName>
            </value>
            <value>
                <fullName>KYC - Completed / KYC Rejected</fullName>
            </value>
            <value>
                <fullName>Payments Collected</fullName>
            </value>
            <value>
                <fullName>Downpayment Payments Cleared</fullName>
            </value>
            <value>
                <fullName>SPA Sent to customer</fullName>
            </value>
            <value>
                <fullName>SPA Validated</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Cancelled SR</fullName>
            </value>
            <value>
                <fullName>Voided</fullName>
            </value>
            <value>
                <fullName>Pending Blocking Fees</fullName>
            </value>
            <value>
                <fullName>Blocking Fees Collected</fullName>
            </value>
            <value>
                <fullName>Property Transfer Cancelled - SR</fullName>
            </value>
            <value>
                <fullName>Unit Swap Cancelled - SR</fullName>
            </value>
            <value>
                <fullName>Unit Upgrade Cancelled - SR</fullName>
            </value>
            <value>
                <fullName>Unit Cancellation Cancelled - SR</fullName>
            </value>
            <value>
                <fullName>Unit Consolidation Cancelled - SR</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

MODON MRE BPDEV/force-app/main/default/objects/SalesOrder__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unit</label>
    <referenceTo>Unit__c</referenceTo>
    <relationshipLabel>Sales Orders</relationshipLabel>
    <relationshipName>Sales_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

MODON MRE BPDEV/force-app/main/default/objects/ServiceRequest__c/ServiceRequest__c.object-meta.xml
<CustomObject>
    <label>Service Request</label>
    <nameField>
        <displayFormat>SR-{0000}</displayFormat>
        <label>ServiceRequest Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

MODON MRE BPDEV/force-app/main/default/objects/ServiceRequest__c/fields/Comments__c.field-meta.xml
<CustomField>
    <fullName>Comments__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Comments</label>
    <length>400</length>
    <type>LongTextArea</type>
</CustomField>

MODON MRE BPDEV/force-app/main/default/objects/ServiceRequest__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>In-progress</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
                <isActive>false</isActive>
                <label>Draft</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

MODON MRE BPDEV/force-app/main/default/objects/Unit__c/Unit__c.object-meta.xml
<CustomObject>
    <description>This object is part of inventory management to store the unit details</description>
    <label>Unit</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Units</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

MODON MRE BPDEV/force-app/main/default/objects/Unit__c/fields/Comments__c.field-meta.xml
<CustomField>
    <fullName>Comments__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Comments</label>
    <length>62072</length>
    <type>LongTextArea</type>
</CustomField>

MODON MRE BPDEV/force-app/main/default/classes/CustomerNotificaionAPI.cls
/**
* --------------------------------------------------------------------------------------------------------------------
* Version       Author              Date                Comment
* 1.0           Suresh   	       05 March 2026        Initial Draft
* 1.1			Suresh			   31 July  2026		Datetime updated	
**/
@RestResource(urlMapping='/CustomerNotificaionAPI/*')
global class CustomerNotificaionAPI {
    
    @HttpGet
    global static void getNotificaion() {
        RestRequest req = RestContext.request;
        RestResponse res = RestContext.response;
        String requestId = String.valueOf(UUID.randomUUID());
        list<CustomerNotification> notifMessage=new list<CustomerNotification>();
        try {
            String userName = req.params.get('CustomerEmail'); 
            if (String.isBlank(userName) ) {
                returnError(res, requestId, 'Missing User Email Parameter', 200);
                return;
            }else{  
                    notifMessage =getThisMonthsNotifications(userName);
                    if (notifMessage.size() ==0) {
                        returnError(res, requestId, 'There is not Notification', 200);
                        return;
                    }
            } 
            APIResponse response = new APIResponse('success', requestId, notifMessage, null);
            res.responseBody = Blob.valueOf(JSON.serialize(response));
            res.addHeader('Content-Type', 'application/json');
            res.statusCode = 200;
            
        } catch (Exception ex) {
            LoggerService.save(LoggerService.createApexLog(ex, 'Customer Notification API', 'CustomerNotificationAPI', 'getNotificaion'));
            returnError(res, requestId, 'Server Error: ' + ex.getMessage(), 200);
        }
    }
    private static void returnError(RestResponse res, String requestId, String msg, Integer status) {
        APIResponse error = new APIResponse('error', requestId, null, msg);
        res.responseBody = Blob.valueOf(JSON.serialize(error));
        res.statusCode = status;
    }   
    public static List<CustomerNotification> getThisMonthsNotifications(string eamil) {
        Date startOfMonth = Date.today().toStartOfMonth();
        Date endOfMonth = startOfMonth.addMonths(1);
        list<CustomerNotification> customerNotificationWrapper =new list<CustomerNotification>();
        for(Portal_Notification__c notifications: [SELECT id,Name, Event_Date_Time__c, Event_Description__c   
                                                   FROM Portal_Notification__c WHERE Event_Date_Time__c >= :startOfMonth AND Event_Date_Time__c < :endOfMonth ORDER BY Event_Date_Time__c ASC]){
            CustomerNotification newNotWrapper=new CustomerNotification();
            newNotWrapper.NotificationNumber = notifications.Name;
            newNotWrapper.Comments =notifications.Event_Description__c;
            newNotWrapper.Status = 'Open';
            newNotWrapper.NotificationType = 'Event';
            customerNotificationWrapper.add(newNotWrapper);
        }
        for(case caseRec : [select id,CaseNumber,Status,Subject,Comments,CreatedDate,
                            CaseCategory__c, CaseSubCategory__c, New_Owner__r.Name, Unit__r.Name, ClosedDate, Description
                            from Case where Customer_Email__c=:eamil ORDER BY CreatedDate DESC]){
             CustomerNotification newCaseNotiy=new CustomerNotification();
             newCaseNotiy.NotificationNumber = caseRec.CaseNumber;
             newCaseNotiy.Comments =caseRec.Description;
             newCaseNotiy.Status = caseRec.Status;
             newCaseNotiy.Subject = caseRec.Subject;
             newCaseNotiy.NotificationType ='Case';
             //1.1 changes                   
             //DateTime createdDate = caseRec.CreatedDate; 
             //String caseDate = createdDate.format('dd MMM yyyy');
             //System.debug('caseDate---- ' + caseDate);
             newCaseNotiy.CreatedDate=caseRec.CreatedDate!=null?String.valueOf(caseRec.CreatedDate):'';
             //DateTime completedDate = caseRec.ClosedDate; 
             //String caseCompleteDate = completedDate!=null?completedDate.format('dd MMM yyyy'):'';
             //System.debug('>>>>   ' + caseCompleteDate);
             newCaseNotiy.CompletedDate=caseRec.ClosedDate!=null?String.valueOf(caseRec.ClosedDate):'';
             newCaseNotiy.Category = caseRec.CaseCategory__c;
             newCaseNotiy.Subcategory = caseRec.CaseSubCategory__c;
             newCaseNotiy.Property = caseRec.Unit__c!=null?caseRec.Unit__r.Name:'';
             newCaseNotiy.Owner = caseRec.New_Owner__r.Name; 
             newCaseNotiy.ExpectedResponseDate = '';                       
             customerNotificationWrapper.add(newCaseNotiy);
        }
        for(ServiceRequest__c obj_SR : [SELECT Id, Comments__c, Name,Status__c, CreatedDate, UnitId__r.Name, 
                            			 Owner.Name, CloseDate__c, RecordType.Name, SalesOrder__r.Name, SalesOrder__r.Unit__r.Name, 
                                         SalesOrder__r.ProjectName__c 
                                         from ServiceRequest__c 
                                         where AccountId__r.PersonEmail = :eamil ORDER BY CreatedDate DESC]){
             CustomerNotification newCaseNotiy=new CustomerNotification();
             String serviceName =  obj_SR.Name;                               
             if(String.isNotBlank(obj_SR.SalesOrder__r.Name)){
                serviceName = serviceName + ' '+ obj_SR.SalesOrder__r.Name;                                 
             } 
             if(String.isNotBlank(obj_SR.SalesOrder__r.Unit__r.Name)){
                serviceName = serviceName + ' '+ obj_SR.SalesOrder__r.Unit__r.Name;                                 
             }
             if(String.isNotBlank(obj_SR.SalesOrder__r.ProjectName__c)){
                serviceName = serviceName + ' '+ obj_SR.SalesOrder__r.ProjectName__c;                                 
             }                                
             newCaseNotiy.NotificationNumber = serviceName;
             newCaseNotiy.Comments =obj_SR.Comments__c;
             newCaseNotiy.Status = obj_SR.Status__c;
             newCaseNotiy.Subject = obj_SR.RecordType.Name;
             newCaseNotiy.NotificationType ='Support Requests';
             //1.1 changes                                  
             //DateTime createdDate = obj_SR.CreatedDate; 
             //String srDate = createdDate.format('dd MMM yyyy');
             //System.debug('>>>>   ' + srDate);
             newCaseNotiy.CreatedDate=obj_SR.CreatedDate!=null?String.valueOf(obj_SR.CreatedDate):'';
             //DateTime completedDate = obj_SR.CloseDate__c; 
             //String srCompleteDate = completedDate!=null?completedDate.format('dd MMM yyyy'):'';
             //System.debug('>>>>   ' + srCompleteDate);
             newCaseNotiy.CompletedDate=obj_SR.CloseDate__c!=null?String.valueOf(obj_SR.CloseDate__c):''; 
             newCaseNotiy.Category = 'Service Requests';
             newCaseNotiy.Subcategory = obj_SR.Name;
             newCaseNotiy.Property = obj_SR.UnitId__c!=null?obj_SR.UnitId__r.Name:'';
             newCaseNotiy.Owner = obj_SR.Owner.Name; 
             newCaseNotiy.ExpectedResponseDate = '';                                
             customerNotificationWrapper.add(newCaseNotiy);
        }
        return customerNotificationWrapper;
    }
    public class CustomerNotification{
        public String NotificationNumber;
        public String Comments;
        public String Subject;
        public String Status;
        public String NotificationType;
        public String CreatedDate; 
        public String Category;
        public String Subcategory;
        public String Property;
        public String Owner;
        public String CompletedDate;
        public String ExpectedResponseDate;
    }   
}