MODON MRE BPDEV/force-app/main/default/objects/Case/fields/CaseCategory__c.field-meta.xml
<CustomField>
    <fullName>CaseCategory__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Sub_Vertical__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Addition/Deletion of Joint Owner</fullName>
            </value>
            <value>
                <fullName>ADM/ADGM Registration</fullName>
            </value>
            <value>
                <fullName>ADM Fee Refund</fullName>
            </value>
            <value>
                <fullName>Advertisements/Events/Digital/PR</fullName>
            </value>
            <value>
                <fullName>Bank Details</fullName>
            </value>
            <value>
                <fullName>Bounced Cheque</fullName>
            </value>
            <value>
                <fullName>Broker Commission Enquiries</fullName>
            </value>
            <value>
                <fullName>Broker Enquiry</fullName>
            </value>
            <value>
                <fullName>Building Guideline Request</fullName>
            </value>
            <value>
                <fullName>Cancel &amp; Refund</fullName>
            </value>
            <value>
                <fullName>Cheque Replacement</fullName>
            </value>
            <value>
                <fullName>Claim</fullName>
            </value>
            <value>
                <fullName>Complaint</fullName>
            </value>
            <value>
                <fullName>Consolidation</fullName>
            </value>
            <value>
                <fullName>Construction Update</fullName>
            </value>
            <value>
                <fullName>Contact Details Update</fullName>
            </value>
            <value>
                <fullName>Court Order</fullName>
            </value>
            <value>
                <fullName>Customer Care</fullName>
            </value>
            <value>
                <fullName>Customer Data Privacy</fullName>
            </value>
            <value>
                <fullName>Default Notice</fullName>
            </value>
            <value>
                <fullName>Delay Handover</fullName>
            </value>
            <value>
                <fullName>Discount</fullName>
            </value>
            <value>
                <fullName>Duplicate Case</fullName>
            </value>
            <value>
                <fullName>Equity Transfer</fullName>
            </value>
            <value>
                <fullName>Expired Cheque Collection</fullName>
            </value>
            <value>
                <fullName>Fee Waiver</fullName>
            </value>
            <value>
                <fullName>Financial Services</fullName>
            </value>
            <value>
                <fullName>General Enquiry</fullName>
            </value>
            <value>
                <fullName>Golden visa</fullName>
            </value>
            <value>
                <fullName>Handover Date</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

MODON MRE BPDEV/force-app/main/default/objects/Case/fields/CaseSubCategory__c.field-meta.xml
<CustomField>
    <fullName>CaseSubCategory__c</fullName>
    <label>Sub Category</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>CaseCategory__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Addition/Deletion of Joint Owner</fullName>
            </value>
            <value>
                <fullName>ADM/ADGM Registration</fullName>
            </value>
            <value>
                <fullName>ADM Fee Refund</fullName>
            </value>
            <value>
                <fullName>ADM Fees</fullName>
            </value>
            <value>
                <fullName>ADM Fee Waiver</fullName>
            </value>
            <value>
                <fullName>ADM Waiver</fullName>
            </value>
            <value>
                <fullName>Appointment Request</fullName>
            </value>
            <value>
                <fullName>Bank Details</fullName>
            </value>
            <value>
                <fullName>Bounced Cheque</fullName>
            </value>
            <value>
                <fullName>Broker Inquiries</fullName>
            </value>
            <value>
                <fullName>Broker Portal</fullName>
            </value>
            <value>
                <fullName>Broker Registration</fullName>
            </value>
            <value>
                <fullName>Cancel &amp; Refund</fullName>
            </value>
            <value>
                <fullName>Cancellation with Refund</fullName>
            </value>
            <value>
                <fullName>Cheque Replacement</fullName>
            </value>
            <value>
                <fullName>Client Approvals</fullName>
            </value>
            <value>
                <fullName>Commission Enquiries</fullName>
            </value>
            <value>
                <fullName>Consolidation</fullName>
            </value>
            <value>
                <fullName>Construction Update</fullName>
            </value>
            <value>
                <fullName>Contact Details Update</fullName>
            </value>
            <value>
                <fullName>Customer Care</fullName>
            </value>
            <value>
                <fullName>Customer Data Privacy</fullName>
            </value>
            <value>
                <fullName>Default Notice And Termination</fullName>
            </value>
            <value>
                <fullName>Discount</fullName>
            </value>
            <value>
                <fullName>Docusign Follow Up</fullName>
            </value>
            <value>
                <fullName>Equity Transfer</fullName>
            </value>
            <value>
                <fullName>Expired Cheque Collection</fullName>
            </value>
            <value>
                <fullName>Financial Service</fullName>
            </value>
            <value>
                <fullName>Financial Services</fullName>
            </value>
            <value>
                <fullName>General Enquiry</fullName>
            </value>
            <value>
                <fullName>Office Location/Working Hours</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

MODON MRE BPDEV/force-app/main/default/objects/Case/fields/Customer_Name__c.field-meta.xml
<CustomField>
    <fullName>Customer_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Customer Name</label>
    <type>TextArea</type>
</CustomField>

MODON MRE BPDEV/force-app/main/default/objects/Case/fields/Customer_Phone__c.field-meta.xml
<CustomField>
    <fullName>Customer_Phone__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Customer Phone</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

MODON MRE BPDEV/force-app/main/default/objects/Case/fields/Customer_Type__c.field-meta.xml
<CustomField>
    <fullName>Customer_Type__c</fullName>
    <label>Customer Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Owner</fullName>
            </value>
            <value>
                <fullName>Visitor</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

MODON MRE BPDEV/force-app/main/default/objects/Case/fields/New_Owner__c.field-meta.xml
<CustomField>
    <fullName>New_Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case Owner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>NewOwner</relationshipName>
    <type>Lookup</type>
</CustomField>

MODON MRE BPDEV/force-app/main/default/objects/Case/fields/RunningTestClass__c.field-meta.xml
<CustomField>
    <fullName>RunningTestClass__c</fullName>
    <defaultValue>false</defaultValue>
    <label>RunningTestClass</label>
    <type>Checkbox</type>
</CustomField>

MODON MRE BPDEV/force-app/main/default/objects/Case/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unit</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>$Source.AccountId</field>
            <operation>equals</operation>
            <valueField>Unit__c.Opportunity__r.AccountId</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Unit__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

MODON MRE BPDEV/force-app/main/default/objects/Case/fields/Visitor_First_Name__c.field-meta.xml
<CustomField>
    <fullName>Visitor_First_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Visitor First Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

MODON MRE BPDEV/force-app/main/default/objects/Case/fields/Visitor_Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Visitor_Last_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Visitor Last Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

MODON MRE BPDEV/force-app/main/default/objects/Case/fields/Visitor_Phone__c.field-meta.xml
<CustomField>
    <fullName>Visitor_Phone__c</fullName>
    <label>Visitor Phone</label>
    <length>25</length>
    <maskChar>asterisk</maskChar>
    <maskType>lastFour</maskType>
    <type>EncryptedText</type>
</CustomField>

MODON MRE BPDEV/force-app/main/default/objects/Unit__c/Unit__c.object-meta.xml
<CustomObject>
    <description>This object is part of inventory management to store the unit details</description>
    <label>Unit</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Units</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

MODON MRE BPDEV/force-app/main/default/objects/Unit__c/fields/PlotNo__c.field-meta.xml
<CustomField>
    <fullName>PlotNo__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Plot No</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

MODON MRE BPDEV/force-app/main/default/classes/CaseSMSCommunicationTest.cls
@isTest
public class CaseSMSCommunicationTest {

    private class MockCallout implements HttpCalloutMock {
        public HTTPResponse respond(HTTPRequest req) {
            HttpResponse res = new HttpResponse();
            res.setHeader('Content-Type', 'application/json');
            res.setBody('[{"MessageId":"TEST-SMS-001","Status":"sent"}]');
            res.setStatusCode(200);
            return res;
        }
    }

    static Map<String, Id> getTestIds() {
        Map<String, Id> ids = new Map<String, Id>();
        ids.put('modonTestUser', [SELECT Id FROM User WHERE LastName = 'CallCenterUser' AND IsActive = true LIMIT 1].Id);
        ids.put('vipOrganizationAccount', [SELECT Id FROM Account WHERE Name = 'AccountVIP' LIMIT 1].Id);
        ids.put('vipOrganizationcontact', [SELECT Id FROM Contact WHERE LastName = 'Contact' AND Account.Name = 'AccountVIP' LIMIT 1].Id);
        ids.put('Unit', [SELECT Id FROM Unit__c WHERE PlotNo__c = '105' LIMIT 1].Id);
        return ids;
    }

    @TestSetup
    static void setupData() {
        TestDataFactory.createTestData();
        Map<String, Id> ids = getTestIds();

        CaseTriggerHandler.isTriggerDisabled = true;

        List<Case> casesToInsert = new List<Case>();

        casesToInsert.add(new Case(
            RunningTestClass__c = true,
            AccountId = ids.get('vipOrganizationAccount'),
            ContactId = ids.get('vipOrganizationcontact'),
            Status = 'In Progress',
            Customer_Type__c = ServiceConstants.CASE_CUSTOMER_TYPE_OWNER,
            Customer_Phone__c = '+971888999654',
            Customer_Name__c = 'SMS Test Owner',
            CaseCategory__c = 'General Enquiry',
            CaseSubCategory__c = 'Office Location/Working Hours',
            Unit__c = ids.get('Unit'),
            New_Owner__c = ids.get('modonTestUser')
        ));

        casesToInsert.add(new Case(
            RunningTestClass__c = true,
            Status = 'In Progress',
            Customer_Type__c = ServiceConstants.CASE_CUSTOMER_TYPE_VISITOR,
            Visitor_Phone__c = '+971507654321',
            Visitor_First_Name__c = 'SMS Test Visitor',
            CaseCategory__c = 'General Enquiry',
            CaseSubCategory__c = 'Office Location/Working Hours',
            Unit__c = ids.get('Unit'),
            Visitor_Last_Name__c = 'Jambal',
            New_Owner__c = ids.get('modonTestUser')
        ));

        casesToInsert.add(new Case(
            RunningTestClass__c = true,
            AccountId = ids.get('vipOrganizationAccount'),
            Status = 'In Progress',
            Customer_Type__c = ServiceConstants.CASE_CUSTOMER_TYPE_OWNER,
            Customer_Name__c = 'SMS No Phone Owner',
            CaseCategory__c = 'General Enquiry',
            CaseSubCategory__c = 'Office Location/Working Hours',
            Visitor_Last_Name__c = 'Bak',
            Visitor_Phone__c = '+919885370070',
            Unit__c = ids.get('Unit'),
            New_Owner__c = ids.get('modonTestUser')
        ));

        insert casesToInsert;

        CaseTriggerHandler.isTriggerDisabled = false;
    }

    @isTest
    static void testOwnerCase() {
        List<Case> cases = [
            SELECT Id, CaseNumber, Customer_Type__c,
                   Customer_Phone__c, Customer_Name__c,
                   Visitor_Phone__c, Visitor_First_Name__c
            FROM Case
            WHERE Customer_Name__c = 'SMS Test Owner'
            LIMIT 1
        ];
        Test.setMock(HttpCalloutMock.class, new MockCallout());
        Test.startTest();
        System.enqueueJob(new CaseSmsCommunication(cases));
        Test.stopTest();
    }

    @isTest
    static void testVisitorCase() {
        List<Case> cases = [
            SELECT Id, CaseNumber, Customer_Type__c,
                   Customer_Phone__c, Customer_Name__c,
                   Visitor_Phone__c, Visitor_First_Name__c
            FROM Case
            WHERE Visitor_First_Name__c = 'SMS Test Visitor'
            LIMIT 1
        ];
        Test.setMock(HttpCalloutMock.class, new MockCallout());
        Test.startTest();
        System.enqueueJob(new CaseSmsCommunication(cases));
        Test.stopTest();
    }

    @isTest
    static void testNoPhoneCase() {
        List<Case> cases = [
            SELECT Id, CaseNumber, Customer_Type__c,
                   Customer_Phone__c, Customer_Name__c,
                   Visitor_Phone__c, Visitor_First_Name__c
            FROM Case
            WHERE Customer_Name__c = 'SMS No Phone Owner'
            LIMIT 1
        ];
        Test.setMock(HttpCalloutMock.class, new MockCallout());
        Test.startTest();
        System.enqueueJob(new CaseSmsCommunication(cases));
        Test.stopTest();
    }

    @isTest
    static void testMixedCases() {
        List<Case> cases = [
            SELECT Id, CaseNumber, Customer_Type__c,
                   Customer_Phone__c, Customer_Name__c,
                   Visitor_Phone__c, Visitor_First_Name__c
            FROM Case
            WHERE Customer_Name__c IN ('SMS Test Owner', 'SMS No Phone Owner')
            OR Visitor_First_Name__c = 'SMS Test Visitor'
        ];
        Test.setMock(HttpCalloutMock.class, new MockCallout());
        Test.startTest();
        System.enqueueJob(new CaseSmsCommunication(cases));
        Test.stopTest();
    }

    @isTest
    static void testEmptyList() {
        Test.setMock(HttpCalloutMock.class, new MockCallout());
        Test.startTest();
        System.enqueueJob(new CaseSmsCommunication(new List<Case>()));
        Test.stopTest();
    }

    @isTest
    static void testNullList() {
        Test.setMock(HttpCalloutMock.class, new MockCallout());
        Test.startTest();
        System.enqueueJob(new CaseSmsCommunication(null));
        Test.stopTest();
    }
}