MODON MRE BPDEV/force-app/main/default/objects/Case/fields/CaseCategory__c.field-meta.xml
<CustomField>
    <fullName>CaseCategory__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Sub_Vertical__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Addition/Deletion of Joint Owner</fullName>
            </value>
            <value>
                <fullName>ADM/ADGM Registration</fullName>
            </value>
            <value>
                <fullName>ADM Fee Refund</fullName>
            </value>
            <value>
                <fullName>Advertisements/Events/Digital/PR</fullName>
            </value>
            <value>
                <fullName>Bank Details</fullName>
            </value>
            <value>
                <fullName>Bounced Cheque</fullName>
            </value>
            <value>
                <fullName>Broker Commission Enquiries</fullName>
            </value>
            <value>
                <fullName>Broker Enquiry</fullName>
            </value>
            <value>
                <fullName>Building Guideline Request</fullName>
            </value>
            <value>
                <fullName>Cancel &amp; Refund</fullName>
            </value>
            <value>
                <fullName>Cheque Replacement</fullName>
            </value>
            <value>
                <fullName>Claim</fullName>
            </value>
            <value>
                <fullName>Complaint</fullName>
            </value>
            <value>
                <fullName>Consolidation</fullName>
            </value>
            <value>
                <fullName>Construction Update</fullName>
            </value>
            <value>
                <fullName>Contact Details Update</fullName>
            </value>
            <value>
                <fullName>Court Order</fullName>
            </value>
            <value>
                <fullName>Customer Care</fullName>
            </value>
            <value>
                <fullName>Customer Data Privacy</fullName>
            </value>
            <value>
                <fullName>Default Notice</fullName>
            </value>
            <value>
                <fullName>Delay Handover</fullName>
            </value>
            <value>
                <fullName>Discount</fullName>
            </value>
            <value>
                <fullName>Duplicate Case</fullName>
            </value>
            <value>
                <fullName>Equity Transfer</fullName>
            </value>
            <value>
                <fullName>Expired Cheque Collection</fullName>
            </value>
            <value>
                <fullName>Fee Waiver</fullName>
            </value>
            <value>
                <fullName>Financial Services</fullName>
            </value>
            <value>
                <fullName>General Enquiry</fullName>
            </value>
            <value>
                <fullName>Golden visa</fullName>
            </value>
            <value>
                <fullName>Handover Date</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

MODON MRE BPDEV/force-app/main/default/objects/Case/fields/CaseSubCategory__c.field-meta.xml
<CustomField>
    <fullName>CaseSubCategory__c</fullName>
    <label>Sub Category</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>CaseCategory__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Addition/Deletion of Joint Owner</fullName>
            </value>
            <value>
                <fullName>ADM/ADGM Registration</fullName>
            </value>
            <value>
                <fullName>ADM Fee Refund</fullName>
            </value>
            <value>
                <fullName>ADM Fees</fullName>
            </value>
            <value>
                <fullName>ADM Fee Waiver</fullName>
            </value>
            <value>
                <fullName>ADM Waiver</fullName>
            </value>
            <value>
                <fullName>Appointment Request</fullName>
            </value>
            <value>
                <fullName>Bank Details</fullName>
            </value>
            <value>
                <fullName>Bounced Cheque</fullName>
            </value>
            <value>
                <fullName>Broker Inquiries</fullName>
            </value>
            <value>
                <fullName>Broker Portal</fullName>
            </value>
            <value>
                <fullName>Broker Registration</fullName>
            </value>
            <value>
                <fullName>Cancel &amp; Refund</fullName>
            </value>
            <value>
                <fullName>Cancellation with Refund</fullName>
            </value>
            <value>
                <fullName>Cheque Replacement</fullName>
            </value>
            <value>
                <fullName>Client Approvals</fullName>
            </value>
            <value>
                <fullName>Commission Enquiries</fullName>
            </value>
            <value>
                <fullName>Consolidation</fullName>
            </value>
            <value>
                <fullName>Construction Update</fullName>
            </value>
            <value>
                <fullName>Contact Details Update</fullName>
            </value>
            <value>
                <fullName>Customer Care</fullName>
            </value>
            <value>
                <fullName>Customer Data Privacy</fullName>
            </value>
            <value>
                <fullName>Default Notice And Termination</fullName>
            </value>
            <value>
                <fullName>Discount</fullName>
            </value>
            <value>
                <fullName>Docusign Follow Up</fullName>
            </value>
            <value>
                <fullName>Equity Transfer</fullName>
            </value>
            <value>
                <fullName>Expired Cheque Collection</fullName>
            </value>
            <value>
                <fullName>Financial Service</fullName>
            </value>
            <value>
                <fullName>Financial Services</fullName>
            </value>
            <value>
                <fullName>General Enquiry</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

MODON MRE BPDEV/force-app/main/default/objects/Case/fields/CaseType__c.field-meta.xml
<CustomField>
    <fullName>CaseType__c</fullName>
    <label>Case Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Complaint</fullName>
            </value>
            <value>
                <fullName>VIP Case</fullName>
            </value>
            <value>
                <fullName>Compliment</fullName>
            </value>
            <value>
                <fullName>Visitor Case</fullName>
            </value>
            <value>
                <fullName>Standard</fullName>
            </value>
            <value>
                <fullName>Non VIP Case</fullName>
            </value>
            <value>
                <fullName>Departmental</fullName>
                <isActive>false</isActive>
                <label>Departmental</label>
            </value>
            <value>
                <fullName>General Enquiry</fullName>
                <isActive>false</isActive>
                <label>General Enquiry</label>
            </value>
            <value>
                <fullName>Negative Feedback</fullName>
                <isActive>false</isActive>
                <label>Negative Feedback</label>
            </value>
            <value>
                <fullName>Service Request</fullName>
                <isActive>false</isActive>
                <label>Service Request</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

MODON MRE BPDEV/force-app/main/default/objects/Case/fields/Language_Preference__c.field-meta.xml
<CustomField>
    <fullName>Language_Preference__c</fullName>
    <label>Language Preference</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>English</fullName>
                <default>true</default>
                <label>English</label>
            </value>
            <value>
                <fullName>Arabic</fullName>
            </value>
            <value>
                <fullName>Russian</fullName>
            </value>
            <value>
                <fullName>Mandarin</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

MODON MRE BPDEV/force-app/main/default/objects/Case/fields/New_Owner__c.field-meta.xml
<CustomField>
    <fullName>New_Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case Owner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>NewOwner</relationshipName>
    <type>Lookup</type>
</CustomField>

MODON MRE BPDEV/force-app/main/default/classes/ClearCasesInQueues.cls
public without sharing class ClearCasesInQueues 
{
    public static void ClearCases(List<SObject> newList)
    {
        List<Case> newCaseList = (List<Case>)newList;
        system.debug('start');
        if(newCaseList.size() == 0)
        {
            newCaseList = [select id,casenumber,ownerid,createddate,New_owner__c,status,ParentId,CaseType__c,Origin,casecategory__c,casesubcategory__c,Language_Preference__c from case 
                           where status = 'New' and casecategory__c  IN
                           ('Contact Center', 'Contact Center / Front Liners', 'Contact Details Update', 'Default & Collections', 'Department Action'
                            , 'Finance', 'Finance / Front Liners', 'General Enquiry', 'Handover', 'KYC Update', 'Operations'
                            , 'Post Sales', 'Real Estate Services', 'Service Request') 
                           AND ownerid not IN (SELECT id FROM User)  order by casesubcategory__c ];
        }
        system.debug('newCaseList.size() :' + newCaseList.size());
        if(newCaseList.size() > 0)
        {
            CaseTriggerHelper.assignToQueueOwner_Updated(newCaseList);
            update newCaseList;
        }
        system.debug('completed');
    }
}