MODON MRE BPDEV/force-app/main/default/objects/DirectDebit_Payment_Response__c/DirectDebit_Payment_Response__c.object-meta.xml
<CustomObject>
    <label>DirectDebit_Payment_Response</label>
    <nameField>
        <displayFormat>DPR-{00000000}</displayFormat>
        <label>DirectDebit_Payment_Response Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DirectDebit_Payment_Responses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

MODON MRE BPDEV/force-app/main/default/objects/DirectDebit_Payment_Response__c/fields/DDA_REF_NO__c.field-meta.xml
<CustomField>
    <fullName>DDA_REF_NO__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>DDA_REF_NO</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

MODON MRE BPDEV/force-app/main/default/objects/DirectDebit_Payment_Response__c/fields/DirectDebit_Transactions__c.field-meta.xml
<CustomField>
    <fullName>DirectDebit_Transactions__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>DirectDebit_Transactions</label>
    <referenceTo>DirectDebit_Transactions__c</referenceTo>
    <relationshipLabel>DirectDebit_Payment_Responses</relationshipLabel>
    <relationshipName>DirectDebit_Payment_Responses</relationshipName>
    <type>Lookup</type>
</CustomField>

MODON MRE BPDEV/force-app/main/default/objects/DirectDebit_Payment_Response__c/fields/Reason__c.field-meta.xml
<CustomField>
    <fullName>Reason__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Reason</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

MODON MRE BPDEV/force-app/main/default/objects/DirectDebit_Payment_Response__c/fields/Ref_No__c.field-meta.xml
<CustomField>
    <fullName>Ref_No__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Ref_No</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

MODON MRE BPDEV/force-app/main/default/objects/DirectDebit_Payment_Response__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Status</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

MODON MRE BPDEV/force-app/main/default/objects/DirectDebit_Registration_Response__c/DirectDebit_Registration_Response__c.object-meta.xml
<CustomObject>
    <label>DirectDebit_Registration_Response</label>
    <nameField>
        <displayFormat>DDRS-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DirectDebit_Registration_Response</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

MODON MRE BPDEV/force-app/main/default/objects/DirectDebit_Registration_Response__c/fields/DirectDebit_Transactions__c.field-meta.xml
<CustomField>
    <fullName>DirectDebit_Transactions__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>DirectDebit_Transactions</label>
    <referenceTo>DirectDebit_Transactions__c</referenceTo>
    <relationshipLabel>DirectDebit_Registration_Response</relationshipLabel>
    <relationshipName>DirectDebit_Registration_Response</relationshipName>
    <type>Lookup</type>
</CustomField>

MODON MRE BPDEV/force-app/main/default/objects/DirectDebit_Registration_Response__c/fields/Payer_Identification__c.field-meta.xml
<CustomField>
    <fullName>Payer_Identification__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Payer Identification</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

MODON MRE BPDEV/force-app/main/default/objects/DirectDebit_Registration_Response__c/fields/Reason__c.field-meta.xml
<CustomField>
    <fullName>Reason__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Reason</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

MODON MRE BPDEV/force-app/main/default/objects/DirectDebit_Registration_Response__c/fields/Request_Type__c.field-meta.xml
<CustomField>
    <fullName>Request_Type__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Request Type</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

MODON MRE BPDEV/force-app/main/default/objects/DirectDebit_Registration_Response__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Status</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

MODON MRE BPDEV/force-app/main/default/objects/DirectDebit_Transactions__c/DirectDebit_Transactions__c.object-meta.xml
<CustomObject>
    <label>DirectDebit_Transactions</label>
    <nameField>
        <displayFormat>DDT-{0000000}</displayFormat>
        <label>DD Transaction Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DirectDebit_Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

MODON MRE BPDEV/force-app/main/default/objects/DirectDebit_Transactions__c/fields/Ack_Nack_Response__c.field-meta.xml
<CustomField>
    <fullName>Ack_Nack_Response__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Ack/Nack Response</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

MODON MRE BPDEV/force-app/main/default/objects/DirectDebit_Transactions__c/fields/DDA_Unique_Number__c.field-meta.xml
<CustomField>
    <fullName>DDA_Unique_Number__c</fullName>
    <formula>Direct_Debit_Request__r.DDA_Unique_Number__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>DDA Unique Number</label>
    <type>Text</type>
</CustomField>

MODON MRE BPDEV/force-app/main/default/objects/DirectDebit_Transactions__c/fields/DirectDebit_Registration_Response__c.field-meta.xml
<CustomField>
    <fullName>DirectDebit_Registration_Response__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>DirectDebit_Registration_Response</label>
    <referenceTo>DirectDebit_Registration_Response__c</referenceTo>
    <relationshipLabel>DirectDebit_Transactions</relationshipLabel>
    <relationshipName>DirectDebit_Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

MODON MRE BPDEV/force-app/main/default/objects/DirectDebit_Transactions__c/fields/Payer_Identification__c.field-meta.xml
<CustomField>
    <fullName>Payer_Identification__c</fullName>
    <formula>Direct_Debit_Request__r.Payer_Identification__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Payer Identification</label>
    <type>Text</type>
</CustomField>

MODON MRE BPDEV/force-app/main/default/objects/DirectDebit_Transactions__c/fields/Request_Type__c.field-meta.xml
<CustomField>
    <fullName>Request_Type__c</fullName>
    <label>Request Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New Registration</fullName>
            </value>
            <value>
                <fullName>Collection</fullName>
            </value>
            <value>
                <fullName>Cancellation</fullName>
            </value>
            <value>
                <fullName>UAEDDS Collection</fullName>
            </value>
            <value>
                <fullName>UAEDDS Representment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

MODON MRE BPDEV/force-app/main/default/objects/DirectDebit_Transactions__c/fields/SOInstallment__c.field-meta.xml
<CustomField>
    <fullName>SOInstallment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Order Installment</label>
    <referenceTo>SalesOrderInstallments__c</referenceTo>
    <relationshipLabel>DirectDebit_Transactions</relationshipLabel>
    <relationshipName>DirectDebit_Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

MODON MRE BPDEV/force-app/main/default/objects/DirectDebit_Transactions__c/fields/Transaction_Number__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Number__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Transaction Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

MODON MRE BPDEV/force-app/main/default/objects/DirectDebit_Transactions__c/fields/Transaction_Status__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Status__c</fullName>
    <label>Transaction Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Unprocessed</fullName>
            </value>
            <value>
                <fullName>Initiated</fullName>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Failure</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

MODON MRE BPDEV/force-app/main/default/classes/DirectDebitPaymentResponseHelper.cls
/**********************************************************************************************************************
* Name               : DirectDebitPaymentResponseHelper                                                        
* Description        : Helper class for Payment process
* Usage              : Called from Trigger
* Created By         : Activeminds                                                     
* --------------------------------------------------------------------------------------------------------------------
* Version       Author                      Date            Comment                                                                       
* 1.0           Suresh         				22 Mar 2025     Initial Draft   
* 2.0           Suresh                      29 Nov 2025     DD Charge Status update
******************************************************************************************************************/
public class DirectDebitPaymentResponseHelper {
    
     public static void processResponsesBeforeUpdate(List<DirectDebit_Payment_Response__c> responses) {
         Set<String> uniqueNumbers = new Set<String>();
         Map<String, String> map_DDTransaction = new Map<String, String>();
         for (DirectDebit_Payment_Response__c res : responses) {
            if (String.isNotBlank(res.DDA_REF_NO__c)) {
                uniqueNumbers.add(res.DDA_REF_NO__c);               
            }
         }
        for (DirectDebit_Transactions__c txn : [
            SELECT Id, Payer_Identification__c, DirectDebit_Registration_Response__c, DDA_Unique_Number__c, Transaction_Status__c,
            Request_Type__c, SOInstallment__c FROM DirectDebit_Transactions__c
            WHERE Request_Type__c = 'Collection' and SOInstallment__c != '' and Transaction_Status__c = 'Initiated'
            and DDA_Unique_Number__c IN :uniqueNumbers
        ]) {
            if(!map_DDTransaction.containsKey(txn.DDA_Unique_Number__c)){
                map_DDTransaction.put(txn.DDA_Unique_Number__c, txn.id);
            }
        } 
        for (DirectDebit_Payment_Response__c res : responses) {
            if(res.DDA_REF_NO__c != '' && map_DDTransaction.containsKey(res.DDA_REF_NO__c)){
                res.DirectDebit_Transactions__c = map_DDTransaction.get(res.DDA_REF_NO__c);
            }
        }    
    } 
    
    public static void processResponses(List<DirectDebit_Payment_Response__c> responses) {
        Set<String> uniqueNumbers = new Set<String>();
        Map<String, DirectDebit_Payment_Response__c> responseByNumber = new Map<String, DirectDebit_Payment_Response__c>();
		List<DirectDebit_Transactions__c> transactionsToUpdate = new List<DirectDebit_Transactions__c>();
        
        for (DirectDebit_Payment_Response__c res : responses) {
            if(!String.isBlank(res.DDA_REF_NO__c)){
                uniqueNumbers.add(res.DDA_REF_NO__c);
                responseByNumber.put(res.DDA_REF_NO__c, res);
            }
        }
        
        if (uniqueNumbers.isEmpty()) return;
        
        for (DirectDebit_Transactions__c txn : [SELECT Id, Payer_Identification__c, DirectDebit_Registration_Response__c, 
                                                DDA_Unique_Number__c, Transaction_Status__c, Ack_Nack_Response__c, Transaction_Number__c, 
                                                Request_Type__c, SOInstallment__c, Rejection_Reason__c  
                                                FROM DirectDebit_Transactions__c
                                                WHERE Request_Type__c = 'Collection' and SOInstallment__c != '' 
                                                and Transaction_Status__c = 'Initiated'
                                                and DDA_Unique_Number__c IN :uniqueNumbers])
        {
            DirectDebit_Payment_Response__c res = responseByNumber.get(txn.DDA_Unique_Number__c);
            if(res != null){
               txn.Ack_Nack_Response__c = res.Status__c; 
               txn.Rejection_Reason__c = res.Reason__c; 
               if(res.Status__c == 'PAY'){
                  txn.Transaction_Status__c = 'Success';
                  txn.Transaction_Number__c = res.Ref_No__c; 
               } else {
                  txn.Transaction_Status__c = 'Failure';  
               }
               transactionsToUpdate.add(txn); 
            }            
        }
        
        if (!transactionsToUpdate.isEmpty()) {
            update transactionsToUpdate;
        }
    } 
}