MODON MRE BPDEV/force-app/main/default/objects/District__c/District__c.object-meta.xml
<CustomObject>
    <description>Object to store the District details in the inventory structure. This will be the second level object in the inventory hierarchy</description>
    <label>District</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>District Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>District</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

MODON MRE BPDEV/force-app/main/default/objects/PaymentPlan__c/PaymentPlan__c.object-meta.xml
<CustomObject>
    <description>Object to store the payment plan details</description>
    <label>Payment Plan</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Payment Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Plans</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

MODON MRE BPDEV/force-app/main/default/objects/PaymentPlan__c/fields/ExpiryDate__c.field-meta.xml
<CustomField>
    <fullName>ExpiryDate__c</fullName>
    <description>A field to store the expiration date of the payment plan</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Expiry Date</label>
    <type>Date</type>
</CustomField>

MODON MRE BPDEV/force-app/main/default/objects/PaymentPlan__c/fields/Is_Employee_Payment_Plan__c.field-meta.xml
<CustomField>
    <fullName>Is_Employee_Payment_Plan__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Employee Payment Plan</label>
    <type>Checkbox</type>
</CustomField>

MODON MRE BPDEV/force-app/main/default/objects/PaymentPlan__c/fields/Online_Sales__c.field-meta.xml
<CustomField>
    <fullName>Online_Sales__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Online Sales</label>
    <type>Checkbox</type>
</CustomField>

MODON MRE BPDEV/force-app/main/default/objects/PaymentPlan__c/fields/PaymentInstallment__c.field-meta.xml
<CustomField>
    <fullName>PaymentInstallment__c</fullName>
    <description>A field to store the sum of the installments in the plan</description>
    <label>Payment Installment %</label>
    <summarizedField>PaymentInstallements__c.Milestone__c</summarizedField>
    <summaryForeignKey>PaymentInstallements__c.PaymentInstallment__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

MODON MRE BPDEV/force-app/main/default/objects/PaymentPlan__c/fields/Phase__c.field-meta.xml
<CustomField>
    <fullName>Phase__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to its related phase</description>
    <label>Phase</label>
    <referenceTo>Phase__c</referenceTo>
    <relationshipLabel>Payment Plans</relationshipLabel>
    <relationshipName>Payment_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

MODON MRE BPDEV/force-app/main/default/objects/PaymentPlan__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to its related project</description>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Payment Plans</relationshipLabel>
    <relationshipName>Payment_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

MODON MRE BPDEV/force-app/main/default/objects/PaymentPlan__c/fields/StartDate__c.field-meta.xml
<CustomField>
    <fullName>StartDate__c</fullName>
    <description>A field to store the start date of the plan</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

MODON MRE BPDEV/force-app/main/default/objects/PaymentPlan__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>A field to store the status of the payment plan</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

MODON MRE BPDEV/force-app/main/default/objects/Phase__c/Phase__c.object-meta.xml
<CustomObject>
    <label>Phase</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Building/Section Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Phases</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

MODON MRE BPDEV/force-app/main/default/objects/Phase__c/fields/District__c.field-meta.xml
<CustomField>
    <fullName>District__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>District</label>
    <referenceTo>District__c</referenceTo>
    <relationshipLabel>Phases</relationshipLabel>
    <relationshipName>Phases</relationshipName>
    <type>Lookup</type>
</CustomField>

MODON MRE BPDEV/force-app/main/default/objects/Phase__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipName>BuildingsSections</relationshipName>
    <type>Lookup</type>
</CustomField>

MODON MRE BPDEV/force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <description>This custom object is part of inventory management to store the project details</description>
    <label>Project</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

MODON MRE BPDEV/force-app/main/default/objects/Project__c/fields/District__c.field-meta.xml
<CustomField>
    <fullName>District__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup relation field to District object.</description>
    <label>District</label>
    <referenceTo>District__c</referenceTo>
    <relationshipLabel>Projects</relationshipLabel>
    <relationshipName>Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

MODON MRE BPDEV/force-app/main/default/objects/Project__c/fields/Island_Name__c.field-meta.xml
<CustomField>
    <fullName>Island_Name__c</fullName>
    <formula>District__r.Island__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Island Name</label>
    <type>Text</type>
</CustomField>

MODON MRE BPDEV/force-app/main/default/classes/OIC_DPGProjectsAPIHelper.cls
/**********************************************************************************************************************
* Name               : OIC_DPGProjectsAPIHelper                                                        
* Description        : This class is used to fetch project details.
* Usage              : 
* Created By         : Activemindsit                                                     
* --------------------------------------------------------------------------------------------------------------------
* Version       Author                      Date            Comment                                                                       
* 1.0           Suresh   	                08 04 2025      Initial Draft       
* 1.1           Suresh   	                15 10 2025      phase added
* 1.2           Arvind                      02 Aug 2026      Is_Employee_Payment_Plan__c = False only show to DPG
***********************************************************************************************************************/
global class OIC_DPGProjectsAPIHelper {
    
    public static List<Project__c> getAllProjects(){
        List<Project__c> lst_Project = new List<Project__c>();
        try{
            lst_Project = [SELECT Id, Name, District__r.Name, Island_Name__c FROM Project__c ];            
        }catch(Exception exe){}
        return lst_Project;  
    }    
    public static List<PaymentPlan__c> getAllPaymentPlans(){
        List<PaymentPlan__c> lst_PaymentPlans = new List<PaymentPlan__c>();
        try{
            lst_PaymentPlans = [SELECT Id, Name, Status__c, PaymentInstallment__c, StartDate__c, ExpiryDate__c, 
                                Project__c, Phase__r.Name, Phase__r.Id, Phase__r.Project__c 
                                FROM PaymentPlan__c WHERE Status__c = 'Active' and Online_Sales__c = true and  Is_Employee_Payment_Plan__c = false and (Project__c != '' or Phase__c != '') ];
                        
        }catch(Exception exe){}
        return lst_PaymentPlans;
    } 
}