MODON MRE BPDEV/force-app/main/default/objects/Bucket__c/Bucket__c.object-meta.xml
<CustomObject>
    <label>Bucket</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Bucket Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Buckets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

MODON MRE BPDEV/force-app/main/default/objects/Bucket_Assignment__c/Bucket_Assignment__c.object-meta.xml
<CustomObject>
    <label>Bucket Assignment</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Bucket Assignment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bucket Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

MODON MRE BPDEV/force-app/main/default/objects/Bucket_Assignment__c/fields/Bucket__c.field-meta.xml
<CustomField>
    <fullName>Bucket__c</fullName>
    <label>Bucket</label>
    <referenceTo>Bucket__c</referenceTo>
    <relationshipLabel>Bucket Assignments</relationshipLabel>
    <relationshipName>Bucket_Assignments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

MODON MRE BPDEV/force-app/main/default/objects/Unit__c/Unit__c.object-meta.xml
<CustomObject>
    <description>This object is part of inventory management to store the unit details</description>
    <label>Unit</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Units</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

MODON MRE BPDEV/force-app/main/default/objects/Unit__c/fields/Bucket__c.field-meta.xml
<CustomField>
    <fullName>Bucket__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Bucket</label>
    <referenceTo>Bucket__c</referenceTo>
    <relationshipLabel>Units</relationshipLabel>
    <relationshipName>Units</relationshipName>
    <type>Lookup</type>
</CustomField>

MODON MRE BPDEV/force-app/main/default/classes/BucketAssignmentTriggerHelper.cls
/**********************************************************************************************************************
* Name               : BucketAssignmentTriggerHelper                                                        
* Description        : This class is helper for BucketAssignment trigger
* Usage              : Called from BucketAssignmentTriggerHandler
* Created By         :                                          
* --------------------------------------------------------------------------------------------------------------------
* Version       Author                              Date            Comment                                                                       
* 1.0                
******************************************************************************************************************/
public without sharing class BucketAssignmentTriggerHelper {
    public static void handleUnitSharing(List<Bucket_Assignment__c> newBAs) {
        set<Id> bucketIds = new set<Id>();
        for(Bucket_Assignment__c baObj : newBAs){
            bucketIds.add(baObj.Bucket__c);
        }
        Map<String, String> unitBucketMap = new Map<String, String>();
        for(Unit__c unitObj : [SELECT Id, Bucket__c FROM Unit__c WHERE Bucket__c IN :bucketIds]){
            unitBucketMap.put(unitObj.Id, unitObj.Bucket__c);
        }
        if(unitBucketMap != NULL && unitBucketMap.keySet().size() > 0){
            UnitTriggerHelper.handleUnitSharing(unitBucketMap, unitBucketMap);
        }
    }
}