MODON MRE BPDEV/force-app/main/default/objects/Allocation__c/Allocation__c.object-meta.xml
<CustomObject>
    <description>Object to store Allocation details</description>
    <label>Allocation</label>
    <nameField>
        <displayFormat>A-{00000}</displayFormat>
        <label>Allocation No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Allocations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

MODON MRE BPDEV/force-app/main/default/objects/Allocation__c/fields/AllocationAmount__c.field-meta.xml
<CustomField>
    <fullName>AllocationAmount__c</fullName>
    <description>A field to store allocation amount</description>
    <label>Allocation Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

MODON MRE BPDEV/force-app/main/default/objects/Allocation__c/fields/Invoice__c.field-meta.xml
<CustomField>
    <fullName>Invoice__c</fullName>
    <description>An Invoice lookup to link between an Invoice and an Allocation</description>
    <label>Invoice</label>
    <referenceTo>Invoice__c</referenceTo>
    <relationshipLabel>Allocations</relationshipLabel>
    <relationshipName>Allocations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

MODON MRE BPDEV/force-app/main/default/objects/Expressionofinterest__c/Expressionofinterest__c.object-meta.xml
<CustomObject>
    <description>Object to store Expression of Interest details (Potential buyer details)</description>
    <label>Expression of Interest</label>
    <nameField>
        <displayFormat>EOI-{0000}</displayFormat>
        <label>EOI Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Expression of Interests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

MODON MRE BPDEV/force-app/main/default/objects/Expressionofinterest__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Expression of Interests</relationshipLabel>
    <relationshipName>Expression_of_Interests</relationshipName>
    <type>Lookup</type>
</CustomField>

MODON MRE BPDEV/force-app/main/default/objects/Expressionofinterest__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <description>Object to store the related opportunity which comes from a Lead</description>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Expression of Interests</relationshipLabel>
    <relationshipName>Expression_of_interests</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

MODON MRE BPDEV/force-app/main/default/objects/Expressionofinterest__c/fields/Source_Entity__c.field-meta.xml
<CustomField>
    <fullName>Source_Entity__c</fullName>
    <description>Field for Modon Egypt</description>
    <formula>TEXT(Opportunity__r.Source_Entity__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Source Entity</label>
    <type>Text</type>
</CustomField>

MODON MRE BPDEV/force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <description>Object to store Invoice details, such as amounts &amp; transactions details</description>
    <label>Invoice</label>
    <nameField>
        <displayFormat>IN-{00000}</displayFormat>
        <label>Invoice  No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

MODON MRE BPDEV/force-app/main/default/objects/Invoice__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>A field to link with the related account of the invoice</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

MODON MRE BPDEV/force-app/main/default/objects/Invoice__c/fields/AppliedAmount__c.field-meta.xml
<CustomField>
    <fullName>AppliedAmount__c</fullName>
    <description>A field to store the total applied amount and is taken from related Allocation amount</description>
    <label>Applied Amount</label>
    <summarizedField>Allocation__c.AllocationAmount__c</summarizedField>
    <summaryFilterItems>
        <field>Allocation__c.Status__c</field>
        <operation>equals</operation>
        <value>Applied</value>
    </summaryFilterItems>
    <summaryForeignKey>Allocation__c.Invoice__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

MODON MRE BPDEV/force-app/main/default/objects/Invoice__c/fields/Expressionofinterest__c.field-meta.xml
<CustomField>
    <fullName>Expressionofinterest__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>A field to store the related EOI that is the invoice applied on</description>
    <label>Expression of interest</label>
    <referenceTo>Expressionofinterest__c</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

MODON MRE BPDEV/force-app/main/default/objects/Invoice__c/fields/InvoiceAmount__c.field-meta.xml
<CustomField>
    <fullName>InvoiceAmount__c</fullName>
    <description>A field to store the amount of the Invoice</description>
    <label>Invoice Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

MODON MRE BPDEV/force-app/main/default/objects/Opportunity/fields/Source_Entity__c.field-meta.xml
<CustomField>
    <fullName>Source_Entity__c</fullName>
    <description>Field for Modon Egypt</description>
    <label>Source Entity</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Modon - Egypt</fullName>
            </value>
            <value>
                <fullName>Modon - UAE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

MODON MRE BPDEV/force-app/main/default/classes/SubmitEOIEgyptControllerTest.cls
@isTest
public class SubmitEOIEgyptControllerTest {

    @isTest 
    static void myTestMethod(){
        
        Account acc = new Account();
        acc.name = 'test acc';
        insert acc;
        
        Opportunity oppObj = new Opportunity();
        oppObj.Name = 'Test opportunity';
        oppObj.StageName = 'Discussion In Progress';
        oppObj.CloseDate = System.Today();
        //oppObj.Account = acc.Id;
        oppObj.Source_Entity__c = 'Modon - Egypt';
        INSERT oppObj;
        
        Expressionofinterest__c eoiObj = new Expressionofinterest__c();
        eoiObj.Opportunity__c = oppObj.Id;
        INSERT eoiObj;

        Invoice__c inv = new Invoice__c();
        inv.Account__c = acc.Id;
        inv.Expressionofinterest__c = eoiObj.Id;
        inv.InvoiceAmount__c  =100;
        //inv.AppliedAmount__c = 100;
        insert inv;
        
         Allocation__c alloc = new Allocation__c();
        alloc.AllocationAmount__c = 100;
        alloc.Invoice__c = inv.Id;
        
        SubmitEOIEgyptController.RequestWrap reqWrap = new SubmitEOIEgyptController.RequestWrap();
        reqWrap.eoiId = eoiObj.Id;
        
        Test.startTest();
            // Check submission eligibility
            SubmitEOIEgyptController.RespondWrap resp = SubmitEOIEgyptController.eoiSubmissionCheck(eoiObj.Id);
            System.debug(resp.result);
            // Submit the EOI
        	SubmitEOIEgyptController.submitEoi(JSON.serialize(reqWrap));
        Test.stopTest();
        System.assertEquals('Please upload the required signed documents: KYC and Wealth Form', resp.result, 'Validation Message');
    }
}