MODON MRE BPDEV/force-app/main/default/objects/Account/fields/Account_Manager__c.field-meta.xml
<CustomField>
    <fullName>Account_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

MODON MRE BPDEV/force-app/main/default/objects/Account/fields/CustomerType__c.field-meta.xml
<CustomField>
    <fullName>CustomerType__c</fullName>
    <label>Customer Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New Client</fullName>
                <default>true</default>
                <label>New Client</label>
            </value>
            <value>
                <fullName>VIP Client</fullName>
            </value>
            <value>
                <fullName>VVIP Client</fullName>
            </value>
            <value>
                <fullName>Non-Profit Organisation eg. Charity/ Donations Organization (UAE / Non UAE based)</fullName>
            </value>
            <value>
                <fullName>Money Value Transfer Services eg. Currency exchange, Virtual or Digital Asset Exchange (UAE / Non UAE based)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

MODON MRE BPDEV/force-app/main/default/objects/Case/fields/Channel__c.field-meta.xml
<CustomField>
    <fullName>Channel__c</fullName>
    <label>Channel</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>800 Modon</fullName>
            </value>
            <value>
                <fullName>Direct Email</fullName>
            </value>
            <value>
                <fullName>Internal Apps</fullName>
            </value>
            <value>
                <fullName>Social</fullName>
            </value>
            <value>
                <fullName>Walk In</fullName>
            </value>
            <value>
                <fullName>Websites</fullName>
            </value>
            <value>
                <fullName>Broker</fullName>
                <isActive>false</isActive>
                <label>Broker</label>
            </value>
            <value>
                <fullName>Broker Portal</fullName>
                <isActive>false</isActive>
                <label>Broker Portal</label>
            </value>
            <value>
                <fullName>Customer Portal</fullName>
                <isActive>false</isActive>
                <label>Customer Portal</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

MODON MRE BPDEV/force-app/main/default/objects/Case/fields/Source__c.field-meta.xml
<CustomField>
    <fullName>Source__c</fullName>
    <label>Source</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Channel__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>800 Modon</fullName>
            </value>
            <value>
                <fullName>Broker Portal</fullName>
            </value>
            <value>
                <fullName>Customer Care</fullName>
            </value>
            <value>
                <fullName>Customer Centre</fullName>
            </value>
            <value>
                <fullName>Customer Portal</fullName>
            </value>
            <value>
                <fullName>Instagram</fullName>
            </value>
            <value>
                <fullName>Internal</fullName>
            </value>
            <value>
                <fullName>Meta</fullName>
            </value>
            <value>
                <fullName>Modon.com</fullName>
            </value>
            <value>
                <fullName>Sales Centre</fullName>
            </value>
            <value>
                <fullName>Salesforce</fullName>
            </value>
            <value>
                <fullName>Snapchat</fullName>
            </value>
            <value>
                <fullName>Twitter</fullName>
            </value>
            <value>
                <fullName>WhatsApp</fullName>
            </value>
            <value>
                <fullName>Youtube</fullName>
            </value>
            <value>
                <fullName>Social Media</fullName>
                <isActive>false</isActive>
                <label>Social Media</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

MODON MRE BPDEV/force-app/main/default/objects/Case/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unit</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>$Source.AccountId</field>
            <operation>equals</operation>
            <valueField>Unit__c.Opportunity__r.AccountId</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Unit__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

MODON MRE BPDEV/force-app/main/default/objects/Case/recordTypes/Standard.recordType-meta.xml
<RecordType>
    <fullName>Standard</fullName>
    <active>true</active>
    <businessProcess>Case Module For Broker Management</businessProcess>
    <description>Standard Record Type for Call Centre Team</description>
    <label>Standard</label>
</RecordType>

MODON MRE BPDEV/force-app/main/default/objects/Opportunity/fields/CustomerType__c.field-meta.xml
<CustomField>
    <fullName>CustomerType__c</fullName>
    <label>Customer Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New Client</fullName>
            </value>
            <value>
                <fullName>VIP Client</fullName>
            </value>
            <value>
                <fullName>VVIP Client</fullName>
            </value>
            <value>
                <fullName>Existing Client</fullName>
                <isActive>false</isActive>
                <label>Existing Client</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

MODON MRE BPDEV/force-app/main/default/objects/Opportunity/fields/Source_Entity__c.field-meta.xml
<CustomField>
    <fullName>Source_Entity__c</fullName>
    <description>Field for Modon Egypt</description>
    <label>Source Entity</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Modon - Egypt</fullName>
            </value>
            <value>
                <fullName>Modon - UAE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

MODON MRE BPDEV/force-app/main/default/objects/Opportunity/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Resale SR</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

MODON MRE BPDEV/force-app/main/default/objects/Opportunity/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unit</label>
    <referenceTo>Unit__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

MODON MRE BPDEV/force-app/main/default/objects/Unit__c/Unit__c.object-meta.xml
<CustomObject>
    <description>This object is part of inventory management to store the unit details</description>
    <label>Unit</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Units</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

MODON MRE BPDEV/force-app/main/default/objects/Unit__c/fields/Number_of_Bedrooms__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Bedrooms__c</fullName>
    <label>Number of Bedrooms</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>0</fullName>
            </value>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>5 Plus</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>11</fullName>
                <isActive>false</isActive>
                <label>11</label>
            </value>
            <value>
                <fullName>49</fullName>
                <isActive>false</isActive>
                <label>49</label>
            </value>
            <value>
                <fullName>99</fullName>
                <isActive>false</isActive>
                <label>99</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

MODON MRE BPDEV/force-app/main/default/objects/Unit__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Units</relationshipLabel>
    <relationshipName>Units</relationshipName>
    <type>Lookup</type>
</CustomField>

MODON MRE BPDEV/force-app/main/default/objects/Unit__c/fields/PlotNo__c.field-meta.xml
<CustomField>
    <fullName>PlotNo__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Plot No</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

MODON MRE BPDEV/force-app/main/default/objects/Unit__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Unit Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Available</fullName>
            </value>
            <value>
                <fullName>Sold</fullName>
            </value>
            <value>
                <fullName>CCMD</fullName>
            </value>
            <value>
                <fullName>Reserved</fullName>
            </value>
            <value>
                <fullName>UnReleased</fullName>
            </value>
            <value>
                <fullName>Blocked</fullName>
                <isActive>false</isActive>
                <label>Blocked</label>
            </value>
            <value>
                <fullName>Booked</fullName>
                <isActive>false</isActive>
                <label>Booked</label>
            </value>
            <value>
                <fullName>Booking cancelled</fullName>
                <isActive>false</isActive>
                <label>Booking cancelled</label>
            </value>
            <value>
                <fullName>Booking confirmed</fullName>
                <isActive>false</isActive>
                <label>Booking confirmed</label>
            </value>
            <value>
                <fullName>Booking in progress</fullName>
                <isActive>false</isActive>
                <label>Booking in progress</label>
            </value>
            <value>
                <fullName>Draft</fullName>
                <isActive>false</isActive>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Leased</fullName>
                <isActive>false</isActive>
                <label>Leased</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

MODON MRE BPDEV/force-app/main/default/objects/Unit__c/fields/UnitClassification__c.field-meta.xml
<CustomField>
    <fullName>UnitClassification__c</fullName>
    <label>Unit Classification</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Villa</fullName>
            </value>
            <value>
                <fullName>Apartment</fullName>
            </value>
            <value>
                <fullName>Townhouse</fullName>
            </value>
            <value>
                <fullName>Plot</fullName>
            </value>
            <value>
                <fullName>Duplex</fullName>
            </value>
            <value>
                <fullName>Mansion</fullName>
            </value>
            <value>
                <fullName>Mega Mansion</fullName>
            </value>
            <value>
                <fullName>Show Villa</fullName>
                <isActive>false</isActive>
                <label>Show Villa</label>
            </value>
            <value>
                <fullName>Townhouse - End Unit</fullName>
                <isActive>false</isActive>
                <label>Townhouse - End Unit</label>
            </value>
            <value>
                <fullName>Townhouse - Mid Unit</fullName>
                <isActive>false</isActive>
                <label>Townhouse - Mid Unit</label>
            </value>
            <value>
                <fullName>Triplex</fullName>
                <isActive>false</isActive>
                <label>Triplex</label>
            </value>
            <value>
                <fullName>Villa/Townhouse</fullName>
                <isActive>false</isActive>
                <label>Villa/Townhouse</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

MODON MRE BPDEV/force-app/main/default/classes/sendRequestXiboCaseTest.cls
/**********************************************************************************************************************
* Name               : sendRequestXiboCaseTest                                                                : 
* Created By         : Active Minds Global Solutions Pvt Ltd                                                     
* --------------------------------------------------------------------------------------------------------------------
* Version       Author                                      Date            Comment                                                                       
* 1.0           Raghu.Gajjela@activemindsit.com      		29 Jan 2025     Initial Draft  
* 2.0           ravikumar.pasumarthi@activemindsit.com      20 Jan 2026     Changes as per Case Mgmt 2.0
******************************************************************************************************************/
@isTest
public class sendRequestXiboCaseTest {
    
    private static string testCategory = 'Customer Care';
    
    public class MockHttpResponseGenerator implements HttpCalloutMock {
        public HttpResponse respond(HTTPRequest req) {
            HttpResponse res = new HttpResponse();
            res.setHeader('Content-Type', 'application/json');
            res.setBody('{"data":[{"message":"Survey created: https://survey-link.com/form/123"}]}');
            res.setStatusCode(200);
            return res;
        }
    }
    
    public class MockHttpFailureResponseGenerator implements HttpCalloutMock {
        public HttpResponse respond(HTTPRequest req) {
            HttpResponse res = new HttpResponse();
            res.setStatusCode(401);
            res.setBody('{"error": "Unauthorized"}');
            return res;
        }
    }
    
    @isTest
    static void testCallCaseXIboService_success() {
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());
        
        Map<String, Id> testData = TestDataFactory.createTestData();
        Id mgrId = testData.get('FrontLinerUser1');
        Id testAccountId = testData.get('vipOrganizationAccount');
        Id testContactId = testData.get('vipOrganizationcontact');
        
        Account vipAccount = new Account(
            Name = 'VIP Account',
            CustomerType__c = 'VIP Client',
            Source_Entity__c = 'Modon - Egypt',
            RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Organization Account').getRecordTypeId(),
            Account_Manager__c = mgrId
        );
        insert vipAccount;

        Opportunity opp = new Opportunity(
            Name = 'VIP Opportunity',
            StageName = 'Discussion In Progress',
            CloseDate = System.Today(),
			AccountId =  vipAccount.Id           
        );
        insert opp;

        Unit__c unit = new Unit__c(Name = 'Error Unit', PlotNo__c = '90/B', UnitClassification__c = 'Apartment', Number_of_Bedrooms__c = '3', Opportunity__c = opp.Id, Status__c = 'Reserved');
        insert unit;
        
        Case testCase = new Case(
            AccountId = testAccountId,
            ContactId = testContactId,
            Status = 'New',
            Subject = 'Test Case',
            Description = 'Test Description',
            channel__c = '800 Modon',
            source__c = '800 Modon',
            Unit__c = unit.Id,
            RecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Standard').getRecordTypeId(),
            CaseCategory__c = testCategory,
            Resolution_Comments__c = 'Closed with resolution'
        );
        insert testCase;
        
        Test.startTest();
        sendRequestXiboCase.callCaseXIboService(new Set<String>{testCase.Id});
        Test.stopTest();
        
        //Case updatedCase = [SELECT SurveyLink__c FROM Case WHERE Id = :testCase.Id limit 1];
    }
    
    @isTest
    static void testCallCaseXIboService_errorResponse() {
        Test.setMock(HttpCalloutMock.class, new MockHttpFailureResponseGenerator());
        
        Map<String, Id> testData = TestDataFactory.createTestData();
        Id mgrId = testData.get('FrontLinerUser1');
        Id testAccountId = testData.get('vipOrganizationAccount');
        Id testContactId = testData.get('vipOrganizationcontact');
        
        Account vipAccount = new Account(
            Name = 'VIP Account',
            CustomerType__c = 'VIP Client',
            Source_Entity__c = 'Modon - Egypt',
            RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Organization Account').getRecordTypeId(),
            Account_Manager__c = mgrId
        );
        insert vipAccount;
        
        Opportunity opp = new Opportunity(
            Name = 'VIP Opportunity',
            StageName = 'Discussion In Progress',
            CloseDate = System.Today(),
			AccountId =  vipAccount.Id           
        );
        insert opp;
        
        Unit__c unit = new Unit__c(Name = 'Error Unit', PlotNo__c = '90/B', UnitClassification__c = 'Apartment', Number_of_Bedrooms__c = '3', Opportunity__c = opp.Id, Status__c = 'Reserved');
        insert unit;
                
        Case testCase = new Case(
            AccountId = testAccountId,
            ContactId = testContactId,
            channel__c = '800 Modon',
            source__c = '800 Modon',
            Status = 'New',
            Subject = 'Test Case',
            Description = 'Test Description',
            Unit__c = unit.Id,
            RecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Standard').getRecordTypeId(),
            CaseCategory__c = testCategory,
            Resolution_Comments__c = 'Closed with resolution'
        );
        insert testCase;
        
        Test.startTest();
        sendRequestXiboCase.callCaseXIboService(new Set<String>{testCase.Id});
        Test.stopTest();
    }
}