MODON MRE BPDEV/force-app/main/default/objects/Account/fields/Agency_Status__c.field-meta.xml
<CustomField>
    <fullName>Agency_Status__c</fullName>
    <label>Agency Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending Verification</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>In Active</fullName>
            </value>
            <value>
                <fullName>Blocked</fullName>
            </value>
            <value>
                <fullName>Suspended</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

MODON MRE BPDEV/force-app/main/default/objects/Account/fields/OIC_SUPPLIER_ADDRESS_ID__c.field-meta.xml
<CustomField>
    <fullName>OIC_SUPPLIER_ADDRESS_ID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>OIC SUPPLIER ADDRESS ID</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

MODON MRE BPDEV/force-app/main/default/objects/Account/fields/OIC_SUPPLIER_NUMBER__c.field-meta.xml
<CustomField>
    <fullName>OIC_SUPPLIER_NUMBER__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>OIC SUPPLIER NUMBER</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

MODON MRE BPDEV/force-app/main/default/objects/Account/fields/OIC_Supplier_Response__c.field-meta.xml
<CustomField>
    <fullName>OIC_Supplier_Response__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>OIC Supplier Response</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

MODON MRE BPDEV/force-app/main/default/objects/Account/fields/OIC_SUPPLIER_SITE_ID__c.field-meta.xml
<CustomField>
    <fullName>OIC_SUPPLIER_SITE_ID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>OIC SUPPLIER SITE ID</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

MODON MRE BPDEV/force-app/main/default/classes/MBP_OracleSupplierSyncQueueableTest.cls
@IsTest
public class MBP_OracleSupplierSyncQueueableTest {

    @TestSetup
    static void setupData() {

        Account acc = new Account(
            Name = 'Queueable Supplier',
            Agency_Status__c = 'Active',
            BillingStreet = 'Street Q',
            BillingCity = 'Dubai',
            BillingCountry = 'United Arab Emirates'
        );
        insert acc;
    }

    @IsTest
    static void testQueueableSuccess() {

        List<Account> accList = [
            SELECT Id, Name, Agency_Status__c,
                   BillingStreet, BillingCity, BillingCountry
            FROM Account
            LIMIT 1
        ];

        Test.setMock(HttpCalloutMock.class, new MBP_OracleCalloutMockTest());

        Test.startTest();
        System.enqueueJob(
            new MBP_OracleSupplierSyncQueueable(accList,0)
        );
        Test.stopTest();

        Account updatedAcc = [
            SELECT OIC_Supplier_Sync_Status__c,
                   OIC_Supplier_Vendor_ID__c,
                   OIC_Supplier_Party_ID__c,
                   OIC_SUPPLIER_NUMBER__c,
                   OIC_Supplier_Address_ID__c,
                   OIC_Supplier_Site_ID__c,
                   OIC_Supplier_Response__c
            FROM Account
            WHERE Id = :accList[0].Id
        ];

    }
}