MODON MRE BPDEV/force-app/main/default/objects/Account/fields/Customer_Segemnt_Group__c.field-meta.xml
<CustomField>
    <fullName>Customer_Segemnt_Group__c</fullName>
    <formula>IF(
    OR(
        Customer_Segmentation__c = &quot;Premier&quot;,
        Customer_Segmentation__c = &quot;Privilege&quot;,
        Customer_Segmentation__c = &quot;Prestige&quot;
    ),
    &quot;Signature&quot;,
    
    IF(
        OR(
            Customer_Segmentation__c = &quot;Executive&quot;,
            Customer_Segmentation__c = &quot;Exclusive&quot;
        ),
        &quot;Elite&quot;,
        &quot;&quot;
    )
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Customer Segment Group</label>
    <type>Text</type>
</CustomField>

MODON MRE BPDEV/force-app/main/default/objects/Account/fields/Isduplicate__c.field-meta.xml
<CustomField>
    <fullName>Isduplicate__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Isduplicate</label>
    <type>Checkbox</type>
</CustomField>

MODON MRE BPDEV/force-app/main/default/objects/Contact/fields/EIDNumber__c.field-meta.xml
<CustomField>
    <fullName>EIDNumber__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Emirates ID Number</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

MODON MRE BPDEV/force-app/main/default/objects/Documents__c/Documents__c.object-meta.xml
<CustomObject>
    <description>Object to store custom document details (Document placeholder)</description>
    <label>Document</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Document Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Documents</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

MODON MRE BPDEV/force-app/main/default/objects/Documents__c/fields/JO2__c.field-meta.xml
<CustomField>
    <fullName>JO2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>JO2</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Documents</relationshipLabel>
    <relationshipName>JO2</relationshipName>
    <type>Lookup</type>
</CustomField>

MODON MRE BPDEV/force-app/main/default/objects/Documents__c/fields/SalesOrder__c.field-meta.xml
<CustomField>
    <fullName>SalesOrder__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Order</label>
    <referenceTo>SalesOrder__c</referenceTo>
    <relationshipLabel>Documents</relationshipLabel>
    <relationshipName>Documents</relationshipName>
    <type>Lookup</type>
</CustomField>

MODON MRE BPDEV/force-app/main/default/objects/Documents__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>A field to store the document status</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending Upload</fullName>
                <default>true</default>
                <label>Pending Upload</label>
            </value>
            <value>
                <fullName>Uploaded</fullName>
            </value>
            <value>
                <fullName>Generated</fullName>
            </value>
            <value>
                <fullName>Signed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

MODON MRE BPDEV/force-app/main/default/objects/Documents__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unit</label>
    <referenceTo>Unit__c</referenceTo>
    <relationshipLabel>Documents</relationshipLabel>
    <relationshipName>Documents</relationshipName>
    <type>Lookup</type>
</CustomField>

MODON MRE BPDEV/force-app/main/default/objects/SalesOrder__c/SalesOrder__c.object-meta.xml
<CustomObject>
    <label>Sales Order</label>
    <nameField>
        <displayFormat>SO-{00000}</displayFormat>
        <label>Sales Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

MODON MRE BPDEV/force-app/main/default/objects/SalesOrder__c/fields/CustomerAccount__c.field-meta.xml
<CustomField>
    <fullName>CustomerAccount__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Sales Orders</relationshipLabel>
    <relationshipName>Sales_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

MODON MRE BPDEV/force-app/main/default/objects/SalesOrder__c/fields/JO1__c.field-meta.xml
<CustomField>
    <fullName>JO1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>JO1</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Sales Orders (JO1)</relationshipLabel>
    <relationshipName>JO1</relationshipName>
    <type>Lookup</type>
</CustomField>

MODON MRE BPDEV/force-app/main/default/objects/SalesOrder__c/fields/JO2__c.field-meta.xml
<CustomField>
    <fullName>JO2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>JO2</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Sales Orders (JO2)</relationshipLabel>
    <relationshipName>JO_2</relationshipName>
    <type>Lookup</type>
</CustomField>

MODON MRE BPDEV/force-app/main/default/objects/SalesOrder__c/fields/JO3__c.field-meta.xml
<CustomField>
    <fullName>JO3__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>JO3</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Sales Orders (JO3)</relationshipLabel>
    <relationshipName>JO3</relationshipName>
    <type>Lookup</type>
</CustomField>

MODON MRE BPDEV/force-app/main/default/objects/SalesOrder__c/fields/JO4__c.field-meta.xml
<CustomField>
    <fullName>JO4__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>JO4</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Sales Orders (JO4)</relationshipLabel>
    <relationshipName>JO4</relationshipName>
    <type>Lookup</type>
</CustomField>

MODON MRE BPDEV/force-app/main/default/objects/SalesOrder__c/fields/JO5__c.field-meta.xml
<CustomField>
    <fullName>JO5__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>JO5</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Sales Orders (JO5)</relationshipLabel>
    <relationshipName>JO5</relationshipName>
    <type>Lookup</type>
</CustomField>

MODON MRE BPDEV/force-app/main/default/objects/SalesOrder__c/fields/JO6__c.field-meta.xml
<CustomField>
    <fullName>JO6__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>JO6</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Sales Orders (JO6)</relationshipLabel>
    <relationshipName>JO6</relationshipName>
    <type>Lookup</type>
</CustomField>

MODON MRE BPDEV/force-app/main/default/objects/SalesOrder__c/fields/ProjectName__c.field-meta.xml
<CustomField>
    <fullName>ProjectName__c</fullName>
    <formula>Unit__r.Phase__r.Project__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Project Name</label>
    <type>Text</type>
</CustomField>

MODON MRE BPDEV/force-app/main/default/objects/SalesOrder__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Reservation form generated</fullName>
            </value>
            <value>
                <fullName>Down payment collected</fullName>
            </value>
            <value>
                <fullName>Reservation form signed</fullName>
            </value>
            <value>
                <fullName>Installment Payment Collected</fullName>
            </value>
            <value>
                <fullName>DP Payment Confirmed</fullName>
            </value>
            <value>
                <fullName>SPA Generated</fullName>
            </value>
            <value>
                <fullName>SPA Signed (Customer)</fullName>
            </value>
            <value>
                <fullName>SPA Signed (Modon)</fullName>
            </value>
            <value>
                <fullName>SPA Delivered</fullName>
            </value>
            <value>
                <fullName>Sold</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>System cancelled</fullName>
            </value>
            <value>
                <fullName>KYC - In progress</fullName>
            </value>
            <value>
                <fullName>KYC - Completed / KYC Rejected</fullName>
            </value>
            <value>
                <fullName>Payments Collected</fullName>
            </value>
            <value>
                <fullName>Downpayment Payments Cleared</fullName>
            </value>
            <value>
                <fullName>SPA Sent to customer</fullName>
            </value>
            <value>
                <fullName>SPA Validated</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Cancelled SR</fullName>
            </value>
            <value>
                <fullName>Voided</fullName>
            </value>
            <value>
                <fullName>Pending Blocking Fees</fullName>
            </value>
            <value>
                <fullName>Blocking Fees Collected</fullName>
            </value>
            <value>
                <fullName>Property Transfer Cancelled - SR</fullName>
            </value>
            <value>
                <fullName>Unit Swap Cancelled - SR</fullName>
            </value>
            <value>
                <fullName>Unit Upgrade Cancelled - SR</fullName>
            </value>
            <value>
                <fullName>Unit Cancellation Cancelled - SR</fullName>
            </value>
            <value>
                <fullName>Unit Consolidation Cancelled - SR</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

MODON MRE BPDEV/force-app/main/default/objects/SalesOrder__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unit</label>
    <referenceTo>Unit__c</referenceTo>
    <relationshipLabel>Sales Orders</relationshipLabel>
    <relationshipName>Sales_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

MODON MRE BPDEV/force-app/main/default/objects/Unit__c/Unit__c.object-meta.xml
<CustomObject>
    <description>This object is part of inventory management to store the unit details</description>
    <label>Unit</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Units</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

MODON MRE BPDEV/force-app/main/default/objects/Unit__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Unit Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Available</fullName>
            </value>
            <value>
                <fullName>Sold</fullName>
            </value>
            <value>
                <fullName>CCMD</fullName>
            </value>
            <value>
                <fullName>Reserved</fullName>
            </value>
            <value>
                <fullName>UnReleased</fullName>
            </value>
            <value>
                <fullName>Blocked</fullName>
                <isActive>false</isActive>
                <label>Blocked</label>
            </value>
            <value>
                <fullName>Booked</fullName>
                <isActive>false</isActive>
                <label>Booked</label>
            </value>
            <value>
                <fullName>Booking cancelled</fullName>
                <isActive>false</isActive>
                <label>Booking cancelled</label>
            </value>
            <value>
                <fullName>Booking confirmed</fullName>
                <isActive>false</isActive>
                <label>Booking confirmed</label>
            </value>
            <value>
                <fullName>Booking in progress</fullName>
                <isActive>false</isActive>
                <label>Booking in progress</label>
            </value>
            <value>
                <fullName>Draft</fullName>
                <isActive>false</isActive>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Leased</fullName>
                <isActive>false</isActive>
                <label>Leased</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

MODON MRE BPDEV/force-app/main/default/objects/User/fields/EmailBase64String__c.field-meta.xml
<CustomField>
    <fullName>EmailBase64String__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>EmailBase64String</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

MODON MRE BPDEV/force-app/main/default/objects/User/fields/EmiratesIDNumber__c.field-meta.xml
<CustomField>
    <fullName>EmiratesIDNumber__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Emirates ID Number</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

MODON MRE BPDEV/force-app/main/default/classes/onBoardingCustomer.cls
/**
* @description       : Community/Portal user On bording
* @author            : Manoj
* @last modified on  : 02-23-2026
* @last modified by  : Manoj
* --------------------------------------------------------------------------------------------------------------------
* Version       Author              Date                Comment
* 1.0           Manoj   	        13 Oct 2025   		Initial Draft 
* 2.0           Manoj   	        09 Dec 2025   		Remove logic 
* 3.0			Manoj				10 Jan 2026			Add SOQL and update other filters
														Communication Matrix
* 4.0			Manoj				13 Jan 2026			Add Bypass the email trigger filters
* 5.0           Manoj				28 Feb 2026			Add creating JOIN owner logic is add  Update the filters for Customer Segemnt and Joint Owner user creation alos
* 6.0 			Manoj				10 Mar 2026			Add All joint owners and error for logic		
-------------------------------------------------------------------------------------------------------------------------**/
global class onBoardingCustomer implements Database.Batchable<SObject>,Database.AllowsCallouts {
    global Database.QueryLocator start(Database.BatchableContext bc) {  
        //3.0 add the Record Type
        list<string> accRecordTypeName =new list<string>();
        accRecordTypeName.add('Person Account');
        accRecordTypeName.add('Organization Account');
        //5.0 Add the Joint Owner 
        string Qry ='select id,CustomerAccount__c,CustomerAccount__r.name,CustomerAccount__r.RecordType.name,Status__c,Unit__c,CustomerAccount__r.IsCustomerPortal,JO1__c,JO1__r.AccountId, JO1__r.Account.IsCustomerPortal,JO2__c,JO2__r.Account.IsCustomerPortal,JO2__r.AccountId, JO3__c,JO3__r.AccountId,JO3__r.Account.IsCustomerPortal,JO4__c,JO4__r.AccountId, JO4__r.Account.IsCustomerPortal,JO5__c,JO5__r.AccountId, JO5__r.Account.IsCustomerPortal,JO6__c,JO6__r.AccountId, JO6__r.Account.IsCustomerPortal from SalesOrder__c where  CustomerAccount__r.RecordType.name IN :accRecordTypeName';
        string SalesOrderIdsLable = System.Label.CPSalesOrderIds;
        string CustomerSegment = System.Label.CustomerSegment;
        string CustomerSegmentGroup = System.Label.CustomerSegmentGroup;
        list<id> SalesOrderIds=new list<id>();
        if(SalesOrderIdsLable.contains(',')){
            system.debug('22---'+SalesOrderIdsLable);
            SalesOrderIds = SalesOrderIdsLable.split(',');
        }else{
            system.debug('26---'+SalesOrderIdsLable);
            if(!SalesOrderIdsLable.contains('null') ){
                SalesOrderIds =new List<String>{SalesOrderIdsLable};
            }
        }   
        list<string> statusValues =new List<string>();
        string statusValuesLables = System.Label.CPSOStatus;
        
        if(statusValuesLables.contains(',')){
            system.debug('22---'+statusValuesLables);
            statusValues = statusValuesLables.split(',');
        }else{
            system.debug('26---'+statusValuesLables);
            if(!statusValuesLables.contains('null') ){
                statusValues =new List<String>{statusValuesLables};
        	}
        }
        if(statusValues != null){ //3.0 and 5.0 update Where logic 
            qry +=' AND Status__c IN :statusValues';
        }//3.0 Start add the Project filters
        string MIREExcludelst = System.Label.MIRE_Exclude_List;
        list<string> projectFilter =new list<string>();
        
        for (String c2 : MIREExcludelst.split(',')) {
            if (c2 != null && c2.contains('^')) {
                projectFilter.add(c2.replace('^', ',').trim());
            } else {
                projectFilter.add(c2.trim());
            }
        }   //3.0 End
        if(projectFilter != null){
            qry += ' AND ProjectName__c  NOt IN : projectFilter';
        }
        system.debug('SalesOrderIds----'+SalesOrderIds);
        if( SalesOrderIds.size() > 0 ){            
            qry +=' AND CustomerAccount__c = :SalesOrderIds ';
        }
        system.debug('qry----'+qry);
        If(!CustomerSegment.contains('null')){ //5.0 Add the Customer Segemnt 
            
            qry +=' AND CustomerAccount__r.Customer_Segemnt_Group__c =: CustomerSegmentGroup  AND CustomerAccount__r.Customer_Segmentation__c = :CustomerSegment and CustomerAccount__r.Isduplicate__c = false';
        }
        
        if(Test.isRunningTest()){
            return Database.getQueryLocator([
                SELECT Id, CustomerAccount__c, CustomerAccount__r.Name, CustomerAccount__r.RecordType.Name, Status__c, Unit__c, CustomerAccount__r.IsCustomerPortal, JO1__c, JO1__r.AccountId, JO1__r.Account.IsCustomerPortal, JO2__c, JO2__r.Account.IsCustomerPortal, JO2__r.AccountId, JO3__c, JO3__r.AccountId, JO3__r.Account.IsCustomerPortal, JO4__c, JO4__r.AccountId, JO4__r.Account.IsCustomerPortal, JO5__c, JO5__r.AccountId, JO5__r.Account.IsCustomerPortal, JO6__c, JO6__r.AccountId, JO6__r.Account.IsCustomerPortal FROM SalesOrder__c LIMIT 1
            ]);
        }
        
        system.debug('44-- '+qry);
        return Database.getQueryLocator(qry);        
        
    }
    global void execute(Database.BatchableContext bc, List<SalesOrder__c> scope) {
        system.debug('executeMethod==========');
        //3.0 add only Active User 
        set<id> newCPAccountids=new set<id>();         
        for(SalesOrder__c recSo : scope){
            //5.0  start Add the Joint Owner
            //6.0 Add All joint owners
                if(recSo.CustomerAccount__r.IsCustomerPortal == false){               
                	newCPAccountids.add(recSo.CustomerAccount__c); 
                }
                if(recSo.JO1__c != null && recSo.JO1__r.Account.IsCustomerPortal == false){               
                	newCPAccountids.add(recSo.JO1__r.AccountId);                
            	}
                if(recSo.JO2__c != null && recSo.JO2__r.Account.IsCustomerPortal == false){               
                	newCPAccountids.add(recSo.JO2__r.AccountId);                
            	}
                if(recSo.JO3__c != null && recSo.JO3__r.Account.IsCustomerPortal == false){               
                	newCPAccountids.add(recSo.JO3__r.AccountId);                
            	}
                if(recSo.JO4__c != null && recSo.JO4__r.Account.IsCustomerPortal == false){               
                	newCPAccountids.add(recSo.JO4__r.AccountId);                
            	}
                if(recSo.JO5__c != null && recSo.JO5__r.Account.IsCustomerPortal == false){               
                	newCPAccountids.add(recSo.JO5__r.AccountId);                
            	}
                if(recSo.JO6__c != null && recSo.JO6__r.Account.IsCustomerPortal == false){               
                	newCPAccountids.add(recSo.JO6__r.AccountId);                
            	}            
            //5.0 End Add the Joint Owner
            //6.0 End
        }
        if(newCPAccountids.size() > 0){
            createNewPortlauser(newCPAccountids);
        }        
        system.debug('28--- done with method calling');
    }

    
    global void finish(Database.BatchableContext bc) {
        
    }
    
    public static void createNewPortlauser(set<id> newCPAccountids){
        list<Contact> conList = [SELECT Id, FirstName, LastName, Email, EIDNumber__c,MailingCity, MailingCountry, MailingState, MailingStreet, MailingPostalCode, MobilePhone,Account.EIDNumber__pc,Account.PersonMailingStreet, Account.PersonMailingCity, Account.PersonMailingState, 
                                 Account.RecordType.name,Account.PersonMailingPostalCode, Account.PersonMailingCountry  FROM Contact  WHERE AccountId = :  newCPAccountids];
        
        system.debug('29--- ' + conList );
        
        list<User> usersToCreate =new list<User>();
        for(Contact conRec : conList){
            
            User newUserRec = new User();
            newUserRec.Username = conRec.Email;
            newUserRec.Email = conRec.Email;
            newUserRec.FirstName = conRec.FirstName;
            newUserRec.LastName = conRec.LastName;
            newUserRec.Phone = conRec.MobilePhone;
            newUserRec.Alias = conRec.LastName.length() >= 5 ? conRec.LastName.substring(0, 5) : conRec.LastName;
            newUserRec.TimeZoneSidKey = 'Asia/Dubai';
            newUserRec.LocaleSidKey = 'en_US';
            newUserRec.EmailEncodingKey = 'UTF-8';
            newUserRec.LanguageLocaleKey = 'en_US';
            newUserRec.ContactId = conRec.Id;
            newUserRec.ProfileId = '00eVH00000LdgMf';// 00eVG000002II6z
            newUserRec.IsActive = true;
            newUserRec.EmiratesIDNumber__c=conRec.Account.RecordType.name == 'Organization Account' ? conRec.EIDNumber__c:conRec.Account.EIDNumber__pc;
            newUserRec.Street = conRec.Account.RecordType.name == 'Organization Account' ? conRec.MailingStreet:conRec.Account.PersonMailingStreet;
            newUserRec.City = conRec.Account.RecordType.name == 'Organization Account' ? conRec.MailingCity:conRec.Account.PersonMailingCity;
            newUserRec.State = conRec.Account.RecordType.name == 'Organization Account' ? conRec.MailingState:conRec.Account.PersonMailingState;
            newUserRec.PostalCode = conRec.Account.RecordType.name == 'Organization Account' ? conRec.MailingPostalCode:conRec.Account.PersonMailingPostalCode;
            newUserRec.Country = conRec.Account.RecordType.name == 'Organization Account' ? conRec.MailingCountry:conRec.Account.PersonMailingCountry;
            Blob stringBlob = Blob.valueOf(newUserRec.Username);			
            String base64Encoded = EncodingUtil.base64Encode(stringBlob);
            newUserRec.EmailBase64String__c = base64Encoded;    
            system.debug('newUserRec---'+newUserRec);
            usersToCreate.add(newUserRec);            
        }
        
        if (!usersToCreate.isEmpty()) {
            
            // This allows partial success: if one record fails, others can still be inserted.
            Database.SaveResult[] results = Database.insert(usersToCreate, false);
            
            // Iterate through the results to check the outcome for each record
            for (Integer i = 0; i < results.size(); i++) { //5.0 Add loop results
                    Database.SaveResult sr = results[i];
                    User attemptedUser = usersToCreate[i];
                if (sr.isSuccess()) {
                    // Operation was successful for this record
                    System.debug('Successfully inserted contact with ID: ' + sr.getId());
                    // Step 2: Attempt password reset
                    try {
                        string newPassword =PasswordGenerator.generatePassword();
                        System.setPassword(sr.getId(), newPassword);                                     
                        system.debug('newPassword :' + newPassword);
                        // 3.0 Add logic for Communication Matrix                         
                        if(System.Label.StopEmailOnonBoardingCustomer == 'true'){ // 4.0 Add bypass 
                            if(sr.getId() != null){
                                user createuser = [SELECT Id, Email, Username,FirstName, EmiratesIDNumber__c,LastName,Street, City, 
                                               State, Country, PostalCode,Phone,Contact.AccountId FROM User 
                                               where id =:sr.getId()];
                                 String emailTemplateName = System.Label.Email_CustomerPortalEmail;                        
                                 SendGridNotificationUtility.sendEmail(null, createuser.id, emailTemplateName, createuser.Email, 'customercare@modon.com',
                                                                                       'MODON Customer Care',null,null, 'Customer Portal', 'Customer Management', null, null, createuser.id);
                            }                      
                        }
                        
                    }catch(Exception ex){
                        System.debug('Failed to resetPassword.'+ex);
                        LoggerService.save(LoggerService.createAPILog('Creat Password Customer Portal User','onBoardingCustomer','newPassword User',ex.getMessage(), ex.getMessage(), 'Error Message: ' +ex.getMessage(), 'Apex Log'));
                    }
                } else {
                     //6.0 Error for logic
                    // Operation failed for this record
                    System.debug('Failed to insert contact.');
                    // Retrieve and log the errors for the failed record
                    for (Database.Error error : sr.getErrors()) {
                        System.debug('Error Status Code: ' + error.getStatusCode());
                        System.debug('Error Message: ' + error.getMessage());
                        System.debug('Fields Affected: ' + error.getFields());
                        //5.0 Add Error Account
                        String errorDetails = 'AccountId: ' + attemptedUser.ContactId +
                              ' | Username: ' + attemptedUser.Username +
                              ' | Email: ' + attemptedUser.Email ;
        
        				System.debug('Error Details: ' + errorDetails);
                        
                        LoggerService.save(LoggerService.createAPILog('Creat New Customer Portal User','onBoardingCustomer','Create User',error.getMessage(), errorDetails, 'Error : 400', 'Apex Log'));
                    }
                }
            }
        }
    }
}