MODON MRE BPDEV/force-app/main/default/objects/Account/fields/OICIntegrationStatus__c.field-meta.xml
<CustomField>
    <fullName>OICIntegrationStatus__c</fullName>
    <label>OIC Integration Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>S</fullName>
                <label>Success</label>
            </value>
            <value>
                <fullName>E</fullName>
                <label>Failed</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

MODON MRE BPDEV/force-app/main/default/objects/Contact/fields/PassportIssueDate__c.field-meta.xml
<CustomField>
    <fullName>PassportIssueDate__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Passport Issue Date</label>
    <type>Date</type>
</CustomField>

MODON MRE BPDEV/force-app/main/default/objects/Contact/fields/PassportNumber__c.field-meta.xml
<CustomField>
    <fullName>PassportNumber__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Passport Number</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

MODON MRE BPDEV/force-app/main/default/objects/EscrowAccount__c/EscrowAccount__c.object-meta.xml
<CustomObject>
    <label>Escrow Account</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Escrow Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Escrow Accounts</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

MODON MRE BPDEV/force-app/main/default/objects/Expressionofinterest__c/Expressionofinterest__c.object-meta.xml
<CustomObject>
    <description>Object to store Expression of Interest details (Potential buyer details)</description>
    <label>Expression of Interest</label>
    <nameField>
        <displayFormat>EOI-{0000}</displayFormat>
        <label>EOI Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Expression of Interests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

MODON MRE BPDEV/force-app/main/default/objects/Expressionofinterest__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Expression of Interests</relationshipLabel>
    <relationshipName>Expression_of_Interests</relationshipName>
    <type>Lookup</type>
</CustomField>

MODON MRE BPDEV/force-app/main/default/objects/Expressionofinterest__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <description>Object to store the related opportunity which comes from a Lead</description>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Expression of Interests</relationshipLabel>
    <relationshipName>Expression_of_interests</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

MODON MRE BPDEV/force-app/main/default/objects/Expressionofinterest__c/fields/Phase__c.field-meta.xml
<CustomField>
    <fullName>Phase__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Phase</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2) OR 3</booleanFilter>
        <filterItems>
            <field>Phase__c.Source_Entity__c</field>
            <operation>equals</operation>
            <value>Modon - Egypt</value>
        </filterItems>
        <filterItems>
            <field>$Profile.Name</field>
            <operation>equals</operation>
            <value>Modon Egypt - Sales Management</value>
        </filterItems>
        <filterItems>
            <field>$Profile.Name</field>
            <operation>notEqual</operation>
            <value>Modon Egypt - Sales Management</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Phase__c</referenceTo>
    <relationshipLabel>Expression of Interests</relationshipLabel>
    <relationshipName>Expression_of_Interests</relationshipName>
    <type>Lookup</type>
</CustomField>

MODON MRE BPDEV/force-app/main/default/objects/Expressionofinterest__c/fields/UAE_Resident_Status__c.field-meta.xml
<CustomField>
    <fullName>UAE_Resident_Status__c</fullName>
    <formula>TEXT(Contact__r.UAE_Resident_Status__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>UAE_Resident_Status</label>
    <type>Text</type>
</CustomField>

MODON MRE BPDEV/force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <description>Object to store Invoice details, such as amounts &amp; transactions details</description>
    <label>Invoice</label>
    <nameField>
        <displayFormat>IN-{00000}</displayFormat>
        <label>Invoice  No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

MODON MRE BPDEV/force-app/main/default/objects/Invoice__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>A field to link with the related account of the invoice</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

MODON MRE BPDEV/force-app/main/default/objects/Invoice__c/fields/Expressionofinterest__c.field-meta.xml
<CustomField>
    <fullName>Expressionofinterest__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>A field to store the related EOI that is the invoice applied on</description>
    <label>Expression of interest</label>
    <referenceTo>Expressionofinterest__c</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

MODON MRE BPDEV/force-app/main/default/objects/Invoice__c/fields/InvoiceAmount__c.field-meta.xml
<CustomField>
    <fullName>InvoiceAmount__c</fullName>
    <description>A field to store the amount of the Invoice</description>
    <label>Invoice Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

MODON MRE BPDEV/force-app/main/default/objects/Invoice__c/fields/InvoiceDate__c.field-meta.xml
<CustomField>
    <fullName>InvoiceDate__c</fullName>
    <description>A field to store the invoice date</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Invoice Date</label>
    <type>Date</type>
</CustomField>

MODON MRE BPDEV/force-app/main/default/objects/Invoice__c/fields/Is_Milestone_Confirmed__c.field-meta.xml
<CustomField>
    <fullName>Is_Milestone_Confirmed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Milestone Confirmed</label>
    <type>Checkbox</type>
</CustomField>

MODON MRE BPDEV/force-app/main/default/objects/Invoice__c/fields/SalesOrderInstallment__c.field-meta.xml
<CustomField>
    <fullName>SalesOrderInstallment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>A field to store the related SOI that is the invoice applied on</description>
    <label>Sales Order Installment</label>
    <referenceTo>SalesOrderInstallments__c</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

MODON MRE BPDEV/force-app/main/default/objects/Opportunity/fields/PassportExpiryDate__c.field-meta.xml
<CustomField>
    <fullName>PassportExpiryDate__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Passport Expiry Date</label>
    <type>Date</type>
</CustomField>

MODON MRE BPDEV/force-app/main/default/objects/Opportunity/fields/PrimaryContact__c.field-meta.xml
<CustomField>
    <fullName>PrimaryContact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities (Primary Contact)</relationshipLabel>
    <relationshipName>Opportunities1</relationshipName>
    <type>Lookup</type>
</CustomField>

MODON MRE BPDEV/force-app/main/default/objects/Opportunity/fields/UAE_Resident_Status__c.field-meta.xml
<CustomField>
    <fullName>UAE_Resident_Status__c</fullName>
    <label>UAE Resident Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Resident</fullName>
            </value>
            <value>
                <fullName>Non-Resident</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

MODON MRE BPDEV/force-app/main/default/objects/PersonAccount/recordTypes/PersonAccount.recordType-meta.xml
<RecordType>
    <fullName>PersonAccount</fullName>
    <active>true</active>
    <description>To capture Individual customer details.</description>
    <label>Person Account</label>
</RecordType>

MODON MRE BPDEV/force-app/main/default/objects/Phase__c/Phase__c.object-meta.xml
<CustomObject>
    <label>Phase</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Building/Section Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Phases</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

MODON MRE BPDEV/force-app/main/default/objects/Phase__c/fields/EscrowAccount__c.field-meta.xml
<CustomField>
    <fullName>EscrowAccount__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Escrow Account</label>
    <referenceTo>EscrowAccount__c</referenceTo>
    <relationshipLabel>Phases</relationshipLabel>
    <relationshipName>Phases</relationshipName>
    <type>Lookup</type>
</CustomField>

MODON MRE BPDEV/force-app/main/default/objects/SalesOrder__c/SalesOrder__c.object-meta.xml
<CustomObject>
    <label>Sales Order</label>
    <nameField>
        <displayFormat>SO-{00000}</displayFormat>
        <label>Sales Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

MODON MRE BPDEV/force-app/main/default/objects/SalesOrder__c/fields/ExpressionofInterest__c.field-meta.xml
<CustomField>
    <fullName>ExpressionofInterest__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Expression of Interest</label>
    <referenceTo>Expressionofinterest__c</referenceTo>
    <relationshipLabel>Sales Orders</relationshipLabel>
    <relationshipName>Sales_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

MODON MRE BPDEV/force-app/main/default/objects/SalesOrder__c/fields/Nationality__c.field-meta.xml
<CustomField>
    <fullName>Nationality__c</fullName>
    <formula>TEXT(Opportunity__r.Nationality__c)</formula>
    <label>Nationality</label>
    <type>Text</type>
</CustomField>

MODON MRE BPDEV/force-app/main/default/objects/SalesOrder__c/fields/OICIntegrationStatus__c.field-meta.xml
<CustomField>
    <fullName>OICIntegrationStatus__c</fullName>
    <description>To track the integration status with oracle.</description>
    <label>OIC Integration Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>S</fullName>
                <label>Success</label>
            </value>
            <value>
                <fullName>E</fullName>
                <label>Failed</label>
            </value>
            <value>
                <fullName>Cancellation Success</fullName>
            </value>
            <value>
                <fullName>Cancellation Failed</fullName>
            </value>
            <value>
                <fullName>Transfer Success</fullName>
            </value>
            <value>
                <fullName>Transfer Failed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

MODON MRE BPDEV/force-app/main/default/objects/SalesOrder__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Sales Orders</relationshipLabel>
    <relationshipName>Sales_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

MODON MRE BPDEV/force-app/main/default/objects/SalesOrder__c/fields/PrimaryContact__c.field-meta.xml
<CustomField>
    <fullName>PrimaryContact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Sales Orders</relationshipLabel>
    <relationshipName>Sales_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

MODON MRE BPDEV/force-app/main/default/objects/SalesOrder__c/fields/UAE_Resident_Status__c.field-meta.xml
<CustomField>
    <fullName>UAE_Resident_Status__c</fullName>
    <label>UAE Resident Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Resident</fullName>
            </value>
            <value>
                <fullName>Non-Resident</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

MODON MRE BPDEV/force-app/main/default/objects/SalesOrderInstallments__c/SalesOrderInstallments__c.object-meta.xml
<CustomObject>
    <label>Sales Order Installment</label>
    <nameField>
        <displayFormat>SOI-{00000}</displayFormat>
        <label>Sales Order Installment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SalesOrderInstallments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

MODON MRE BPDEV/force-app/main/default/objects/SalesOrderInstallments__c/fields/SalesOrder__c.field-meta.xml
<CustomField>
    <fullName>SalesOrder__c</fullName>
    <label>Sales Order</label>
    <referenceTo>SalesOrder__c</referenceTo>
    <relationshipLabel>Sales Order Installments</relationshipLabel>
    <relationshipName>Sales_Order_Installments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

MODON MRE BPDEV/force-app/main/default/classes/OIC_ProjectInvoiceSyncBatchTest.cls
/**********************************************************************************************************************
* Name               : OIC_ProjectInvoiceSyncBatchTest
* Description        : Test Class for OIC_ProjectInvoiceSyncBatch
* Created By         : PWC Digital Middle East
* --------------------------------------------------------------------------------------------------------------------
* Version       Author              Date                Comment
* 1.0           Prateek             16 Oct 2025         Initial
***********************************************************************************************************************/
@IsTest
public with sharing class OIC_ProjectInvoiceSyncBatchTest {
    // --------------------------------------------------------------------------------------
    // Generic HTTP mock to satisfy downstream callouts inside the integration controller.
    // --------------------------------------------------------------------------------------
    private class Generic200HttpMock implements HttpCalloutMock {
        public HTTPResponse respond(HTTPRequest req) {
            HttpResponse res = new HttpResponse();
            res.setStatusCode(200);
            res.setStatus('OK');
            // A minimal success body; adjust if your controller expects a format.
            res.setBody('{"success":true}');
            return res;
        }
    }

    // --------------------------------------------------------------------------------------
    // Seed minimal, consistent data once for all tests
    // NOTE: You can enrich this as needed; the query in the batch is not relied upon
    //       for the "execute()" coverage since we call execute() directly with a scope.
    // --------------------------------------------------------------------------------------
    @testSetup
    public static void makeData() {
        Schema.RecordTypeInfo recordTypeInfo = Schema.getGlobalDescribe().get('Account').getDescribe().getRecordTypeInfosByDeveloperName().get('PersonAccount');
         String recordTypeId = recordTypeInfo.getRecordTypeId();
         
        Account testAccount = new Account();
       // testAccount.Name = 'Test Account';
        testAccount.FirstName = 'First';
        testAccount.LastName = 'Last';
        testAccount.UAE_Resident_Status__pc = 'Non-Resident';
        testAccount.Nationality__pc = 'India';
        testAccount.PassportIssueDate__pc = Date.today();
        testAccount.PassportExpiryDate__pc = Date.today().AddDays(200);
        testAccount.PassportNumber__pc = 'NP232131';
        testAccount.RecordTypeId =recordTypeId;
        insert testAccount;
        
       /* Contact conObj = new Contact();
        conObj.LastName = 'Test contact';
        conObj.Email = 'test@test.com';
        conObj.accountid=testAccount.id;
        INSERT conObj;*/
        
        Opportunity oppObj = new Opportunity();
        oppObj.Name = 'Test opportunity';
        oppObj.StageName = 'Discussion In Progress';
        oppObj.CloseDate = System.Today();
        oppObj.accountid=testAccount.id;
        //oppObj.PrimaryContact__c = testAccount.Id;
        oppObj.Nationality__c = 'India';
        oppObj.UAE_Resident_Status__c='Non-Resident';
        oppObj.PassportIssueDate__c = Date.today();
        oppObj.PassportExpiryDate__c = Date.today().AddDays(200);
        oppObj.PassportNumber__c = 'NP232131';
        insert oppObj;
        
        EscrowAccount__c escAccount = new EscrowAccount__c(name='Phase 1 Escrow Account');
        insert escAccount;
        phase__c phase = new phase__c(name='Test Phase',EscrowAccount__c =escAccount.id );
        insert phase;
        
        Expressionofinterest__c eoi = new Expressionofinterest__c();
        eoi.Opportunity__c = oppObj.Id;
        eoi.Phase__c = phase.id;
        insert eoi;
        
        SalesOrder__c so = new SalesOrder__c();
        insert so;
        
        SalesOrderInstallments__c soi = new SalesOrderInstallments__c();
        soi.SalesOrder__c = so.Id;
        insert soi;
        
        Invoice__c invoice = new Invoice__c();
        invoice.Expressionofinterest__c = eoi.Id;
        invoice.InvoiceAmount__c = 100;
        invoice.Account__c = testAccount.Id;
        invoice.OICIntegrationStatus__c = '';
        insert invoice;

        list<Invoice__c> invoiceList = new list<Invoice__c>();
            Invoice__c inv = new Invoice__c(
                Expressionofinterest__c = eoi.Id,
                InvoiceAmount__c = 100,
                Account__c = testAccount.Id,               
                OICIntegrationStatus__c = '', // Not 'S'
                InvoiceDate__c = Date.today().addDays(1), // TOMORROW
                Is_Milestone_Confirmed__c = true,
                SalesOrderInstallment__c = soi.id 
            );
            invoiceList.add(inv);
  

        insert invoiceList;
    }

    // --------------------------------------------------------------------------------------
    // Test 1: Cover start() via executeBatch() using override project name
    //         (ensures QueryLocator creation and safe no-op when no records match)
    // --------------------------------------------------------------------------------------
    @IsTest
    static void test_start_viaExecuteBatch_noMatches() {
        Test.setMock(HttpCalloutMock.class, new Generic200HttpMock());

        // Use an override project name that does NOT match the setup data
        OIC_ProjectInvoiceSyncBatch batch = new OIC_ProjectInvoiceSyncBatch('Project-That-Does-Not-Exist');

        Test.startTest();
        Id jobId = Database.executeBatch(batch, 10);
        // Also schedule path coverage
        String cron = '0 0 2 * * ?';
        System.schedule('OIC Project Invoice Sync (Test)', cron, new OIC_ProjectInvoiceSyncBatch('Another-Non-Match'));
        Test.stopTest();

        System.assertNotEquals(null, jobId, 'Batch job should be queued.');
    }

    // --------------------------------------------------------------------------------------
    // Test 2: Directly cover execute() with a fabricated scope (bypassing filters)
    //         This ensures that ID collection and downstream controller call path is covered.
    // --------------------------------------------------------------------------------------
    @IsTest
    static void test_execute_withScope_callsController() {
        Test.setMock(HttpCalloutMock.class, new Generic200HttpMock());

        // Grab one Invoice from setup
        Invoice__c seedInv = [SELECT Id FROM Invoice__c LIMIT 1];

        // Prepare a scope list with that invoice (bypasses the query filters)
        List<Invoice__c> scope = new List<Invoice__c>{ seedInv };

        // Instantiate with any project name; not used in direct execute() call
        OIC_ProjectInvoiceSyncBatch batch = new OIC_ProjectInvoiceSyncBatch('IrrelevantForDirectExecute');

        Test.startTest();
        // Call execute directly to cover the logic that collects IDs and calls the controller
        batch.execute(null, scope);
        Test.stopTest();

        // No exception means pass; optionally assert something about the invoice still exists
        System.assertNotEquals(null, seedInv.Id, 'Seed invoice should exist.');
    }
     @isTest
    static void testSchedulerExecutesBatch() {

        Test.startTest();

        // Execute scheduler directly (this simulates Salesforce scheduler firing)
        OIC_ProjectInvoiceScheduler scheduler = new OIC_ProjectInvoiceScheduler();
        scheduler.execute(null);
        
        OIC_ProjectInvoiceSchedulerB sche = new OIC_ProjectInvoiceSchedulerB ();
        sche.execute(null);

        Test.stopTest();
    }
}