MODON MRE BPDEV/force-app/main/default/objects/Documents__c/Documents__c.object-meta.xml
<CustomObject>
    <description>Object to store custom document details (Document placeholder)</description>
    <label>Document</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Document Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Documents</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

MODON MRE BPDEV/force-app/main/default/objects/Documents__c/fields/Registration_Agent__c.field-meta.xml
<CustomField>
    <fullName>Registration_Agent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Registration Agent</label>
    <referenceTo>Registration_Agent__c</referenceTo>
    <relationshipLabel>Documents</relationshipLabel>
    <relationshipName>Documents</relationshipName>
    <type>Lookup</type>
</CustomField>

MODON MRE BPDEV/force-app/main/default/objects/Registration_Agent__c/Registration_Agent__c.object-meta.xml
<CustomObject>
    <description>This is the child Object to Registration</description>
    <label>Registration Agent</label>
    <nameField>
        <displayFormat>RA-{00000}</displayFormat>
        <label>Agent Full Name (Passport)</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Registration Agents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

MODON MRE BPDEV/force-app/main/default/classes/Registrationagentstriggerhandler.cls
public class Registrationagentstriggerhandler {

    public static void createDocumentRecords(List<SObject> newList){
        list<Documents__c> lstDocumentsCurrent = new list<Documents__c>();
        lstDocumentsCurrent = DocumentsUtility.getDocumentsForSObject('Registration_Agent__c');
         if(!lstDocumentsCurrent.isEmpty()){
            list<Documents__c> lstDocumentsToInsert = new list<Documents__c>();
            for(Registration_Agent__c registration : (List<Registration_Agent__c>)newList){
                for(Documents__c doc: lstDocumentsCurrent){
                    Documents__c tempD = doc.clone();
                    tempD.Registration_Agent__c = registration.Id;
                    lstDocumentsToInsert.add(tempD);
                }
            }
            if(!lstDocumentsToInsert.isEmpty()){
                insert lstDocumentsToInsert;
            }
        }
    }
}