MODON MRE BPDEV/force-app/main/default/objects/Documents__c/Documents__c.object-meta.xml
<CustomObject>
    <description>Object to store custom document details (Document placeholder)</description>
    <label>Document</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Document Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Documents</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

MODON MRE BPDEV/force-app/main/default/objects/Documents__c/fields/Refund__c.field-meta.xml
<CustomField>
    <fullName>Refund__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Refund</label>
    <referenceTo>Refund__c</referenceTo>
    <relationshipLabel>Documents</relationshipLabel>
    <relationshipName>Documents</relationshipName>
    <type>Lookup</type>
</CustomField>

MODON MRE BPDEV/force-app/main/default/objects/Refund__c/Refund__c.object-meta.xml
<CustomObject>
    <label>Refund</label>
    <nameField>
        <displayFormat>Refund-{00000}</displayFormat>
        <label>Refund No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Refunds</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

MODON MRE BPDEV/force-app/main/default/objects/Refund__c/fields/Source_Entity__c.field-meta.xml
<CustomField>
    <fullName>Source_Entity__c</fullName>
    <formula>TEXT(Account__r.Source_Entity__c)</formula>
    <label>Source Entity</label>
    <type>Text</type>
</CustomField>

MODON MRE BPDEV/force-app/main/default/classes/RefundTriggerHelper.cls
/**********************************************************************************************************************
* Name               : RefundTriggerHelper                                                        
* Description        : This class is helper for Refund trigger
* Usage              : Called from RefundTriggerHandler
* Created By         : Gautam Sah(Horizontal)                                                     
* --------------------------------------------------------------------------------------------------------------------
* Version       Author                              Date            Comment                                                                       
* 1.0           Gautam Sah(Horizontal)           02 April 2025     Initial Draft       
******************************************************************************************************************/
public without sharing class RefundTriggerHelper {
    
    public static void createDocumentRecords(List<SObject> newList){ // call this After Insert.
        
        list<Documents__c> lstDocumentsCurrent = new list<Documents__c>();
        lstDocumentsCurrent = DocumentsUtility.getEgyptDocumentsForSObject('Refund__c', 'Modon - Egypt');
        if(!lstDocumentsCurrent.isEmpty()){
            list<Documents__c> lstDocumentsToInsert = new list<Documents__c>();
            for(Refund__c refund : (List<Refund__c>)newList){
                if (refund.Source_Entity__c == 'Modon - Egypt'){
                    for(Documents__c doc: lstDocumentsCurrent){
                        Documents__c tempD = doc.clone();
                        tempD.Refund__c = refund.Id;
                        lstDocumentsToInsert.add(tempD);
                	}
                }
            }
            if(!lstDocumentsToInsert.isEmpty()){
                insert lstDocumentsToInsert;
            }
        }
    }
}