MODON MRE BPDEV/force-app/main/default/objects/Documents__c/Documents__c.object-meta.xml
<CustomObject>
    <description>Object to store custom document details (Document placeholder)</description>
    <label>Document</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Document Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Documents</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

MODON MRE BPDEV/force-app/main/default/objects/Documents__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>A field to store the related opportunity which comes from a Lead</description>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Documents</relationshipLabel>
    <relationshipName>Documents</relationshipName>
    <type>Lookup</type>
</CustomField>

MODON MRE BPDEV/force-app/main/default/objects/Documents__c/fields/SalesOrder__c.field-meta.xml
<CustomField>
    <fullName>SalesOrder__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Order</label>
    <referenceTo>SalesOrder__c</referenceTo>
    <relationshipLabel>Documents</relationshipLabel>
    <relationshipName>Documents</relationshipName>
    <type>Lookup</type>
</CustomField>

MODON MRE BPDEV/force-app/main/default/objects/Documents__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>A field to store the document status</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending Upload</fullName>
                <default>true</default>
                <label>Pending Upload</label>
            </value>
            <value>
                <fullName>Uploaded</fullName>
            </value>
            <value>
                <fullName>Generated</fullName>
            </value>
            <value>
                <fullName>Signed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

MODON MRE BPDEV/force-app/main/default/objects/Opportunity/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Resale SR</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

MODON MRE BPDEV/force-app/main/default/objects/SalesOrder__c/SalesOrder__c.object-meta.xml
<CustomObject>
    <label>Sales Order</label>
    <nameField>
        <displayFormat>SO-{00000}</displayFormat>
        <label>Sales Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

MODON MRE BPDEV/force-app/main/default/objects/SalesOrder__c/fields/CustomerAccount__c.field-meta.xml
<CustomField>
    <fullName>CustomerAccount__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Sales Orders</relationshipLabel>
    <relationshipName>Sales_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

MODON MRE BPDEV/force-app/main/default/objects/SalesOrder__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Sales Orders</relationshipLabel>
    <relationshipName>Sales_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

MODON MRE BPDEV/force-app/main/default/objects/SalesOrder__c/fields/Parent_Sales_Order__c.field-meta.xml
<CustomField>
    <fullName>Parent_Sales_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Sales Order</label>
    <referenceTo>SalesOrder__c</referenceTo>
    <relationshipLabel>Sales Orders</relationshipLabel>
    <relationshipName>Sales_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

MODON MRE BPDEV/force-app/main/default/objects/SalesOrder__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Reservation form generated</fullName>
            </value>
            <value>
                <fullName>Down payment collected</fullName>
            </value>
            <value>
                <fullName>Reservation form signed</fullName>
            </value>
            <value>
                <fullName>Installment Payment Collected</fullName>
            </value>
            <value>
                <fullName>DP Payment Confirmed</fullName>
            </value>
            <value>
                <fullName>SPA Generated</fullName>
            </value>
            <value>
                <fullName>SPA Signed (Customer)</fullName>
            </value>
            <value>
                <fullName>SPA Signed (Modon)</fullName>
            </value>
            <value>
                <fullName>SPA Delivered</fullName>
            </value>
            <value>
                <fullName>Sold</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>System cancelled</fullName>
            </value>
            <value>
                <fullName>KYC - In progress</fullName>
            </value>
            <value>
                <fullName>KYC - Completed / KYC Rejected</fullName>
            </value>
            <value>
                <fullName>Payments Collected</fullName>
            </value>
            <value>
                <fullName>Downpayment Payments Cleared</fullName>
            </value>
            <value>
                <fullName>SPA Sent to customer</fullName>
            </value>
            <value>
                <fullName>SPA Validated</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Cancelled SR</fullName>
            </value>
            <value>
                <fullName>Voided</fullName>
            </value>
            <value>
                <fullName>Pending Blocking Fees</fullName>
            </value>
            <value>
                <fullName>Blocking Fees Collected</fullName>
            </value>
            <value>
                <fullName>Property Transfer Cancelled - SR</fullName>
            </value>
            <value>
                <fullName>Unit Swap Cancelled - SR</fullName>
            </value>
            <value>
                <fullName>Unit Upgrade Cancelled - SR</fullName>
            </value>
            <value>
                <fullName>Unit Cancellation Cancelled - SR</fullName>
            </value>
            <value>
                <fullName>Unit Consolidation Cancelled - SR</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

MODON MRE BPDEV/force-app/main/default/classes/CloneOpportunityController.cls
public with sharing class CloneOpportunityController {
    
    @AuraEnabled(Cacheable=true)
    public static List<Opportunity> getRelatedOpportunities(Id accountId) {
        return [SELECT Id, Name,(Select Id From Sales_Orders__r) FROM Opportunity WHERE AccountId = :accountId];
    }
    
    @AuraEnabled
    public static Id cloneOpportunity(Id accountId) {
        
        //Id userId = UserInfo.getUserId();
        List<Opportunity> allOpportunities = [SELECT Id, Name FROM Opportunity WHERE AccountId = :accountId];
        
        if(allOpportunities.size() < 1){
            throw new AuraHandledException('You have no opportunity to clone');
        }
        
        Set<Id> opportunityIdsWithValidSalesOrders = new Set<Id>();
        for (SalesOrder__c salesOrder : [SELECT Opportunity__c FROM SalesOrder__c WHERE Opportunity__r.AccountId = :accountId 
                                         AND Status__c NOT IN ('Cancelled', 'System Cancelled', 'In Progress')]) {
                                             opportunityIdsWithValidSalesOrders.add(salesOrder.Opportunity__c);
                                         }
        
        Boolean allOpportunitiesHaveValidSalesOrders = true;
        for (Opportunity opp : allOpportunities) {
            if (!opportunityIdsWithValidSalesOrders.contains(opp.Id)) {
                allOpportunitiesHaveValidSalesOrders = false;
                break;
            }
        }
        
        if (!allOpportunitiesHaveValidSalesOrders) {
            return null;
        }
        
        Opportunity originalOpp = [SELECT Id, Name, StageName, Account.Name, OwnerId FROM Opportunity WHERE Id IN :opportunityIdsWithValidSalesOrders 
                                   ORDER BY CreatedDate ASC LIMIT 1];
        List<SObject> passtoDocument = new List<SObject>();
        Opportunity clonedOpp;
        try{
            clonedOpp = originalOpp.clone(false, true);
            clonedOpp.Name = originalOpp.Account.Name;
            clonedOpp.StageName = 'Unit Selection in Progress';
            clonedOpp.CloseDate = Date.today().addDays(2);
            insert clonedOpp;
        }catch(DMLException e){
            System.debug('Error While Inserting Clone Record:'+ e.getMessage());
        }
        try{
            AccountShare accountShare = new AccountShare();
            accountShare.AccountId = originalOpp.AccountId;
            accountShare.UserOrGroupId = originalOpp.OwnerId;
            accountShare.AccountAccessLevel = 'Edit'; 
            accountShare.OpportunityAccessLevel = 'Edit';
            accountShare.RowCause = Schema.AccountShare.RowCause.Manual;
            insert accountShare;
            System.debug('accountShare: '+accountShare);
        }catch(DMLException e){
            System.debug('Error While Creating account sharing: '+ e.getMessage());
        }
        passtoDocument.add(clonedOpp);
        createDocumentRecords(passtoDocument);
        return clonedOpp.Id;
    }
    public static void createDocumentRecords(List<SObject> newList) { 
        List<Documents__c> lstDocumentsCurrent = DocumentsUtility.getDocumentsForSObject('Lead');
        
        if (!lstDocumentsCurrent.isEmpty()) {
            List<Documents__c> lstDocumentsToInsert = new List<Documents__c>();
            for (Opportunity soObj : (List<Opportunity>)newList) {
                for (Documents__c doc : lstDocumentsCurrent) {
                    Documents__c tempD = doc.clone();
                    tempD.Opportunity__c = soObj.Id;
                    lstDocumentsToInsert.add(tempD);
                }
            }
            if (!lstDocumentsToInsert.isEmpty()) {
                try{
                    insert lstDocumentsToInsert;
                }
                catch(DMLException e){
                    System.debug('Documents Insertion Failed: '+ e.getMessage());
                }
            }
        }
    }
}