MODON MRE BPDEV/force-app/main/default/objects/Opportunity/fields/EIDNumber__c.field-meta.xml
<CustomField>
    <fullName>EIDNumber__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Please enter the value in the format of 784-xxxx-xxxxxxx-x</inlineHelpText>
    <label>Emirates ID Number</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

MODON MRE BPDEV/force-app/main/default/objects/Opportunity/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Resale SR</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

MODON MRE BPDEV/force-app/main/default/objects/Opportunity/fields/UAE_Resident_Status__c.field-meta.xml
<CustomField>
    <fullName>UAE_Resident_Status__c</fullName>
    <label>UAE Resident Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Resident</fullName>
            </value>
            <value>
                <fullName>Non-Resident</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

MODON MRE BPDEV/force-app/main/default/objects/SalesOrder__c/SalesOrder__c.object-meta.xml
<CustomObject>
    <label>Sales Order</label>
    <nameField>
        <displayFormat>SO-{00000}</displayFormat>
        <label>Sales Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

MODON MRE BPDEV/force-app/main/default/objects/SalesOrder__c/fields/CustomerAccount__c.field-meta.xml
<CustomField>
    <fullName>CustomerAccount__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Sales Orders</relationshipLabel>
    <relationshipName>Sales_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

MODON MRE BPDEV/force-app/main/default/objects/SalesOrder__c/fields/Nationality__c.field-meta.xml
<CustomField>
    <fullName>Nationality__c</fullName>
    <formula>TEXT(Opportunity__r.Nationality__c)</formula>
    <label>Nationality</label>
    <type>Text</type>
</CustomField>

MODON MRE BPDEV/force-app/main/default/objects/SalesOrder__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Sales Orders</relationshipLabel>
    <relationshipName>Sales_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

MODON MRE BPDEV/force-app/main/default/objects/SalesOrder__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Reservation form generated</fullName>
            </value>
            <value>
                <fullName>Down payment collected</fullName>
            </value>
            <value>
                <fullName>Reservation form signed</fullName>
            </value>
            <value>
                <fullName>Installment Payment Collected</fullName>
            </value>
            <value>
                <fullName>DP Payment Confirmed</fullName>
            </value>
            <value>
                <fullName>SPA Generated</fullName>
            </value>
            <value>
                <fullName>SPA Signed (Customer)</fullName>
            </value>
            <value>
                <fullName>SPA Signed (Modon)</fullName>
            </value>
            <value>
                <fullName>SPA Delivered</fullName>
            </value>
            <value>
                <fullName>Sold</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>System cancelled</fullName>
            </value>
            <value>
                <fullName>KYC - In progress</fullName>
            </value>
            <value>
                <fullName>KYC - Completed / KYC Rejected</fullName>
            </value>
            <value>
                <fullName>Payments Collected</fullName>
            </value>
            <value>
                <fullName>Downpayment Payments Cleared</fullName>
            </value>
            <value>
                <fullName>SPA Sent to customer</fullName>
            </value>
            <value>
                <fullName>SPA Validated</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Cancelled SR</fullName>
            </value>
            <value>
                <fullName>Voided</fullName>
            </value>
            <value>
                <fullName>Pending Blocking Fees</fullName>
            </value>
            <value>
                <fullName>Blocking Fees Collected</fullName>
            </value>
            <value>
                <fullName>Property Transfer Cancelled - SR</fullName>
            </value>
            <value>
                <fullName>Unit Swap Cancelled - SR</fullName>
            </value>
            <value>
                <fullName>Unit Upgrade Cancelled - SR</fullName>
            </value>
            <value>
                <fullName>Unit Cancellation Cancelled - SR</fullName>
            </value>
            <value>
                <fullName>Unit Consolidation Cancelled - SR</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

MODON MRE BPDEV/force-app/main/default/objects/SalesOrder__c/fields/UAE_Resident_Status__c.field-meta.xml
<CustomField>
    <fullName>UAE_Resident_Status__c</fullName>
    <label>UAE Resident Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Resident</fullName>
            </value>
            <value>
                <fullName>Non-Resident</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

MODON MRE BPDEV/force-app/main/default/classes/TransferQueueableSOTest.cls
@IsTest
private class TransferQueueableSOTest {

    private class MockHttpResponseGenerator implements HttpCalloutMock {

        public HTTPResponse respond(HTTPRequest req) {

            HttpResponse res = new HttpResponse();
            res.setHeader('Content-Type', 'application/json');
            res.setStatusCode(200);

            res.setBody('S');

            return res;
        }
    }

    @IsTest
    static void testQueueable_SuccessFlow() {

         Account testAccount = new Account(Name = 'Test Account');
        insert testAccount;
        
              Opportunity testOpportunity = new Opportunity(Name = 'Test Opportunity', StageName = 'Qualification', CloseDate = Date.today(),UAE_Resident_Status__c = 'Resident',Nationality__c = 'United Arab Emirates',EmiratesIDExpiryDate__c = Date.today().addDays(365),EIDNumber__c='784-1232-1234567-4');
        insert testOpportunity;
        
        
        SalesOrder__c testSalesOrder = new SalesOrder__c(
            CustomerAccount__c = testAccount.Id,
            Opportunity__c = testOpportunity.Id,
            Status__c = 'Completed'
        );
        insert testSalesOrder;
        Set<String> soIds = new Set<String>();
        soIds.add(testSalesOrder.Id);

        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());

        Test.startTest();

        System.enqueueJob(new TransferQueueableSO(soIds));

        Test.stopTest();
    }
}