MODON MRE BPDEV/force-app/main/default/objects/Block_Request__c/Block_Request__c.object-meta.xml
<CustomObject>
    <description>Object to be used to raise unit block request by the Sales Associates</description>
    <label>Block Request</label>
    <nameField>
        <displayFormat>BR-{00000}</displayFormat>
        <label>Block Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Block Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

MODON MRE BPDEV/force-app/main/default/objects/Block_Request__c/fields/Hourstoblock__c.field-meta.xml
<CustomField>
    <fullName>Hourstoblock__c</fullName>
    <description>A field to store how many hours the unit is blocked</description>
    <label>Hours to block</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>20 Min</fullName>
                <default>true</default>
                <label>20 Min</label>
            </value>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>24</fullName>
            </value>
            <value>
                <fullName>48</fullName>
            </value>
            <value>
                <fullName>Unlimited</fullName>
            </value>
            <value>
                <fullName>120</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

MODON MRE BPDEV/force-app/main/default/objects/Block_Request__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>A field to sore the status of the unit block request</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In Progress</fullName>
                <default>true</default>
                <label>In Progress</label>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

MODON MRE BPDEV/force-app/main/default/objects/Block_Request__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>A field to link the unit that the block request to going to be raised on</description>
    <label>Unit</label>
    <referenceTo>Unit__c</referenceTo>
    <relationshipLabel>Block Requests</relationshipLabel>
    <relationshipName>Block_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

MODON MRE BPDEV/force-app/main/default/objects/Unit__c/Unit__c.object-meta.xml
<CustomObject>
    <description>This object is part of inventory management to store the unit details</description>
    <label>Unit</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Units</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

MODON MRE BPDEV/force-app/main/default/objects/Unit__c/fields/BlockedBy__c.field-meta.xml
<CustomField>
    <fullName>BlockedBy__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Blocked By</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Units</relationshipName>
    <type>Lookup</type>
</CustomField>

MODON MRE BPDEV/force-app/main/default/objects/Unit__c/fields/BlockedFor__c.field-meta.xml
<CustomField>
    <fullName>BlockedFor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Blocked For</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Units1</relationshipName>
    <type>Lookup</type>
</CustomField>

MODON MRE BPDEV/force-app/main/default/objects/Unit__c/fields/BlockUntil__c.field-meta.xml
<CustomField>
    <fullName>BlockUntil__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Block Until</label>
    <type>DateTime</type>
</CustomField>

MODON MRE BPDEV/force-app/main/default/objects/Unit__c/fields/PlotAreasqm__c.field-meta.xml
<CustomField>
    <fullName>PlotAreasqm__c</fullName>
    <label>Plot Area</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

MODON MRE BPDEV/force-app/main/default/objects/Unit__c/fields/PlotNo__c.field-meta.xml
<CustomField>
    <fullName>PlotNo__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Plot No</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

MODON MRE BPDEV/force-app/main/default/objects/Unit__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Unit Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Available</fullName>
            </value>
            <value>
                <fullName>Sold</fullName>
            </value>
            <value>
                <fullName>CCMD</fullName>
            </value>
            <value>
                <fullName>Reserved</fullName>
            </value>
            <value>
                <fullName>UnReleased</fullName>
            </value>
            <value>
                <fullName>Blocked</fullName>
                <isActive>false</isActive>
                <label>Blocked</label>
            </value>
            <value>
                <fullName>Booked</fullName>
                <isActive>false</isActive>
                <label>Booked</label>
            </value>
            <value>
                <fullName>Booking cancelled</fullName>
                <isActive>false</isActive>
                <label>Booking cancelled</label>
            </value>
            <value>
                <fullName>Booking confirmed</fullName>
                <isActive>false</isActive>
                <label>Booking confirmed</label>
            </value>
            <value>
                <fullName>Booking in progress</fullName>
                <isActive>false</isActive>
                <label>Booking in progress</label>
            </value>
            <value>
                <fullName>Draft</fullName>
                <isActive>false</isActive>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Leased</fullName>
                <isActive>false</isActive>
                <label>Leased</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

MODON MRE BPDEV/force-app/main/default/objects/Unit__c/fields/Sub_Status__c.field-meta.xml
<CustomField>
    <fullName>Sub_Status__c</fullName>
    <label>Sub Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Assigned</fullName>
            </value>
            <value>
                <fullName>Un-Assigned</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

MODON MRE BPDEV/force-app/main/default/classes/BlockRequestTriggerHelperTest.cls
@isTest
public class BlockRequestTriggerHelperTest {
    @isTest
    static void testCheckBlockApproval() {
        Unit__c testUnit = new Unit__c();
        testUnit.PlotAreasqm__c = 1.0;
        testUnit.PlotNo__c = '1';
        testUnit.Status__c='Available';
        testUnit.Sub_Status__c='Un-Assigned';
        testUnit.BlockedBy__c=null;
        insert testUnit;

        Block_Request__c testBlockRequest = new Block_Request__c(
            Status__c = 'In Progress',
            Unit__c = testUnit.Id,
            Hourstoblock__c = '2'
        );
        insert testBlockRequest;
        
        Block_Request__c oldBr = [SELECT id, Status__c,Unit__c FROM Block_Request__c WHERE Id =: testBlockRequest.Id];
        
        testBlockRequest.Status__c = 'Approved';
        update testBlockRequest;
        
        Block_Request__c newBr = [SELECT id, Status__c,Unit__c FROM Block_Request__c WHERE Id =: testBlockRequest.Id];

        Approval.ProcessSubmitRequest req1 = new Approval.ProcessSubmitRequest();
        req1.setComments('Submitting request for approval.');
        req1.setObjectId(testBlockRequest.Id);
        List<ProcessInstance> approvalProcesses = [SELECT Id, TargetObjectId, status FROM ProcessInstance WHERE TargetObjectId =: testBlockRequest.Id];

        List<ProcessInstanceWorkitem> workItems = [SELECT Id, ProcessInstanceId FROM ProcessInstanceWorkitem WHERE ProcessInstanceId IN :approvalProcesses];
        System.debug('asdsad ' + workitems);

        if (!workItems.isEmpty()) {
            Approval.ProcessWorkitemRequest req = new Approval.ProcessWorkitemRequest();
            req.setComments('Approving the request.');
            req.setAction('Approve');
            req.setWorkitemId(workItems[0].Id);

            Approval.ProcessResult result = Approval.process(req);
        }

        testBlockRequest = [SELECT Id, Status__c FROM Block_Request__c WHERE Id =: testBlockRequest.Id];

        Map<Id, SObject> oldMap = new Map<Id, SObject>{oldBr.Id => oldBr};
        Map<Id, SObject> newMap = new Map<Id, SObject>{newBr.Id => newBr};

        Test.startTest();
        BlockRequestTriggerHelper.checkBlockApproval(oldMap, newMap);
        Test.stopTest();

        testUnit = [SELECT Id, Status__c, BlockedFor__c, BlockedBy__c, BlockUntil__c FROM Unit__c WHERE Id =: testUnit.Id];
    }
}