MODON MRE BPDEV/force-app/main/default/objects/Block_Request__c/Block_Request__c.object-meta.xml
<CustomObject>
    <description>Object to be used to raise unit block request by the Sales Associates</description>
    <label>Block Request</label>
    <nameField>
        <displayFormat>BR-{00000}</displayFormat>
        <label>Block Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Block Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

MODON MRE BPDEV/force-app/main/default/objects/Block_Request__c/fields/Hourstoblock__c.field-meta.xml
<CustomField>
    <fullName>Hourstoblock__c</fullName>
    <description>A field to store how many hours the unit is blocked</description>
    <label>Hours to block</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>20 Min</fullName>
                <default>true</default>
                <label>20 Min</label>
            </value>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>24</fullName>
            </value>
            <value>
                <fullName>48</fullName>
            </value>
            <value>
                <fullName>Unlimited</fullName>
            </value>
            <value>
                <fullName>120</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

MODON MRE BPDEV/force-app/main/default/objects/Block_Request__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>A lookup field to its related opportunity</description>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Block Requests</relationshipLabel>
    <relationshipName>Block_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

MODON MRE BPDEV/force-app/main/default/objects/Block_Request__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>A field to sore the status of the unit block request</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In Progress</fullName>
                <default>true</default>
                <label>In Progress</label>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

MODON MRE BPDEV/force-app/main/default/objects/Block_Request__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>A field to link the unit that the block request to going to be raised on</description>
    <label>Unit</label>
    <referenceTo>Unit__c</referenceTo>
    <relationshipLabel>Block Requests</relationshipLabel>
    <relationshipName>Block_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

MODON MRE BPDEV/force-app/main/default/objects/Unit__c/Unit__c.object-meta.xml
<CustomObject>
    <description>This object is part of inventory management to store the unit details</description>
    <label>Unit</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Units</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

MODON MRE BPDEV/force-app/main/default/objects/Unit__c/fields/BlockedBy__c.field-meta.xml
<CustomField>
    <fullName>BlockedBy__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Blocked By</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Units</relationshipName>
    <type>Lookup</type>
</CustomField>

MODON MRE BPDEV/force-app/main/default/objects/Unit__c/fields/BlockedFor__c.field-meta.xml
<CustomField>
    <fullName>BlockedFor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Blocked For</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Units1</relationshipName>
    <type>Lookup</type>
</CustomField>

MODON MRE BPDEV/force-app/main/default/objects/Unit__c/fields/BlockUntil__c.field-meta.xml
<CustomField>
    <fullName>BlockUntil__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Block Until</label>
    <type>DateTime</type>
</CustomField>

MODON MRE BPDEV/force-app/main/default/objects/Unit__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Units</relationshipLabel>
    <relationshipName>Units</relationshipName>
    <type>Lookup</type>
</CustomField>

MODON MRE BPDEV/force-app/main/default/objects/Unit__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Unit Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Available</fullName>
            </value>
            <value>
                <fullName>Sold</fullName>
            </value>
            <value>
                <fullName>CCMD</fullName>
            </value>
            <value>
                <fullName>Reserved</fullName>
            </value>
            <value>
                <fullName>UnReleased</fullName>
            </value>
            <value>
                <fullName>Blocked</fullName>
                <isActive>false</isActive>
                <label>Blocked</label>
            </value>
            <value>
                <fullName>Booked</fullName>
                <isActive>false</isActive>
                <label>Booked</label>
            </value>
            <value>
                <fullName>Booking cancelled</fullName>
                <isActive>false</isActive>
                <label>Booking cancelled</label>
            </value>
            <value>
                <fullName>Booking confirmed</fullName>
                <isActive>false</isActive>
                <label>Booking confirmed</label>
            </value>
            <value>
                <fullName>Booking in progress</fullName>
                <isActive>false</isActive>
                <label>Booking in progress</label>
            </value>
            <value>
                <fullName>Draft</fullName>
                <isActive>false</isActive>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Leased</fullName>
                <isActive>false</isActive>
                <label>Leased</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

MODON MRE BPDEV/force-app/main/default/objects/Unit__c/fields/Sub_Status__c.field-meta.xml
<CustomField>
    <fullName>Sub_Status__c</fullName>
    <label>Sub Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Assigned</fullName>
            </value>
            <value>
                <fullName>Un-Assigned</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

MODON MRE BPDEV/force-app/main/default/classes/BlockRequestTriggerHelper.cls
/**********************************************************************************************************************
* Name               : BlockRequestTriggerHelper                                                        
* Description        : This class is helper for Block Request trigger
* Usage              : Called from BlockRequestTriggerHandler
* Created By         : PWC Digital Middle East                                                     
* --------------------------------------------------------------------------------------------------------------------
* Version       Author                              Date            Comment                                                                       
* 1.0           prateek.b.bansal@pwc.com         24 Jan 2024     Initial Draft     
* 1.1           Manoj.vallapuneni@modon.com      24 Dec 2024     Update the Change as par of new status 
******************************************************************************************************************/
public without sharing class BlockRequestTriggerHelper {
    public static void checkBlockApproval(Map<Id, SObject> oldMap, Map<Id, SObject> newMap){
        Map<Id, Block_Request__c> blockRequestToApproveMap = new Map<Id, Block_Request__c>();
        Map<String, String> unitBlockRequestMap = new Map<String, String>();
        for(String key : oldMap.keySet()){
            Block_Request__c newBlock = (Block_Request__c)newMap.get(key);
            Block_Request__c oldBlock = (Block_Request__c)oldMap.get(key);
            if(oldBlock.Status__c == 'In Progress' && newBlock.Status__c == 'Approved'){
                blockRequestToApproveMap.put(key, newBlock);
                unitBlockRequestMap.put(newBlock.Unit__c, key);
            }
        }
        
        if(!blockRequestToApproveMap.isEmpty()){
            List<Unit__c> unitList = new List<Unit__c>();
            for(Block_Request__c brObj : [SELECT Id, Hourstoblock__c, Unit__c, Unit__r.BlockedFor__c, Unit__r.BlockedBy__c, Unit__r.Status__c,Unit__r.Sub_Status__c, CreatedById, Opportunity__c FROM Block_Request__c WHERE Id IN : blockRequestToApproveMap.keySet()]){
               // if(brObj.Unit__r.Status__c != 'Blocked' && brObj.Unit__r.BlockedBy__c == null){ //Update the Change as par of new status
                  if(brObj.Unit__r.Sub_Status__c != 'Assigned' && brObj.Unit__r.BlockedBy__c == null){ //Update the Change as par of new status
                    Unit__c unitObj = new Unit__c();
                    unitObj.Id = brObj.Unit__c;
                    unitObj.Status__c = 'Available';
                    unitObj.Sub_Status__c='Assigned';
                    unitObj.BlockedFor__c = brObj.CreatedById;
                    unitObj.BlockedBy__c = UserInfo.getUserId();
                   	unitObj.Opportunity__c = brObj.Opportunity__c;
                    List<String> tempLst = brObj.Hourstoblock__c.split(' ');
                    if(tempLst.size()>1){
                        unitObj.BlockUntil__c = System.now().addMinutes(Integer.valueOf(tempLst[0]));
                    }else{
                        unitObj.BlockUntil__c = System.now().addHours(Integer.valueOf(brObj.Hourstoblock__c));
                    }
                    //unitObj.BlockUntil__c = System.now().addHours(Integer.valueOf(brObj.Hourstoblock__c));
                    unitList.add(unitObj);
                }else{
                    (newMap.get(brObj.Id)).addError('Unit is already blocked by some other user.');
                }
            }
            if(!unitList.isEmpty()){
                UPDATE unitList;
            }
        }
    }
}