MODON MRE BPDEV/force-app/main/default/objects/SalesOrder__c/SalesOrder__c.object-meta.xml
<CustomObject>
    <label>Sales Order</label>
    <nameField>
        <displayFormat>SO-{00000}</displayFormat>
        <label>Sales Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

MODON MRE BPDEV/force-app/main/default/objects/SalesOrder__c/fields/CustomerAccount__c.field-meta.xml
<CustomField>
    <fullName>CustomerAccount__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Sales Orders</relationshipLabel>
    <relationshipName>Sales_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

MODON MRE BPDEV/force-app/main/default/objects/SalesOrder__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Reservation form generated</fullName>
            </value>
            <value>
                <fullName>Down payment collected</fullName>
            </value>
            <value>
                <fullName>Reservation form signed</fullName>
            </value>
            <value>
                <fullName>Installment Payment Collected</fullName>
            </value>
            <value>
                <fullName>DP Payment Confirmed</fullName>
            </value>
            <value>
                <fullName>SPA Generated</fullName>
            </value>
            <value>
                <fullName>SPA Signed (Customer)</fullName>
            </value>
            <value>
                <fullName>SPA Signed (Modon)</fullName>
            </value>
            <value>
                <fullName>SPA Delivered</fullName>
            </value>
            <value>
                <fullName>Sold</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>System cancelled</fullName>
            </value>
            <value>
                <fullName>KYC - In progress</fullName>
            </value>
            <value>
                <fullName>KYC - Completed / KYC Rejected</fullName>
            </value>
            <value>
                <fullName>Payments Collected</fullName>
            </value>
            <value>
                <fullName>Downpayment Payments Cleared</fullName>
            </value>
            <value>
                <fullName>SPA Sent to customer</fullName>
            </value>
            <value>
                <fullName>SPA Validated</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Cancelled SR</fullName>
            </value>
            <value>
                <fullName>Voided</fullName>
            </value>
            <value>
                <fullName>Pending Blocking Fees</fullName>
            </value>
            <value>
                <fullName>Blocking Fees Collected</fullName>
            </value>
            <value>
                <fullName>Property Transfer Cancelled - SR</fullName>
            </value>
            <value>
                <fullName>Unit Swap Cancelled - SR</fullName>
            </value>
            <value>
                <fullName>Unit Upgrade Cancelled - SR</fullName>
            </value>
            <value>
                <fullName>Unit Cancellation Cancelled - SR</fullName>
            </value>
            <value>
                <fullName>Unit Consolidation Cancelled - SR</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

MODON MRE BPDEV/force-app/main/default/objects/SPAWhatsapp__c/SPAWhatsapp__c.object-meta.xml
<CustomObject>
    <label>SPAWhatsapp</label>
    <nameField>
        <displayFormat>SPA-{0000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SPAWhatsapp</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

MODON MRE BPDEV/force-app/main/default/objects/SPAWhatsapp__c/fields/FileUploaded__c.field-meta.xml
<CustomField>
    <fullName>FileUploaded__c</fullName>
    <defaultValue>false</defaultValue>
    <label>FileUploaded</label>
    <type>Checkbox</type>
</CustomField>

MODON MRE BPDEV/force-app/main/default/objects/SPAWhatsapp__c/fields/Sales_Order__c.field-meta.xml
<CustomField>
    <fullName>Sales_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Order</label>
    <referenceTo>SalesOrder__c</referenceTo>
    <relationshipLabel>SPAWhatsapp</relationshipLabel>
    <relationshipName>SPAWhatsapp</relationshipName>
    <type>Lookup</type>
</CustomField>

MODON MRE BPDEV/force-app/main/default/classes/SPAWhatsappTriggerHelperTest.cls
@IsTest
private class SPAWhatsappTriggerHelperTest {

    // Mock class for HTTP callouts
    private class MockHttpResponseGenerator implements HttpCalloutMock {
        public HTTPResponse respond(HTTPRequest req) {
            HttpResponse res = new HttpResponse();
            res.setHeader('Content-Type', 'application/json');

            if(req.getEndpoint().contains('SPAWhatsappAPI')){
                res.setStatusCode(200);
                res.setBody('{"MessageId":"mockMsgId","BitlyURL":"https://bit.ly/mockUrl","Status":"sent"}');
            } else {
                res.setStatusCode(200);
                res.setBody('{}');
            }
            return res;
        }
    }

    @IsTest
    static void testDownloadSPA_enqueueJob() {
        Id rtId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Person Account').getRecordTypeId();
        Account acc = new Account(FirstName = 'John54454223', LastName = 'Doe54454223', RecordTypeId = rtId);
        insert acc;
        
        // Create SalesOrder
        SalesOrder__c so = new SalesOrder__c(CustomerAccount__c = acc.Id);
        insert so;

        // Create SPAWhatsapp record
        SPAWhatsapp__c spa = new SPAWhatsapp__c(
            Sales_Order__c = so.Id,
            Status__c = 'pending'
        );
        insert spa;

        // Change Status to 'completed' to trigger downloadSPA
        spa.Status__c = 'completed';
		update spa;
        Map<Id, SObject> oldMap = new Map<Id, SObject>{ spa.Id => [SELECT Id, Status__c FROM SPAWhatsapp__c WHERE Id = :spa.Id] };
        List<SObject> newList = new List<SObject>{ spa };
            
        // Create SPAWhatsapp record
        SPAWhatsapp__c spa2 = new SPAWhatsapp__c(
            Sales_Order__c = so.Id,
            Status__c = 'pending'
        );
        insert spa2;

        // Change Status to 'completed' to trigger downloadSPA
        spa2.Status__c = 'completed';
        spa2.FileUploaded__c = true;
		update spa2;
        Map<Id, SObject> oldMap2 = new Map<Id, SObject>{ spa2.Id => [SELECT Id, Status__c, FileUploaded__c FROM SPAWhatsapp__c WHERE Id = :spa2.Id] };
        List<SObject> newList2 = new List<SObject>{ spa2 };    

        Test.startTest();
        SPAWhatsappTriggerHelper.sendEmailMessage(newList, oldMap);
        SPAWhatsappTriggerHelper.downloadSPA(newList, oldMap);
        SPAWhatsappTriggerHelper.sendJOSPA(newList2, oldMap2);
        SPAWhatsappTriggerHelper.sendWhatsappMsgToJOQueueable(new Set<Id>{spa2.Id});
        Test.stopTest();
        // Since it's async, we can't assert job ID directly, but we can check debug logs manually
    }

    @IsTest
    static void testSendWhatsappMessage() {
        // Setup test data
        Id rtId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Person Account').getRecordTypeId();
        Account acc = new Account(FirstName = 'John544541212', LastName = 'Doe544541212', RecordTypeId = rtId);
        insert acc;

        SalesOrder__c so = new SalesOrder__c(CustomerAccount__c=acc.Id);
        insert so;

        SPAWhatsapp__c spa = new SPAWhatsapp__c(
            Sales_Order__c = so.Id,
            Status__c = 'sent',
            DocuSignURL__c = 'https://mock.docusign.net/doc'
        );
        insert spa;

        List<SObject> newList = new List<SObject>{ spa };

        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());
        Test.startTest();
        SPAWhatsappTriggerHelper.sendWhatsappMessage(newList);
        Test.stopTest();
    }

    @IsTest
    static void testSendWhatsappMessageOICAPI_direct() {
        Id rtId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Person Account').getRecordTypeId();
        Account acc = new Account(FirstName = 'John5445498', LastName = 'Doe5445498', RecordTypeId = rtId);
        insert acc;

        SalesOrder__c so = new SalesOrder__c(CustomerAccount__c=acc.Id);
        insert so;

        SPAWhatsapp__c spa = new SPAWhatsapp__c(
            Sales_Order__c = so.Id,
            Status__c = 'sent',
            DocuSignURL__c = 'https://mock.docusign.net/doc'
        );
        insert spa;

        Set<Id> spaIds = new Set<Id>{ spa.Id };

        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());
        Test.startTest();
        SPAWhatsappTriggerHelper.sendWhatsappMessageOICAPI(spaIds);
        SPAWhatsappTriggerHelper.sendWhatsappMsgToQueueable(spaIds);
        SPAWhatsappTriggerHelper.sendEmailMessageFuture(spaIds);
        Test.stopTest();
    }
}