MODON MRE BPDEV/force-app/main/default/objects/SalesOrder__c/SalesOrder__c.object-meta.xml
<CustomObject>
    <label>Sales Order</label>
    <nameField>
        <displayFormat>SO-{00000}</displayFormat>
        <label>Sales Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

MODON MRE BPDEV/force-app/main/default/objects/SalesOrder__c/fields/Resale__c.field-meta.xml
<CustomField>
    <fullName>Resale__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Resale</label>
    <type>Checkbox</type>
</CustomField>

MODON MRE BPDEV/force-app/main/default/objects/SalesOrder__c/fields/Source_Entity__c.field-meta.xml
<CustomField>
    <fullName>Source_Entity__c</fullName>
    <label>Source Entity</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Source_Entity</valueSetName>
    </valueSet>
</CustomField>

MODON MRE BPDEV/force-app/main/default/objects/SalesOrder__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Reservation form generated</fullName>
            </value>
            <value>
                <fullName>Down payment collected</fullName>
            </value>
            <value>
                <fullName>Reservation form signed</fullName>
            </value>
            <value>
                <fullName>Installment Payment Collected</fullName>
            </value>
            <value>
                <fullName>DP Payment Confirmed</fullName>
            </value>
            <value>
                <fullName>SPA Generated</fullName>
            </value>
            <value>
                <fullName>SPA Signed (Customer)</fullName>
            </value>
            <value>
                <fullName>SPA Signed (Modon)</fullName>
            </value>
            <value>
                <fullName>SPA Delivered</fullName>
            </value>
            <value>
                <fullName>Sold</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>System cancelled</fullName>
            </value>
            <value>
                <fullName>KYC - In progress</fullName>
            </value>
            <value>
                <fullName>KYC - Completed / KYC Rejected</fullName>
            </value>
            <value>
                <fullName>Payments Collected</fullName>
            </value>
            <value>
                <fullName>Downpayment Payments Cleared</fullName>
            </value>
            <value>
                <fullName>SPA Sent to customer</fullName>
            </value>
            <value>
                <fullName>SPA Validated</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Cancelled SR</fullName>
            </value>
            <value>
                <fullName>Voided</fullName>
            </value>
            <value>
                <fullName>Pending Blocking Fees</fullName>
            </value>
            <value>
                <fullName>Blocking Fees Collected</fullName>
            </value>
            <value>
                <fullName>Property Transfer Cancelled - SR</fullName>
            </value>
            <value>
                <fullName>Unit Swap Cancelled - SR</fullName>
            </value>
            <value>
                <fullName>Unit Upgrade Cancelled - SR</fullName>
            </value>
            <value>
                <fullName>Unit Cancellation Cancelled - SR</fullName>
            </value>
            <value>
                <fullName>Unit Consolidation Cancelled - SR</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

MODON MRE BPDEV/force-app/main/default/globalValueSets/Source_Entity.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Modon - Egypt</fullName>
    </customValue>
    <customValue>
        <fullName>Modon - UAE</fullName>
    </customValue>
    <masterLabel>Source Entity</masterLabel>
</GlobalValueSet>

MODON MRE BPDEV/force-app/main/default/classes/SalesOrderHistoricalUpdateBatch.cls
public class SalesOrderHistoricalUpdateBatch implements Database.Batchable<sObject>,Database.Stateful {
    public String queryString;
    public SalesOrderHistoricalUpdateBatch(String queryString){
        this.queryString = queryString;
    }
    public Database.QueryLocator start(Database.BatchableContext bc) {
        if(String.isNotBlank(queryString)){
            return Database.getQueryLocator(queryString);
        }
        if(Test.isRunningTest()){
            return Database.getQueryLocator([SELECT Id FROM SalesOrder__c LIMIT 1]);
        }
        List<String> cancellStatus = System.label.CommissionCancelStatus.contains(',')?System.label.CommissionCancelStatus.split(','):new List<String>{System.label.CommissionCancelStatus};
        return Database.getQueryLocator([
            SELECT Id 
            FROM SalesOrder__c 
            WHERE (NOT (Status__c IN :cancellStatus)) 
            AND Resale__c = false 
            AND Source_Entity__c != 'Modon - Egypt'
        ]);
    }
    public void execute(Database.BatchableContext bc, List<SObject> scope) {
        for(SalesOrder__c so:(List<SalesOrder__c>) scope){
           SalesOrderHistoricalUpdateHelper.checkADMStatus(new Set<Id>{so.Id});
           SalesOrderHistoricalUpdateHelper.checkDownPaymentStatus(new Set<Id>{so.Id});
           SalesOrderHistoricalUpdateHelper.checkSPAStatus(new Set<Id>{so.Id});
           SalesOrderHistoricalUpdateHelper.updatePDCStatus(new Set<Id>{so.Id});
        }
    }
    
    public void finish(Database.BatchableContext bc) {
        System.debug('SalesOrderHistoricalUpdateBatch completed.');
    }
}